### DISCUSSION TITLE
Querier not working with Block storage

### DISCUSSION THREAD

**Discussion by vicmania2007** [cortexproject/cortex#3596] [Q&A] [answered]
I am working on implementing block storage cortex solution and in the process of building a cortex cluster. I have hit a roadblock when installing/deploying querier. So far i have installed the following

1. ingester without WAL
2. distributor without ha_tracker
3. compactor without sharding
4. storegatewaywithout sharding
5. etcd cluster for distributed data store

Problem: Not able to install querier service, as it is  throwing the following error.
```
level=info ts=2020-12-11T16:00:25.834913154Z caller=main.go:187 msg="Starting Cortex" version="(version=1.5.0, branch=HEAD, revision=86d95e7)"
level=info ts=2020-12-11T16:00:25.835156771Z caller=server.go:225 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2020-12-11T16:00:25.835411288Z caller=log.go:149 msg="error running cortex" err="etcdclient: no available endpoints\nerror initialising module: ring\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/__w/cortex/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/__w/cortex/cortex/pkg/util/modules/modules.go:75\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:331\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:189\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
```

There is nothing stated in the querier config for providing explicit etcd endpoints or so.. But out of curiosity i provided the etcd endpoints via the CLI to see if that could do something. But then i started seeing some other error.

```
level=info ts=2020-12-11T16:03:20.253764796Z caller=main.go:187 msg="Starting Cortex" version="(version=1.5.0, branch=HEAD, revision=86d95e7)"
level=info ts=2020-12-11T16:03:20.25401412Z caller=server.go:225 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2020-12-11T16:03:20.403290885Z caller=query_logger.go:109 msg="Failed to create directory for logging active queries"
level=error ts=2020-12-11T16:03:20.403349503Z caller=query_logger.go:87 msg="Error opening query log file" file=active-query-tracker/queries.active err="open active-query-tracker/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x24df526, 0x16, 0x14, 0x2aacb80, 0xc000307cb0, 0x2636d20)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/query_logger.go:117 +0x4cd
github.com/cortexproject/cortex/pkg/querier.createActiveQueryTracker(...)
	/__w/cortex/cortex/pkg/querier/querier.go:187
github.com/cortexproject/cortex/pkg/querier.New(0x14, 0x1bf08eb000, 0x10100, 0x2faf080, 0x0, 0x0, 0x8bb2c97000, 0x37e11d600, 0x24df526, 0x16, ...)
	/__w/cortex/cortex/pkg/querier/querier.go:164 +0x5e4
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).initQueryable(0xc000c00000, 0x2b239c0, 0xc000631980, 0xc00064c120, 0xc000700fa0)
	/__w/cortex/cortex/pkg/cortex/modules.go:198 +0x1c3
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule(0xc000138480, 0x7fffa1e00736, 0x7, 0xc000d49d38, 0xc000bfa630, 0xc000307b90, 0xc000d49df0)
	/__w/cortex/cortex/pkg/util/modules/modules.go:103 +0x2c6
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc000138480, 0xc0007ac0f0, 0x1, 0x1, 0xc000701120, 0x22ffb01, 0x2ad8100)
	/__w/cortex/cortex/pkg/util/modules/modules.go:75 +0xfe
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run(0xc000c00000, 0xc000631100, 0x4)
	/__w/cortex/cortex/pkg/cortex/cortex.go:331 +0x125
main.main()
	/__w/cortex/cortex/cmd/cortex/main.go:189 +0xe1e
```

My Deployment code
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-querier
  namespace: default
  labels:
    app: cortex-querier
    chart: cortex-0.2.0
    release: cortex
    heritage: Tiller
  annotations:
    {}
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cortex-querier
      release: cortex
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app: cortex-querier
        name: cortex-querier
        target: querier
        release: cortex
      annotations:
        checksum/config: 6dd406f10b037c8f1727c9703989ae342b09846df41aea9dacbd8d76a7c6fde4
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
        
    spec:
      securityContext:
        {}
        
      initContainers:
        []
        
      containers:
        - name: cortex
          image: "quay.io/cortexproject/cortex:v1.5.0" 
          imagePullPolicy: IfNotPresent
          args:
            - "-target=querier"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-etcd.endpoints=http://etcd-client.default.svc.cluster.local:2379"
          volumeMounts:
            - name: config
              mountPath: /etc/cortex
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          resources:
            limits:
              cpu: 600m
              memory: 4Gi
            requests:
              cpu: 600m
              memory: 2Gi
            
          securityContext:
            readOnlyRootFilesystem: true
          env:
      nodeSelector:
        {}
        
      affinity:
        {}
        
      tolerations:
        []
        
      terminationGracePeriodSeconds: 180
      volumes:
        - name: config
          secret:
            secretName: cortex
        - name: storage
          # emptyDir: {}
          hostPath: 
            path: "/data"
            type: DirectoryOrCreate`
```

My overall config

```yaml
config:
  auth_enabled: false
  ingester_client:
    grpc_client_config:
      max_recv_msg_size: 104857600
      max_send_msg_size: 104857600
      use_gzip_compression: false
  ingester:
    lifecycler:
      join_after: 0s
      final_sleep: 0s
      num_tokens: 256
      ring:
        replication_factor: 2
        kvstore:
          store: "etcd"
  querier:
    default_evaluation_interval: 15s
    store_gateway_addresses: cortex-store-gateway-headless.default.svc.cluster.local:8080
  limits:
    ingestion_rate: 750000
    ingestion_rate_strategy: local
    ingestion_burst_size: 1000000    
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  server:
    http_listen_port: 8080
    grpc_listen_port: 9095
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600
    grpc_server_max_concurrent_streams: 1000
  store_gateway:
    sharding_enabled: false
  storage:
    engine: blocks
  blocks_storage:
    tsdb:
      dir: /tmp/cortex/tsdb
      block_ranges_period: ['0h1m0s']
    bucket_store:
      sync_dir: /tmp/cortex/tsdb-sync
    backend: azure
    azure:
      account_key: <key>
      account_name: cortexblockstorage
      container_name: cortex-poc
  distributor:
    ring:
      kvstore:
        store: "etcd"
    shard_by_all_labels: true
    pool: 
      health_check_ingesters: true
```

**Comment by jtlisi** [comment]
@vicmania2007 FYI: I updated you comment to include proper formatting for your code blocks

```yaml
    azure:
      account_key: cI/hhGjWOfkNo5xeP8Fvn524unLN2N9wf6dDhh8+zA8HO2Qq1Tac5v8X9iARZWvlid9avMwu9ni5QNksVtZ/Pg==
      account_name: cortexblockstorage
      container_name: cortex-poc
```

Also you pasted a key into your comment, I highly recommend you invalidate this key ASAP
