### DISCUSSION TITLE
Bad Gateway - Not able to add Cortex data source

### DISCUSSION THREAD

**Discussion by vicmania2007** [cortexproject/cortex#3702] [Q&A]
I have my block storage cortex setup with the write path working and data getting into Azure blob. Even though the querier is working, i am not able to add cortex as data source into grafana to validate the read path. I dont know what I am missing.

**To Test:**
I have made the nginx service as nodeport and performing port forwarding, so i can test locally. 
`akc port-forward service/cortex 8080:8080
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080`

**Grafana Error:**
![image](https://user-images.githubusercontent.com/6048841/104788771-11fa6980-5761-11eb-8534-67b42764bcd3.png)

**1.This is my config:**
```
auth_enabled: false
blocks_storage:
  azure:
    account_key: <Hided key>
    account_name: cortexblockstorage
    container_name: cortex-poc
  backend: azure
  bucket_store:
    sync_dir: /data/cortex/tsdb-sync
  tsdb:
    block_ranges_period:
    - 0h1m0s
    dir: /data/cortex/tsdb
distributor:
  pool:
    health_check_ingesters: true
  ring:
    kvstore:
      store: etcd
  shard_by_all_labels: true
ingester:
  lifecycler:
    final_sleep: 0s
    join_after: 0s
    num_tokens: 256
    ring:
      kvstore:
        store: etcd
      replication_factor: 2
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: false
limits:
  enforce_metric_name: false
  ingestion_burst_size: 1000000
  ingestion_rate: 750000
  ingestion_rate_strategy: local
  reject_old_samples: true
  reject_old_samples_max_age: 168h
querier:
  default_evaluation_interval: 15s
  store_gateway_addresses: dns+cortex-store-gateway-headless.default.svc.cluster.local:8080
server:
  grpc_listen_port: 9095
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 8080
storage:
  engine: blocks
store_gateway:
  sharding_enabled: false
```

**2. Querier logs:**
`level=info ts=2021-01-15T23:22:33.275253807Z caller=main.go:187 msg="Starting Cortex" version="(version=1.5.0, branch=HEAD, revision=86d95e7)"
level=info ts=2021-01-15T23:22:33.275478666Z caller=server.go:225 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-01-15T23:22:33.431412647Z caller=worker.go:65 msg="no address specified, not starting worker"
level=info ts=2021-01-15T23:22:33.431577807Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2021-01-15T23:22:33.431611178Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2021-01-15T23:22:33.43167128Z caller=module_service.go:58 msg=initialising module=ring
level=info ts=2021-01-15T23:22:33.431721627Z caller=module_service.go:58 msg=initialising module=store-queryable
level=info ts=2021-01-15T23:22:33.431852617Z caller=module_service.go:58 msg=initialising module=distributor-service
level=info ts=2021-01-15T23:22:35.628224319Z caller=fetcher.go:453 org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.170020084s cached=153 returned=153 partial=0
level=info ts=2021-01-15T23:22:36.981312096Z caller=cortex.go:355 msg="Cortex started"
level=info ts=2021-01-15T23:27:41.617091687Z caller=fetcher.go:453 org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1.855914346s cached=163 returned=163 partial=0
level=info ts=2021-01-15T23:32:44.310315136Z caller=fetcher.go:453 org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1.828943292s cached=173 returned=173 partial=0`

**3. Nginx configmap:**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: cortex-nginx
  namespace: default
  labels:
    app: cortex-nginx
    chart: cortex
    release: cortex
    heritage: Tiller
data:
  nginx.conf: |-
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver coredns.kube-system.svc.cluster.local;

      server { # simple reverse-proxy
        listen 80;

        proxy_set_header X-Scope-OrgID 0;

        location = /healthz {
          return 200 'alive';
        }

        location = /api/prom/push {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local$request_uri;
        }

        location = /ring {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local$request_uri;
        }
        location = /config {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local$request_uri;
        }
        location = /all_user_stats {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local$request_uri;
        }

        location ~ /api/prom/.* {
          proxy_pass      http://cortex-querier.default.svc.cluster.local$request_uri;
        }
      }
    }
```

**Comment by jtlisi** [comment]
Hey @vicmania2007,

One thing I noticed is you are using port 8080 for HTTP requests. However, you do not define the port in the nginx config. You can see in the official Cortex helm chart [here](https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/nginx-config.yaml) that the ports should be explicitly defined. Could you update your nginx config to following and see if that works:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: cortex-nginx
  namespace: default
  labels:
    app: cortex-nginx
    chart: cortex
    release: cortex
    heritage: Tiller
data:
  nginx.conf: |-
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver coredns.kube-system.svc.cluster.local;

      server { # simple reverse-proxy
        listen 80;

        proxy_set_header X-Scope-OrgID 0;

        location = /healthz {
          return 200 'alive';
        }

        location = /api/prom/push {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local:8080$request_uri;
        }

        location = /ring {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local:8080$request_uri;
        }
        location = /config {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local:8080$request_uri;
        }
        location = /all_user_stats {
          proxy_pass      http://cortex-distributor.default.svc.cluster.local:8080$request_uri;
        }

        location ~ /api/prom/.* {
          proxy_pass      http://cortex-querier.default.svc.cluster.local:8080$request_uri;
        }
      }
    }
```

**Reply by jtlisi** [reply]
@vicmania2007 Where are you running Grafana? You said you port-forwarded Nginx to your local and queried it from Grafana. Does your local grafana have access to the ports running on your node? For instance, if you are running Grafana in a container it may not have access unless you specify it.

Second, have you tried port-forwarding the queriers to your local machine and querying them instead of Nginx?

**Reply by vicmania2007** [reply]
1. I tested with Grafana via docker in my local (port forwarding) also from a hosted grafana to add as a datasource. Getting same error.
2. what i also tried testing after your comment was to remove nginx and directly hit the querier service. 

```
╰─$ akc port-forward service/cortex-querier 31500:80
Forwarding from 127.0.0.1:31500 -> 8080
Forwarding from [::1]:31500 -> 8080
```

When i hit localhost:31500 i see this screen
 
![image](https://user-images.githubusercontent.com/6048841/105556891-fbac5a80-5cd8-11eb-9317-8aaca88cbb94.png)



and when i hit localhost:31500/config 

![image](https://user-images.githubusercontent.com/6048841/105556825-cd2e7f80-5cd8-11eb-8abc-b6cf6c493ab0.png)
, i see **target=querier**, which means i am hitting the querier pod for sure. But localhost:31500/api/prom is not working.  I also tested port forwarding from the querier prod, same behavior.

Do i have to query from a different port or is that a different URL for querying?

**Comment by vicmania2007** [comment]
I tried the following, but still facing the same issues.

1. Changed the nginx config with the 8080 port. I am still getting bad gateway.
```
location ~ /api/prom/.* {
  proxy_pass      http://cortex-querier.default.svc.cluster.local:8080$request_uri;
}
```
 When i was doing above i noticed that querier was giving out weird logs. I couldnt understand much but thought it might be connected to store-gateway.  Checking the store-gateway logs, i found this. I created a new Azure container and redeployed the store-gateway, after which I didnt see this error message.

```
level=info ts=2021-01-20T16:51:41.313344795Z caller=gateway.go:308 msg="synchronizing TSDB blocks for all users" reason=periodic
level=warn ts=2021-01-20T16:51:41.358615026Z caller=gateway.go:312 msg="failed to synchronize TSDB blocks" reason=periodic err="cannot list blobs in directory  (iteration #1): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /__w/cortex/cortex/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:9452473f-c01e-0084-624c-ef4e9e000000\nTime:2021-01-20T16:51:41.3512202Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'PPy/pYXwetv0S/jdhoZ/mzbG8HT55JESY4p2iT5xx3Q=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:a33038c6-3b16-487e-710a-50fbcd2f4c00\nx-ms-date:Wed, 20 Jan 2021 16:51:41 GMT\nx-ms-version:2018-11-09\n/cortexblockstorage/cortex-poc\ncomp:list\ndelimiter:/\nrestype:container\ntimeout:61'.\n   Code: AuthenticationFailed\n   GET https://cortexblockstorage.blob.core.windows.net/cortex-poc?comp=list&delimiter=%2F&restype=container&timeout=61\n   Authorization: REDACTED\n   User-Agent: [Thanos Azure-Storage/0.7 (go1.14.9; linux)]\n   X-Ms-Client-Request-Id: [a33038c6-3b16-487e-710a-50fbcd2f4c00]\n   X-Ms-Date: [Wed, 20 Jan 2021 16:51:41 GMT]\n   X-Ms-Version: [2018-11-09]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [770]\n   Content-Type: [application/xml]\n   Date: [Wed, 20 Jan 2021 16:51:40 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [9452473f-c01e-0084-624c-ef4e9e000000]\n\n\n"
level=info ts=2021-01-20T16:55:51.721369585Z caller=gateway.go:308 msg="synchronizing TSDB blocks for all users" reason=periodic
```

3. Querier yaml config

```
---
# Source: cortex/templates/querier-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cortex-querier
  namespace: default
  labels:
    app: cortex-querier
    chart: cortex-0.2.0
    release: cortex
    heritage: Tiller
  annotations:
    {}
    
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  # type: NodePort
  # ports:
  #   - nodePort: 31000
  #     port: 9090
  #     targetPort: 9090
  selector:
    app: cortex-querier
    release: cortex
---
# Source: cortex/templates/querier-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-querier
  namespace: default
  labels:
    app: cortex-querier
    chart: cortex-0.2.0
    release: cortex
    heritage: Tiller
  annotations:
    {}
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cortex-querier
      release: cortex
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app: cortex-querier
        name: cortex-querier
        target: querier
        release: cortex
      annotations:
        checksum/config: 6dd406f10b037c8f1727c9703989ae342b09846df41aea9dacbd8d76a7c6fde4
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
        
    spec:
      securityContext:
        {}
        
      initContainers:
        []
        
      containers:
        - name: cortex
          image: "quay.io/cortexproject/cortex:v1.5.0" 
          imagePullPolicy: IfNotPresent
          args:
            - "-target=querier"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-etcd.endpoints=http://etcd-client.default.svc.cluster.local:2379"
            # - "-querier.frontend-address=http://cortex-query-frontend.default.svc.cluster.local:80"
          volumeMounts:
            - name: config
              mountPath: /etc/cortex
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          resources:
            limits:
              cpu: 600m
              memory: 4Gi
            requests:
              cpu: 600m
              memory: 2Gi
          env:
      nodeSelector:
        {}
        
      affinity:
        {}
        
      tolerations:
        []
        
      terminationGracePeriodSeconds: 180
      volumes:
        - name: config
          secret:
            secretName: cortex
        - name: storage
          # emptyDir: {}
          hostPath: 
            path: "/querier/data"
            type: DirectoryOrCreate
```
