### DISCUSSION TITLE
distributor ha_tracker config

### DISCUSSION THREAD

**Discussion by zhuchqun** [cortexproject/cortex#5538] [Q&A]
I want to implement distributor ha_tracker through etcd, but I check that there is no corresponding prefix in etcd, please help me. Here is my relevant configuration:
```
distributor:
  pool:
    health_check_ingesters: true
  ha_tracker:
    enable_ha_tracker: true
    ha_tracker_update_timeout: 15s
    ha_tracker_update_timeout_jitter_max: 5s
    ha_tracker_failover_timeout: 30s
    kvstore:
      store: "etcd"
      prefix: "/cortex/ha-tracker/"
      etcd:
        endpoints: ["192.168.2.61:2379","192.168.2.30:2379","192.168.2.159:2379"]
        dial_timeout: 10s
        max_retries: 10
        tls_enabled: true
        tls_cert_path: "/opt/cortex/pki/server.crt"
        tls_key_path: "/opt/cortex/pki/server.key"
        tls_ca_path: "/opt/cortex/pki/ca.crt"
        tls_insecure_skip_verify: true
  max_recv_msg_size: 104857600
  remote_timeout: 15s
  extra_queue_delay: 0s
  sharding_strategy: default
  shard_by_all_labels: true
  extend_writes: true
  ring:
    kvstore:
      store: "etcd"
      prefix: "/cortex/collectors/"
      etcd:
        endpoints: ["192.168.2.61:2379","192.168.2.30:2379","192.168.2.159:2379"]
        dial_timeout: 10s
        max_retries: 10
        tls_enabled: true
        tls_cert_path: "/opt/cortex/pki/server.crt"
        tls_key_path: "/opt/cortex/pki/server.key"
        tls_ca_path: "/opt/cortex/pki/ca.crt"
        tls_insecure_skip_verify: false
    heartbeat_period: 5s
    heartbeat_timeout: 1m0s
    instance_id: node1
    instance_port: 9005
    instance_addr: "192.168.61"
  instance_limits:
    max_ingestion_rate: 0
    max_inflight_push_requests: 0
```
please help me. Thanks.

**Comment by friedrichg** [comment]
Not sure, I understand what you mean by: "there is no prefix".
This is my configuration and it works fine:

```
distributor:
  ha_tracker:
    enable_ha_tracker: true
    ha_tracker_failover_timeout: 5m0s
    ha_tracker_update_timeout: 2m0s
    kvstore:
      etcd:
        endpoints:
        - etcd-client.cortex.svc.cluster.local.:2379
      prefix: prom_ha/
      store: etcd
  instance_limits:
    max_inflight_push_requests: 40
  ring:
    kvstore:
      prefix: ""
      store: memberlist
  shard_by_all_labels: true
  sharding_strategy: shuffle-sharding
```
