### DISCUSSION TITLE
Querier error "expanding series: consistency check failed because some blocks were not queried" also I have store gateway storage available

### DISCUSSION THREAD

**Discussion by Rahuly360** [cortexproject/cortex#5549] [General]
"expanding series: consistency check failed because some blocks were not queried: blocks"

Anyone has any idea about the above issue? My Cortex store-gateway storage is only 2% full. Still showing above issue

Duplicate of : https://github.com/cortexproject/cortex/issues/4431

@saidben0 @uberspot

**Comment by friedrichg** [comment]
please share configuration for storegateway and content of meta.json for the block that fails

**Reply by Rahuly360** [reply]
```
store_gateway:
  sharding_enabled: false
  sharding_ring:
    kvstore:
      store: consul
      prefix: collectors/
      dynamodb:
        region: ""
        table_name: ""
        ttl: 0s
      consul:
        host: localhost:8500
        acl_token: ""
        http_client_timeout: 20s
        consistent_reads: false
        watch_rate_limit: 1
        watch_burst_size: 1
      etcd:
        endpoints: []
        dial_timeout: 10s
        max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        username: ""
        password: ""
      multi:
        primary: ""
        secondary: ""
        mirror_enabled: false
        mirror_timeout: 2s
    heartbeat_period: 15s
    heartbeat_timeout: 1m0s
    replication_factor: 3
    tokens_file_path: ""
    zone_awareness_enabled: false
    wait_stability_min_duration: 1m0s
    wait_stability_max_duration: 5m0s
    instance_id: cortex-distributor-74bc5f6585-l5cl5
    instance_interface_names:
    - eth0
    - en0
    instance_port: 0
    instance_addr: ""
    instance_availability_zone: ""
  sharding_strategy: default
tenant_federation:
  enabled: true
```
