### DISCUSSION TITLE
deleting a tenant (compactor?)

### DISCUSSION THREAD

**Discussion by aep** [cortexproject/cortex#6753] [General]
hi, i was wondering how to delete a tenant.

i _think_ the way to do it is enabling the [overrides-exporter](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L1032)  and then in cortex-runtime-config, set 

```yaml
data:
  runtime_config.yaml: |
    overrides:
      tenant123:
        compactor_blocks_retention_period: 1s
```

which would cause compactor to auto reload that config and then delete the blocks of this tenant.

is this the correct way to approach this?
seems rather odd to have a _deleted_ tenant be in the config which may pile up eventually.
