### ISSUE TITLE
ingester frequently terminated due to error

### ISSUE THREAD

**Issue by mjsjinsu** [cortexproject/cortex#1256]
I setup cortex with cassandra chunk storage.
Not only deployment successful and PromQL working well(http://nginx:30080/api/prom/api/v1/query?query=up) but also cortex ring (Distributor/ring) show all active status.

But when flushing triggered, ingester pod raised error and terminated with metric initialized.
I think it is supposed to relate `-ingester.max-chunk-idle` duration.
I try changing `-ingester.max-chunk-idle` parameter, I can see terminated interval changed

```
NAME                              READY     STATUS    RESTARTS   AGE
alertmanager-5d4df4bb5c-bdd5j     1/1       Running   0          4h
cassandra-0                       1/1       Running   0          4h
cassandra-1                       1/1       Running   0          4h
cassandra-2                       1/1       Running   0          4h
configs-db-75c6b4df96-hbqjs       1/1       Running   0          4h
configs-dcd654584-n56tz           1/1       Running   0          4h
consul-76669d6c85-t4lxj           1/1       Running   0          4h
distributor-54868b7499-kk6n9      1/1       Running   0          4h
ingester-856747d6b9-6qfc4         1/1       Running   22         2h
ingester-856747d6b9-fzghz         1/1       Running   22         2h
ingester-856747d6b9-pwdk2         1/1       Running   22         2h
memcached-cf8545f6d-kd7l2         1/1       Running   0          4h
nginx-55b9f744d5-p47xm            1/1       Running   0          4h
querier-bd7b99df7-nrjc5           1/1       Running   0          4h
query-frontend-6b8ffd69d5-v2mtw   1/1       Running   0          4h
ruler-7c9bfcd58-sf5qx             1/1       Running   0          4h
table-manager-6886cddcdd-b6gw7    1/1       Running   0          4h
```

```
- name: ingester
        image: ingester:20190304
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - -ingester.join-after=30s
        - -ingester.claim-on-rollout=false
        - -ingester.num-tokens=512
        - -ingester.chunk-encoding=3
        - -consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -chunk.storage-client=cassandra
        - -cassandra.addresses=cassandra.monitoring.svc.cluster.local:9042
        - -cassandra.keyspace=cortex
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2019-01-01
        - -dynamodb.original-table-name=cortex
        - -memcached.hostname=memcached.monitoring.svc.cluster.local
        - -memcached.service=memcached
        - -store.index-cache-write.memcached.hostname=memcached.monitoring.svc.cluster.local.
        - -store.index-cache-write.memcached.expiration=24h
```

```
level=debug ts=2019-03-04T07:48:11.633987338Z caller=flush.go:210 msg="Ingester.flushLoop() exited"
panic: runtime error: integer divide by zero
goroutine 637 [running]:
github.com/cortexproject/cortex/pkg/chunk.(*PeriodicTableConfig).TableFor(0xc4201ca450, 0x16947a7ab6a, 0x10285e0, 0xc42b1d7140)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/schema_config.go:438 +0xe2
github.com/cortexproject/cortex/pkg/chunk.SchemaConfig.ChunkTableFor(0xc4201ca360, 0x2, 0x2, 0x0, 0x0, 0x7ffdec0462b4, 0x9, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/schema_config.go:428 +0x83
github.com/cortexproject/cortex/pkg/chunk/cassandra.(*StorageClient).PutChunks(0xc4201588c0, 0x13953e0, 0xc4302d5da0, 0xc42e1f5570, 0x1, 0x1, 0x0, 0x0)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/cassandra/storage_client.go:273 +0x155
github.com/cortexproject/cortex/pkg/chunk.(*store).PutOne(0xc4201661e0, 0x13953e0, 0xc4302d5da0, 0x16947a7ab6a, 0x16947a7ab6a, 0x5b3b66a5db2d3e08, 0xc4203e33cd, 0x1, 0x16947a7ab6a, 0x16947a7ab6a, ...)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go:133 +0x119
github.com/cortexproject/cortex/pkg/chunk.compositeStore.Put.func1(0x16947a7ab6a, 0x16947a7ab6a, 0x1395620, 0xc4201661e0, 0x0, 0x0)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:63 +0x91
github.com/cortexproject/cortex/pkg/chunk.compositeStore.forStores(0xc4201996e0, 0x2, 0x2, 0x16947a7ab6a, 0x16947a7ab6a, 0xc43038ba10, 0x15f0820a, 0xc42a71e478)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:140 +0x1de
github.com/cortexproject/cortex/pkg/chunk.compositeStore.Put(0xc4201996e0, 0x2, 0x2, 0x13953e0, 0xc4302d5da0, 0xc42e1f5420, 0x1, 0x1, 0xc42e1f5500, 0xc43026af00)
    /go/src/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:62 +0x131
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).flushChunks(0xc42018ed80, 0x13953e0, 0xc4302d5da0, 0x5b3b66a5db2d3e08, 0xc4302d5dd0, 0xc422f5f428, 0x1, 0x1, 0xc4300e8e10, 0x13953e0)
    /go/src/github.com/cortexproject/cortex/pkg/ingester/flush.go:332 +0x3d2
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).flushUserSeries(0xc42018ed80, 0x1a, 0xc4203e33cd, 0x1, 0x5b3b66a5db2d3e08, 0x0, 0x0, 0x0)
    /go/src/github.com/cortexproject/cortex/pkg/ingester/flush.go:280 +0x855
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).flushLoop(0xc42018ed80, 0x1a)
    /go/src/github.com/cortexproject/cortex/pkg/ingester/flush.go:221 +0xec
created by github.com/cortexproject/cortex/pkg/ingester.New
    /go/src/github.com/cortexproject/cortex/pkg/ingester/ingester.go:181 +0x372
```
