### ISSUE TITLE
S3 : Set up DNS-Style URL

### ISSUE THREAD

**Issue by JqckB** [cortexproject/cortex#1411]
After trying to test Cortex with an Ceph S3 Gateway, which isn't AWS S3, I got an issue with the construct of the s3 URL when passing this config :
```
schema:
  configs:
  - from: 2019-03-25
    store: boltdb
    object_store: s3
    schema: v10
    index:
      prefix: index_
      period: 168h

storage:
  boltdb:
    directory: /tmp/cortex/index
  aws:
    s3: s3://access_key:access_secret@IP:PORT/cortex-dc1
```

Here is the Cortex error when trying to push into this S3 : 
```
level=error ts=2019-05-23T09:58:51.957080106Z caller=flush.go:223 org_id=fake msg="failed to flush user" err="RequestError: send request failed\ncaused by: Put http://cortex-dc1.172.24.35.59:8080/fake/ca3178a3f5afcf7d%3A16ae4198a12%3A16ae4198a12%3A4f9c409e: dial tcp: lookup cortex-dc1.172.24.35.59 on 8.8.8.8:53: read udp 172.17.0.2:41917->8.8.8.8:53: i/o timeout"
``` 

I think it is about the DNS-Style URL, which is on AWS "%(bucket)s.s3.amazonaws.com" but not existing in my own implementation of S3.

Is it possible to introduce a variable that let us declare that DNS-Style, or at least not use this DNS-Style and let the URL untouched ?
