### ISSUE TITLE
Support cassandra/s3 as the table/storage client stores

### ISSUE THREAD

**Issue by rcallphin** [cortexproject/cortex#1627]
As it is today if you want to use Cassandra as the table store, you also have to use Cassandra as your chuck store. And if you want to use an s3 compatible backend then you have to use DynamoDB for your table. It would be nice to add support to run both of these together.

**Comment by jtlisi** [comment]
I think that you can operate cortex with a cassandra index and an s3 chunk store as is. If you supply cortex with a schema that includes:
```yaml
schema:
  configs:
  - from: 2019-03-25
    store: cassandra
    object_store: s3
    schema: v10
    index:
      prefix: index_
      period: 168h
```

S3 uses a bucket instead of a table, so the table-manager does not need to generate chunk tables. Is there something I'm missing you are running into when trying to deploy cortex?
