### ISSUE TITLE
Cortex chunk table doesn't create in Cassandra

### ISSUE THREAD

**Issue by luguangzhen** [cortexproject/cortex#1684]
Follow steps from https://github.com/cortexproject/cortex/blob/master/docs/getting_started.md#single-instance-single-process, a single cortex is installed. And the single-process-config.yml file is modified below, in order to use cassandra for storage.

```
schema:
  configs:
  - from: 2019-03-25
    store: boltdb
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: portal_chunk_
      period: 3m
storage:
  boltdb:
    directory: /tmp/cortex/index

  cassandra:
    addresses: 127.0.0.1
    port: 9042
    keyspace: schema1
```

Then start cortex with command:`./cortex -config.file=./docs/single-process-config.yml  -chunk.storage-client=cassandra`. It seems that tables are created into cassandra, but it's not.

```
level=info ts=2019-09-19T11:32:32.043506309Z caller=table_manager.go:363 msg="creating table" table=portal_chunk_8681741
level=info ts=2019-09-19T11:32:32.043519523Z caller=table_manager.go:363 msg="creating table" table=portal_chunk_8685534
...

level=error ts=2019-09-19T11:34:43.182454562Z caller=flush.go:226 org_id=fake msg="failed to flush user" err="unconfigured table portal_chunk_8716051"
level=error ts=2019-09-19T11:34:43.182458072Z caller=flush.go:226 org_id=fake msg="failed to flush user" err="unconfigured table portal_chunk_8716051"
...

```

**Comment by luguangzhen** [comment]
When set store db with cassandra, both index and chunk tables are created into cassandra.

```
schema:
  configs:
  - from: 2019-03-25
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: portal_chunk_
      period: 168h
storage:
  cassandra:
    addresses: 127.0.0.1
    port: 9042
    keyspace: demo919
```

Is it mean if you choose cassandra as the object_store db，you should also use cassandra as store db?
