### ISSUE TITLE
Table Manager fails to manage table if metrics.url return unexpected result

### ISSUE THREAD

**Issue by rkomara** [cortexproject/cortex#1707]
After enabling table manager to monitor cortex metrics for DynamoDB, we see following set of messages in logs:

```
level=debug ts=2019-10-01T23:56:00.782868238Z caller=schema_config.go:399 msg="Table is Active" tableName=cortex_data_2595 provisionedRead=50 provisionedWrite=25 useOnDemandMode=true useWriteAutoScale=false useReadAutoScale=false
level=info ts=2019-10-01T23:56:00.782888789Z caller=table_manager.go:206 msg="synching tables" num_expected_tables=10 expected_tables=10
level=debug ts=2019-10-01T23:56:00.80611095Z caller=table_manager.go:376 msg="checking provisioned throughput on table" table=cortex_index_2595
level=error ts=2019-10-01T23:56:01.811753514Z caller=table_manager.go:174 msg="error syncing tables" err="expected one sample stream for queue: 0"
```
This points to unexpected result from internal Prometheus. However, receiving this type of response stops table manager to apply default scale down on table. This situation caused our DynamoDB tables to stay with active capacity provisioned even after they were no longer actively written to. Yep, cost skyrocketed.

The proposal is to perform default adjustments even when fetching related metrics from Prometheus fails. Especially for non-active tables.

Configuration storage section: (we use yaml config file for cortex)
```
storage:
    aws:
        dynamodbconfig:
            dynamodb: dynamodb://<auth>@us-west-2
            metrics:
                url: http://retrieval.monitoring.svc.cluster.local:9090
        s3: http://<auth>@us-west-2/<bucket>
```
