### ISSUE TITLE
How Cortex can connect to Cassandra Cluster

### ISSUE THREAD

**Issue by techy16** [cortexproject/cortex#1731]
Can you please help to provide the information how can i connect Cortex Cluster running in K8 to my Cassandra Cluster running on host. I see the Ingester deploy yaml where dynamo db details are passed and S3 as well. For Cassandra how can we pass the info, how the ingester will read the Cassandra details. Please help to provide the details

**Comment by paulcostinean** [comment]
The docs are not that helpful on this but you can infer how the config should look like by reading the config source code.

Assuming you're using the `schemaConfig` in the k8s example, the following should work for configuring cassandra and s3:

```yaml
storage:
  cassandra:
    addresses: <cassandra-service-dns>
    keyspace: <cassandra-keyspace>
  aws:
    s3: <s3-url>
```
