### ISSUE TITLE
msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)

### ISSUE THREAD

**Issue by techy16** [cortexproject/cortex#1769]
I am getting this error from the ingester logs and i see that table manager has created around 2000 tables in Cassandra and visible to me. But getting the below error 

level=error ts=2019-10-30T17:20:36.366864066Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"

Any suggestions?

**Comment by techy16** [comment]
Now i am getting error after updating the table manager with below enteries for Cassandra along with dynamodb for specifying the chunk table not sure whether it is correct or not. But after updating with below one i am atleast getting the below error. Can you pls help what is missing and where is the problem?

        - -chunk.storage-client=cassandra
        - -cassandra.timeout=1000ms
        - -cassandra.keyspace=cortex
        - -cassandra.port=7011
        - -dynamodb.chunk-table.period=168h0m0s
        - -dynamodb.chunk-table.prefix=cortex_chunks_
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2019-10-30
        - -dynamodb.daily-buckets-from=2019-10-30
        - -dynamodb.base64-buckets-from=2019-10-30
        - -dynamodb.chunk-table.from=2019-10-30

level=error ts=2019-10-30T21:00:50.289501923Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="unconfigured table cortex_chunks_2599"

**Comment by techy16** [comment]
Now ingester is throwing this error

level=error ts=2019-10-30T22:04:55.129090694Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"
level=error ts=2019-10-30T22:04:55.129068158Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"
level=error ts=2019-10-30T22:04:55.129112204Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"
level=error ts=2019-10-30T22:04:55.129122333Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"
level=error ts=2019-10-30T22:04:55.1290556Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"
level=error ts=2019-10-30T22:04:55.129134203Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)"

**Comment by pracucci** [comment]
I'm not much familiar about running Cortex with Cassandra. However, looking at this log:

```
level=error ts=2019-10-30T22:04:55.129134203Z caller=flush.go:226 org_id=0 msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO [(]...)"
```

I've the feeling that the table name is missing. I would have expected `INSERT INTO table-name (` instead of `INSERT INTO (`.

Can you share your config (make sure to strip away sensitive data - if any), in particular the schema config? Which schema version are you running?

**Comment by techy16** [comment]
I am deploying on Kubernetes and i am not sure on Schema congis but below are the configs which i am passing in deployment yaml for both ingester and table-manager

        name: table-manager
    spec:
      containers:
      - name: table-manager
        image: cortex-table-manager
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -chunk.storage-client=cassandra
        - -cassandra.addresses=*********************
        - -cassandra.auth=true
        - -cassandra.keyspace=cortex
        - -cassandra.port=****
        - -cassandra.username=****
        - -cassandra.password=****
        - -cassandra.timeout=5000ms
        - -dynamodb.chunk-table.period=168h0m0s
        - -dynamodb.chunk-table.prefix=cortex_chunks_
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2019-10-30
        - -dynamodb.daily-buckets-from=2019-10-30
        - -dynamodb.base64-buckets-from=2019-10-30
        - -dynamodb.chunk-table.from=2019-10-30
        ports:
        - containerPort: 80


This is for Ingester

      - name: ingester
        image: cortex-ingester:latest
        imagePullPolicy: IfNotPresent
        args:
        - -target=ingester
        - -ingester.join-after=30s
        - -ingester.claim-on-rollout=true
        - -chunk.storage-client=cassandra
        - -consul.hostname=consul.com-cortex.svc.cluster.local:8500
        - -cassandra.addresses=***************
        - -cassandra.auth=true
        - -cassandra.keyspace=cortex
        - -cassandra.port=*****
        - -cassandra.username=****
        - -cassandra.password=*****
        - -memcached.hostname=memcached.com-cortex.svc.cluster.local
        - -memcached.timeout=100ms
        - -memcached.service=memcached
        ports:
        - containerPort: 80
        readinessProbe:

**Comment by JohnCMcDonough** [comment]
how was this issue fixed? I'm trying to use azure's cosmosdb as an index and chunk store. I'm seeing this issue when I go to shut down a cortex instance.

```yaml
auth_enabled: true

server:
  http_listen_port: 9009
  log_level: debug

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true

ingester:
  #chunk_idle_period: 15m

  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    # address: 127.0.0.1

    # We want to start immediately and flush on shutdown.
    join_after: 0
    claim_on_rollout: false
    final_sleep: 0s
    num_tokens: 512

    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

# Use local storage - BoltDB for the index, and the filesystem
# for the chunks.
schema:
  configs:
  - from: 2019-07-29
    store: boltdb
    object_store: filesystem
    schema: v10
    index:
      prefix: index_
      period: 168h
  - from: 2019-07-29
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h

storage:
  cassandra: 
    addresses: "<REDACTED>"
    port: 10350
    keyspace: cortex
    disable_initial_host_lookup: false
    SSL: true
    host_verification: false
    auth: true
    username: "<REDACTED>"
    password: "<REDACTED>"
    timeout: "5000ms"
    connect_timeout: "5000ms"
    replication_factor: 1

  boltdb:
    directory: /tmp/cortex-config/index

  filesystem:
    directory: /tmp/cortex-config/chunks
```

**Comment by JohnCMcDonough** [comment]
I found the issue. I didn't add a chunk section to the schema config.

I now understand the linked issue. The Schemas aren't described in the reference config. I had to dig through the code to find my issue.

```yaml
      - from: 2019-07-29
        store: cassandra
        object_store: cassandra
        schema: v10
        index:
          prefix: index_
          period: 168h
        chunks: # <-- ADDING THIS FIXED IT
          prefix: chunk_
          period: 168h
```
