### ISSUE TITLE
Rate query result lag  behind

### ISSUE THREAD

**Issue by canghai118** [cortexproject/cortex#1924]
I use rate() function on node_cpu_seconds_total to calculate cpu utility,  the promql is like below:
`avg by (mode) (rate(node_cpu_seconds_total{instance=~"$instance", mode!="idle"}[$interval]))`

`$interval` value is 5s, and the source prometheus target scrape interval is 2s
The weird thing is: the recent  query result is missing.  so the line in grafana is behind.  but the other query worked normally. for a clear compare, I also add the another query:
`sum by (mode) (node_cpu_seconds_total{instance=~"$instance", mode!="idle"})`, and the result seems ok.

![image](https://user-images.githubusercontent.com/3394863/71143749-a04aa600-2256-11ea-8536-51dcba0c0e2a.png)

the lag time periodicity changed from about serval seconds to more than 30 seconds. this cause my recording rule not work as expected
```yaml
- name: node10s
  interval: 10s
  rules:
    - record: "instance:node_cpu_used_seconds:rate10s"
      expr: sum by (instance) (rate(node_cpu_seconds_total{mode=~"user|system"}[10s]))
```
when the lag is longer than 10s, the above record rule create nothing. the final graph will be something blow:
![image](https://user-images.githubusercontent.com/3394863/71144309-87db8b00-2258-11ea-8317-d851dc9baa86.png)

I recently upgrade my cortex cluster from v0.3.0 to v0.4.0, and change chunk encoding to bigchunk. 

From the above, when the lag is happened, can I tell all the data write to cortex is lag behind  or is just something wrong about the rate function
default `-promql.lookback-delta` is 5m, that's maybe why the second query seems normal ?
