### ISSUE TITLE
feat: support YAML format for config API

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2170]
### WHAT

Support posting YAML body to configs API: `/api/prom/configs/rules`.

### WHY

Current format example:
```json
{
    "id": 4,
    "rule_format_version": "2",
    "rules_files": {
        "rule1.yml": "groups:\n- name: container_spec_memory_limit_bytes:container\n  rules:\n  - record: container_spec_memory_limit_bytes:container\n    expr: max by (namespace,container)(container_spec_memory_limit_bytes{container!=\"POD\",container!=\"\"})\n"
    }
}
```

It's hard to read and write without some custom tool.

If we support YAML, the example become:
```yml
id: 1
rule_format_version: 2
rules_files:
  rule1.yml: |
    groups:
    - name: container_spec_memory_limit_bytes:container
      rules:
      - record: container_spec_memory_limit_bytes:container
        expr: max by (namespace,container)(container_spec_memory_limit_bytes{container!=\"POD\",container!=\"\"})
```

It's much easier for reading and writing.

### Backward Compatibility

Since YAML is superset for JSON, there is no backward compatibility problem.
