### ISSUE TITLE
Distributor Ring KVStore config from file not honored

### ISSUE THREAD

**Issue by josnidhin** [cortexproject/cortex#2292]
Cortex version: v0.7.0

I am trying to run a distributor service with Consul as the KVStore for both Ring and HA Tracker. The following is the yaml config file I had created.

```yaml
target: distributor
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9009

  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      store: consul
      consul:
        host: "172.31.0.114:8500"
      prefix: "ha-tracker/"
  ring:
    kvstore:
      store: consul
      consul:
        host: "172.31.0.114:8500"
      prefix: "collectors/"
```

This is how I start the distributor
```shell
$ cortex -config.file=/home/jose/cortex/distributor.yaml
```

I get the following error logs
```
level=error ts=2020-03-19T04:33:20.045107618Z caller=client.go:198 msg="error getting path" key=collectors/ring err="Get http://localhost:8500/v1/kv/collectors/ring?consistent=&wait=10000ms: dial tcp 127.0.0.1:8500: connect: connection refused" 
```

As you can see from the logs it is looking for consul at `localhost:8500`

I updated the config file to the following
```yaml
target: distributor
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9009

  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  ha_tracker:
    enable_ha_tracker: true
```

changed the start cmd to this
```shell
$ cortex \
    -ring.store=consul \
    -ring.prefix=collectors/ \
    -consul.hostname=172.31.0.114:8500 \
    -distributor.ha-tracker.store=consul \
    -distributor.ha-tracker.prefix=ha-tracker/ \
    -distributor.ha-tracker.consul.hostname=172.31.0.114:8500 \
    -config.file=/home/jose/cortex/distributor.yaml
```
Now everything seems fine I have not yet tested this but at least I don't see any error logs.
Why is this happening? Am I doing something wrong when defining the config file?
