### ISSUE TITLE
gocql: dns error:

### ISSUE THREAD

**Issue by vacheli** [cortexproject/cortex#2320]
Deployment config following as:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingester
  namespace: monitoring-external
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingester

  # Ingesters are not ready for at least 1 min
  # after creation.  This has to be in sync with
  # the ring timeout value, as this will stop a
  # stampede of new ingesters if we should loose
  # some.
  minReadySeconds: 60

  # Having maxSurge 0 and maxUnavailable 1 means
  # the deployment will update one ingester at a time
  # as it will have to stop one (making one unavailable)
  # before it can start one (surge of zero)
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    metadata:
      labels:
        name: ingester
    spec:
      # Give ingesters 40 minutes grace to flush chunks and exit cleanly.
      # Service is available during this time, as long as we don't stop
      # too many ingesters at once.
      terminationGracePeriodSeconds: 2400

      containers:
      - name: ingester
        image: quay.io/cortexproject/cortex:v0.7.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=ingester
        - -ingester.join-after=30s
        - -ingester.claim-on-rollout=true
        - -consul.hostname=consul-cortex.monitoring-external.svc.cluster.local:8500
        - -schema-config-file=/etc/cortex/schema.yaml
        - -cassandra.addresses="10.8.51.200,10.8.51.201,10.8.51.202"
        - -cassandra.keyspace=cortex
        - -cassandra.auth=true
        - -cassandra.username=123
        - -cassandra.password=123
        - -memcached.hostname=memcached-cortex.monitoring-external.svc.cluster.local
        - -memcached.timeout=100ms
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
        resources:
          requests:
            cpu: "4"
            memory: "10Gi"
          limits:
            cpu: "4"
            memory: "10Gi"
      nodeSelector:
        app: cortex
      tolerations:
      - key: "db"
        operator: "Equal"
        value: "cortex"
        effect: "NoSchedule"
      volumes:
        - name: config-volume
          configMap:
            name: schema-config
```
Pod log
```
 Loading...2020-03-24 06:39:45.912431 I | gocql: dns error: lookup "10.8.51.200: no such host
2020-03-24 06:39:45.912479 I | gocql: dns error: lookup 10.8.51.202": no such host
2020-03-24 06:39:46.122615 I | gocql: dns error: lookup "10.8.51.200: no such host
2020-03-24 06:39:46.122652 I | gocql: dns error: lookup 10.8.51.202": no such host
```
