### ISSUE TITLE
Make config file cleaner

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2373]
Current config file format is not user friendly.
* It's hard to know a mapping between flags and config without reading docs.
* It's hard to know which component use which config section.

Let's make config file format cleaner.

* `query_range` is used by query-frontend => move to under `frontend`
* `frontend_worker` is used by querier => move to `querier`

* if a flag named `-querier.frontend-client.grpc-max-recv-msg-size`, the equivalent config should be:
```yaml
querier:
  frontend-client:
    grpc-max-recv-msg-size: xxx
```

Since it's a big breaking change, we should do it before release v1.0
