### ISSUE TITLE
Single process high memory usage 

### ISSUE THREAD

**Issue by vishnubraj** [cortexproject/cortex#2406]
I am using single process cortex with 246k seried in 32GB ram system. The initial cortex usage is 11GB and slowly it consumes all the 32Gb and dies without any error.  I chnaged the max_chunk_age  from 12h to 1h still the same happens. Can you please help on this.. 

https://files.slack.com/files-pri/T08PSQ7BQ-F0115L6A0D9/image.png 

```
auth_enabled: false

server:
  http_listen_port: 9009
 # http_listen_address: 10.3.1.48

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true

ingester:
  max_chunk_age: 1h
  lifecycler:
    # The address to advertise for this ingester. Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    address: 10.3.1.114

    # We want to start immediately and flush on shutdown.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints: ["10.3.0.206:2380"]
      replication_factor: 1

schema:
  configs:
  - from: 2020-03-20
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: chunk_
      period: 168h

storage:
  cassandra:
    addresses: 10.3.1.48 # configure cassandra addresses here.
    keyspace: cortex   # configure desired keyspace here.

limits:
  ingestion_rate: 250000
  max_samples_per_query: 10000000
  max_series_per_query: 1000000
  max_series_per_user: 50000000
  max_series_per_metric: 500000
```
