### ISSUE TITLE
rpc error: code = Unimplemented desc = unknown service cortex.Ingester 

### ISSUE THREAD

**Issue by vishnubraj** [cortexproject/cortex#2407]
I am getting below error continuously, it was working when i initialy started with kv store, and after stop and stop of cortex its not working. If i move the config to inmemory kv store it works fine again. 
Can you please check this. 
```
level=warn ts=2020-04-06T07:32:45.945516937Z caller=logging.go:49 traceID=4a505f9c3668827f msg="POST /api/prom/push (500) 2.231303ms Response: \"rpc error: code = Unimplemented desc = unknown service cortex.Ingester\\n\" ws: false; Content-Encoding: snappy; Content-Length: 12660; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.8.0; X-Prometheus-Remote-Write-Version: 0.1.0;
```

```
auth_enabled: false

server:
  http_listen_port: 9009

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true

ingester:
  max_chunk_age: 1h
  lifecycler:
    # The address to advertise for this ingester. Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    address: 10.3.1.114

    # We want to start immediately and flush on shutdown.
    join_after: 0
  #  claim_on_rollout: false
    final_sleep: 0s
    num_tokens: 512
    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints: ["10.3.0.206:2380"]
      replication_factor: 1

# Use cassandra as storage -for both index store and chunks store.
schema:
  configs:
  - from: 2020-03-20
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: chunk_
      period: 168h

storage:
  cassandra:
    addresses: 10.3.1.48 # configure cassandra addresses here.
    keyspace: cortex   # configure desired keyspace here.

limits:
  ingestion_rate: 250000
  max_samples_per_query: 10000000
  max_series_per_query: 1000000
  max_series_per_user: 50000000
  max_series_per_metric: 500000
```
