### ISSUE TITLE
[bug] -distributor.ring.consul.* not working

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2455]
# BUG Report

I found `-distributor.ring.consul.*` flags is not working while old `-consul.*` is working.

# Reproduce

```yml
version: "3"
services:
  consul:
    image: consul
    command:
      - agent
      - -dev
      - -client=0.0.0.0
      - -log-level=warn
  distributor:
    image: quay.io/cortexproject/cortex
    command:
      - -target=distributor
      #- -distributor.ring.consul.hostname=consul:8500 # don't work
      - -consul.hostname=consul:8500 # work!
```

# Reason

The distributor module depends on ring module.

distributor register `-distributor.ring.consul.*` first
https://github.com/cortexproject/cortex/blob/master/pkg/distributor/distributor_ring.go#L36

then ring overwrite those flags to `-consul.*`
https://github.com/cortexproject/cortex/blob/master/pkg/cortex/modules.go#L142
