### ISSUE TITLE
Doesn't create chunks/indexes tables properly in Cassandra

### ISSUE THREAD

**Issue by williansvi** [cortexproject/cortex#2588]
Having this in logs repeatedly:

`level=error ts=2020-05-12T14:24:01.772755202Z caller=flush.go:207 org_id=fake msg="failed to flush user" err="unconfigured table stage_chunks_18394"`

And in Cassandra no table (indexes / chunks) is created...

Cortex version: v1.0.1
Cassandra: 3.11

Config:

```
target: all
http_prefix: /api/prom
auth_enabled: false

server:
  http_listen_port: 80
  grpc_listen_port: 9095

  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

  log_level: info

ingester:
  lifecycler:
    ring: &consul
      kvstore:
        store: consul
        prefix: collectors/
        consul:
          host: consul:8500
    join_after: 30s

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  ring: *consul

querier:
  query_store_after: 1h

chunk_store:
  chunk_cache_config:
    redis: &redis
      endpoint: redis:6379
  write_dedupe_cache_config:
    redis: *redis
schema:
  configs:
    - from: "2020-05-01"
      schema: v10
      store: cassandra
      object_store: cassandra
      chunks:
        period: 1d
        prefix: stage_chunks_
      index:
        period: 1d
        prefix: stage_index_

storage:
  engine: chunks
  cassandra:
    addresses: cassandra
    port: 9042
    auth: true
    username: cassandra
    password: cassandra
    keyspace: cortex
    replication_factor: 1
  index_queries_cache_config:
    redis: *redis
```

Cassandra setup following: https://cortexmetrics.io/docs/production/cassandra/#setup-a-locally-running-cassandra (for testing purposes)

Any suggestion?
