### ISSUE TITLE
Cassandra read and write consistency levels

### ISSUE THREAD

**Issue by kwSeo** [cortexproject/cortex#2607]
We are using the Apache Cassandra as the Cortex storage.
Cortex provides an option for setting the consistency level but it can not use read and write consistency levels separately.
We want to configure read and write consistency levels differently.
(https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlConfigConsistency.html)

How about providing the configuration options as below?

```yaml
storage:
  cassandra:
    addresses: "127.0.0.1"
    keyspace: "cortex"
    consistency: "QUORUM".   # for backward compatibility
    read_consistency: "ONE"
    write_consistency: "QUORUM"
```
