### ISSUE TITLE
Cannot connect to configs-db from configs pods

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#2625]
I am running Cortex on k8s. Upgraded to 1.0.1 from 0.4.0. -  Configs pods went into the running state then restarted constantly because it could not connect to the configs-db.

here are the errors encountered :
```
level=warn ts=2020-05-24T19:27:55.109490306Z` caller=postgres.go:63 msg="db connection not established, retrying..." error="pq: empty password returned by client"
```
or 
```
level=info ts=2020-05-24T21:58:33.34384927Z caller=server.go:147 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2020-05-24T21:58:33.416812508Z caller=postgres.go:63 msg="db connection not established, retrying..." error="pq: password authentication failed for user \"postgres\""
level=warn ts=2020-05-24T21:58:34.526182619Z caller=postgres.go:63 msg="db connection not established, retrying..." error="pq: password authentication failed for user \"postgres\""
level=warn ts=2020-05-24T21:58:36.570799272Z caller=postgres.go:63 msg="db connection not established, retrying..." error="pq: password authentication failed for user \"postgres\""
level=warn ts=2020-05-24T21:58:40.624258274Z caller=postgres.go:63 msg="db connection not established, retrying..." error="pq: password authentication failed for user \"postgres\""
```
Here is the deployment yaml for configs-db

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configs-db
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configs-db
  template:
    metadata:
      labels:
        name: configs-db
      annotations:
        prometheus.io.scrape: "false"
    spec:
      nodeSelector:
        dedicated: cortex
      containers:
      - name: configs-db
        image: postgres:12
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_DB
             value: configs
          - name: POSTGRES_PASSWORD
             valueFrom:
                secretKeyRef:
                name: config-db-secret
                key: pgl_pass
          - name: POSTGRES_HOST_AUTH_METHOD
            value: password
        ports:
        - containerPort: 5432
```
and here is the configs deployment yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configs
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: configs
  replicas: 2
  template:
    metadata:
      labels:
        name: configs
    spec:
      nodeSelector:
        dedicated: cortex
      containers:
        - name: configs
          image: quay.io/cortexproject/cortex:v1.0.1
          imagePullPolicy: IfNotPresent
          args:
            - -target=configs
            - -server.http-listen-port=80
            - -configs.database.uri=postgres://postgres@configs-db.monitoring.svc.cluster.local:5432/configs?sslmode=disable
            - -configs.database.migrations-dir=/migrations
          env: 
            - name: POSTGRES_PASSWORD
               valueFrom:
                  secretKeyRef:
                      name: config-db-secret
                      key: pgl_pass
          ports:
            - containerPort: 80
```
I checked the secret and it returned the correct value.  I went into the configs container and POSTGRES_PASSWORD environment variable has the right value also
The configs pods went into a restart after it is running for a while and cannot connect to the db

 I can get this to connect if I set the db auth method to “trust”,  not a good approach for a production environment

Any suggestion to try?
