### ISSUE TITLE
Table manager creates chunks tables when my schema is configured for s3

### ISSUE THREAD

**Issue by samitpal** [cortexproject/cortex#2719]
I setup dynamodb for index and s3 for chunks. But table-manager creates chunks tables in addition to the index tables. I guess i need to remove the chunks related config which perhaps will fix the issue? Here is my schema file. 
```
configs:
- from: 2020-05-21
  schema: v9
  index:
    period: 1w
    prefix: cortex_index_
    tags:
      sc_product_name: cortex
  chunks:
    period: 1w
    prefix: cortex_chunks_
  store: aws
  object_store: s3
```

Looking at the table-manager [code](https://github.com/cortexproject/cortex/blob/85f93ff4abd7af81a5eeeae0e07379dd6ff2071d/pkg/chunk/table_manager.go#L414) it seems to be checking for the chunks prefix which is true in my case. But wondering if there should be an additional check like `config.ObjectType == aws` when creating the chunks table?
