### ISSUE TITLE
Missing chunks and  index config causing silent failure

### ISSUE THREAD

**Issue by jaybatra26** [cortexproject/cortex#2731]
**If the following configuration is missing, Cortex fails silently without a proper explanation. 
In my opinion, this should be validated when Cortex loads the config file.**
For chunks
```
chunks:
      prefix: chunks_
      period: 1w 
```

For Index
```
index:
      prefix: index_
      period: 1w 
```

**Comment by bboreham** [comment]
I think the context for this issue was taking the example config and editing it to work with DynamoDB.  So the whole file that creates the issue is:

```
# Configuration for running Cortex in single-process mode.
# This should not be used in production.  It is only for getting started
# and development.
​
# Disable the requirement that every request to Cortex has a
# X-Scope-OrgID header. `fake` will be substituted in instead.
auth_enabled: false
​
server:
  http_listen_port: 9009
​
  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000
​
distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
​
ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true
​
ingester:
  # We want our ingesters to flush chunks at the same time to optimise
  # deduplication opportunities.
  spread_flushes: true
  chunk_age_jitter: 0
​
  walconfig:
    wal_enabled: true
    recover_from_wal: true
    wal_dir: /tmp/cortex/wal
​
  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    # address: 127.0.0.1
​
    # We want to start immediately and flush on shutdown.
    join_after: 0
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /tmp/cortex/wal/tokens
​
    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
​
schema:
  configs:
  - from: 2020-06-01
    store: aws-dynamo
    object_store: aws-dynamo
    schema: v9
    index:
      prefix: index_
      period: 1w 
​
storage:
  aws:
    dynamodb:
      dynamodb_url: dynamodb://u:p@127.0.0.1:8000
​
frontend_worker:
  match_max_concurrent: true
```

run with `cortex -config-file foo.yaml`
