### ISSUE TITLE
404 page not found-I needHelp

### ISSUE THREAD

**Issue by sun-iot** [cortexproject/cortex#2836]
The Cortex API for Configs API and Ruler . I encountered this problem .
Somrthing like this:
```yaml

ruler:
  enable_sharding: true
  enable_api: true
  alertmanager_url: http://{IP}:9093
  ring:
    kvstore:
      store: etcd
      prefix: rulers/
      etcd:
        endpoints: 
        - http://{IP}:2379

configs:
  database:
    uri: postgres: 
    password_file: 
  api:
    notifications:
      disable_email: false    
      disable_webhook: false
```
But I used curl -H 'X-Scope-OrgID:1' http://localhost:9009/api/prom/configs/alertmanager , 
just like this：
```shell
404 page not found
```
![](https://blog-resource.gitee.io/prometheus/cortex/error-404.png)
