### ISSUE TITLE
query-frontend: Different HTTP Headers on /api/v1/query and /api/v1/query_range calls

### ISSUE THREAD

**Issue by Jakob3xD** [cortexproject/cortex#2875]
Hello, the query fronted sets different HTTP Host Headers depending on the Prometheus API call.
In front of Cortex is an Nginx which listen to `api-cortex.example.com`.
There is another Nginx in front of the Prometheus which should listen to `cortex-thanos.example.com`.
Depending on the Prometheus API endpoint Cortex sets different Host Headers.
This causes Nginx to chose the first server_name if finds as `api-cortex.example.com` is not configured.

Cortex is running inside Docker.
Testet with Cortex: v1.0.0, v1.1.0, v1.2.0

cortex.yml
```
auth_enabled: false
target: query-frontend
http_prefix:
server:
  http_listen_port: 9091
  http_listen_address: localhost
  grpc_listen_address: localhost
  log_level: debug
query_range:
  split_queries_by_interval: 24h
  align_queries_with_step: true
  cache_results: true
  results_cache:
    max_freshness: 1m
    cache:
      enable_fifocache: true
      fifocache:
        size: 5120
        validity: 3h
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  downstream_url: https://cortex-thanos.example.com
```
Nginx Logs:
```
26404#26404: *1 http request line: "GET /api/v1/query?query=1%2B1 HTTP/1.1"
26404#26404: *1 http header: "Host: api-cortex.example.com"
```
```
26405#26405: *2 http request line: "GET /api/v1/query_range?end=1594741440&query=[...]&start=1594684800&step=480 HTTP/1.1"
26405#26405: *2 http header: "Host: cortex-thanos.example.com"
```
