### ISSUE TITLE
Flexibility with indexing labels

### ISSUE THREAD

**Issue by jaybatra26** [cortexproject/cortex#2910]
Currently, all the labels are indexed.
I would like the option to say "exclude the indexing of labels which have less number of values"

Since there are many labels like `instance, job, etc` which have only one value. These can be skipped while indexing. This is a little complicated to enable it on the command line. I would like to put it in the config file under the `exclude_labels` section.

The idea is to skip the labels mentioned under the exclude_labels section. 
This can be done by skipping the [matcher loop ](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/series_store.go#L291) for all the excluded labels.

The configuration should look like this
```
exclude_labels:
  12768:
  - metric_name: go_gc_duration_seconds
    label_name: instance
  - metric_name: go_heap_size
    label_name: job
  19771:
  - metric_name: scrape_series_added
    label_name: job
```
