### ISSUE TITLE
New ingester pods don't become ready

### ISSUE THREAD

**Issue by waseem-h** [cortexproject/cortex#2913]
Hi,
I'm running cortex in openshift with cassandra as backend as well as etcd for kv store with memcached clusters for caches and indexes. We do regular maintenance of our openshift nodes and we drain them frequently. We already have 1 ingester pod per node scheduled so we don't kill more than 1 pod at once. When an ingester pod gets killed, the new one's /ready endpoint always throws 503 error and it never becomes ready. Here are the logs from the new ingester pod (i have debug logging enabled):
```
level=info ts=2020-07-22T11:48:53.562804747Z caller=server.go:179 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=debug ts=2020-07-22T11:48:53.563105274Z caller=api.go:93 msg="api: registering route" methods= path=/config auth=false
level=debug ts=2020-07-22T11:48:53.563156194Z caller=api.go:93 msg="api: registering route" methods= path=/ auth=false
level=warn ts=2020-07-22T11:48:53.563357917Z caller=experimental.go:19 msg="experimental feature in use" feature="DNS-based memcached service discovery"
level=warn ts=2020-07-22T11:48:53.569296885Z caller=experimental.go:19 msg="experimental feature in use" feature="DNS-based memcached service discovery"
level=warn ts=2020-07-22T11:48:53.576033945Z caller=experimental.go:19 msg="experimental feature in use" feature="DNS-based memcached service discovery"
level=warn ts=2020-07-22T11:48:53.582732081Z caller=experimental.go:19 msg="experimental feature in use" feature="Cassandra Backend"
level=warn ts=2020-07-22T11:48:53.619431946Z caller=experimental.go:19 msg="experimental feature in use" feature="Cassandra Backend"
level=debug ts=2020-07-22T11:48:53.652200448Z caller=api.go:93 msg="api: registering route" methods= path=/ingester/flush auth=false
level=debug ts=2020-07-22T11:48:53.652333271Z caller=api.go:93 msg="api: registering route" methods= path=/ingester/shutdown auth=false
level=debug ts=2020-07-22T11:48:53.652435944Z caller=api.go:93 msg="api: registering route" methods= path=/ingester/push auth=true
level=debug ts=2020-07-22T11:48:53.652498206Z caller=api.go:93 msg="api: registering route" methods= path=/flush auth=false
level=debug ts=2020-07-22T11:48:53.652543535Z caller=api.go:93 msg="api: registering route" methods= path=/shutdown auth=false
level=debug ts=2020-07-22T11:48:53.652592038Z caller=api.go:93 msg="api: registering route" methods= path=/push auth=true
level=debug ts=2020-07-22T11:48:53.65263418Z caller=api.go:93 msg="api: registering route" methods= path=/services auth=false
level=info ts=2020-07-22T11:48:53.652693724Z caller=main.go:119 msg="Starting Cortex" version="(version=1.1.0, branch=HEAD, revision=9db28c16)"
level=debug ts=2020-07-22T11:48:53.652861057Z caller=module_service.go:48 msg="module waiting for initialization" module=ingester waiting_for=runtime-config
level=info ts=2020-07-22T11:48:53.653023459Z caller=module_service.go:58 msg=initialising module=store
level=info ts=2020-07-22T11:48:53.653820529Z caller=module_service.go:58 msg=initialising module=runtime-config
level=info ts=2020-07-22T11:48:53.65381657Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2020-07-22T11:48:53.653861309Z caller=manager.go:109 msg="runtime config disabled: file not specified"
level=debug ts=2020-07-22T11:48:53.654053128Z caller=module_service.go:48 msg="module waiting for initialization" module=ingester waiting_for=memberlist-kv
level=debug ts=2020-07-22T11:48:53.654083668Z caller=module_service.go:48 msg="module waiting for initialization" module=ingester waiting_for=store
level=info ts=2020-07-22T11:48:53.654117909Z caller=module_service.go:58 msg=initialising module=ingester
level=info ts=2020-07-22T11:48:53.654230746Z caller=lifecycler.go:485 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2020-07-22T11:48:53.654683961Z caller=cortex.go:336 msg="Cortex started"
level=info ts=2020-07-22T11:48:53.65901329Z caller=lifecycler.go:509 msg="instance not found in ring, adding with no tokens" ring=ingester
level=debug ts=2020-07-22T11:49:23.667502712Z caller=lifecycler.go:357 msg="JoinAfter expired" ring=ingester
level=info ts=2020-07-22T11:49:23.66756926Z caller=lifecycler.go:361 msg="auto-joining cluster after timeout" ring=ingester
level=debug ts=2020-07-22T11:49:58.924998432Z caller=logging.go:44 traceID=7452c457c26efe4b msg="GET /ready (503) 2.901898ms"
level=debug ts=2020-07-22T11:50:08.924172679Z caller=logging.go:44 traceID=3231cae80bc0b5b1 msg="GET /ready (503) 2.596767ms"
level=debug ts=2020-07-22T11:50:18.924553212Z caller=logging.go:44 traceID=75de5405b4123536 msg="GET /ready (503) 2.877078ms"
level=debug ts=2020-07-22T11:50:28.923849417Z caller=logging.go:44 traceID=27d7461962aea33d msg="GET /ready (503) 2.174031ms"
level=debug ts=2020-07-22T11:50:38.924902873Z caller=logging.go:44 traceID=3e07588d7be19908 msg="GET /ready (503) 2.903305ms"
level=debug ts=2020-07-22T11:50:48.923708021Z caller=logging.go:44 traceID=4ec75d1e2a2c1599 msg="GET /ready (503) 2.228006ms"
level=debug ts=2020-07-22T11:50:58.924004081Z caller=logging.go:44 traceID=16a8b782d249eee6 msg="GET /ready (503) 2.3529ms"
level=debug ts=2020-07-22T11:51:08.924588801Z caller=logging.go:44 traceID=2ab0e12412e7209f msg="GET /ready (503) 2.605825ms"
level=debug ts=2020-07-22T11:51:18.924313993Z caller=logging.go:44 traceID=77a40c362775b83c msg="GET /ready (503) 2.533376ms"
level=debug ts=2020-07-22T11:51:28.924193547Z caller=logging.go:44 traceID=4768f7bf7b987773 msg="GET /ready (503) 2.414374ms"
level=debug ts=2020-07-22T11:51:38.924561842Z caller=logging.go:44 traceID=27b7d6bf730db527 msg="GET /ready (503) 2.917226ms"
level=debug ts=2020-07-22T11:51:48.925180437Z caller=logging.go:44 traceID=5ed170777fdefdd0 msg="GET /ready (503) 3.540147ms"
level=debug ts=2020-07-22T11:51:58.924590433Z caller=logging.go:44 traceID=b7668d18ec4edfc msg="GET /ready (503) 2.86502ms"
level=debug ts=2020-07-22T11:52:08.925608755Z caller=logging.go:44 traceID=ee26eaa515a89e1 msg="GET /ready (503) 3.794088ms"
level=debug ts=2020-07-22T11:52:10.637729546Z caller=logging.go:44 traceID=868f8d918eb326 msg="GET /ready (503) 3.049259ms"
level=debug ts=2020-07-22T11:52:18.924007098Z caller=logging.go:44 traceID=1224deb4b6adc59e msg="GET /ready (503) 2.488725ms"
level=debug ts=2020-07-22T11:52:28.924720264Z caller=logging.go:44 traceID=44bd9544ca836a9a msg="GET /ready (503) 2.673008ms"
level=debug ts=2020-07-22T11:52:38.923766071Z caller=logging.go:44 traceID=1e1f1f7c292081af msg="GET /ready (503) 2.176767ms"
level=debug ts=2020-07-22T11:52:40.637866766Z caller=logging.go:44 traceID=964a8aa72c27079 msg="GET /ready (503) 3.22584ms"
level=debug ts=2020-07-22T11:52:48.923934439Z caller=logging.go:44 traceID=637f83c247584209 msg="GET /ready (503) 2.304449ms"
level=debug ts=2020-07-22T11:52:58.924085069Z caller=logging.go:44 traceID=472c55e20b408aa2 msg="GET /ready (503) 2.612969ms"
level=debug ts=2020-07-22T11:53:08.92389509Z caller=logging.go:44 traceID=7e42803a1b244ca5 msg="GET /ready (503) 2.403107ms"
level=debug ts=2020-07-22T11:53:10.639287843Z caller=logging.go:44 traceID=59caa7d6fa2f14cc msg="GET /ready (503) 4.087766ms"
level=debug ts=2020-07-22T11:53:18.924263612Z caller=logging.go:44 traceID=35830dd293fa76aa msg="GET /ready (503) 2.461383ms"
level=debug ts=2020-07-22T11:53:28.924009881Z caller=logging.go:44 traceID=69401da79b0c3c6f msg="GET /ready (503) 2.520883ms"
level=debug ts=2020-07-22T11:53:38.924127816Z caller=logging.go:44 traceID=3be20ed63691de57 msg="GET /ready (503) 2.382404ms"
level=debug ts=2020-07-22T11:53:40.637746912Z caller=logging.go:44 traceID=4ffa64780445f173 msg="GET /ready (503) 2.933653ms"
level=debug ts=2020-07-22T11:53:48.924729547Z caller=logging.go:44 traceID=5dd8c8822aa26d4c msg="GET /ready (503) 2.846531ms"
level=debug ts=2020-07-22T11:53:58.924329326Z caller=logging.go:44 traceID=1f2d5dd17c068a9d msg="GET /ready (503) 2.635114ms"
level=debug ts=2020-07-22T11:54:08.924865236Z caller=logging.go:44 traceID=53579f132d849a80 msg="GET /ready (503) 2.901618ms"
level=debug ts=2020-07-22T11:54:10.637147304Z caller=logging.go:44 traceID=80415decb0b9404 msg="GET /ready (503) 2.623914ms"
level=debug ts=2020-07-22T11:54:18.924769002Z caller=logging.go:44 traceID=5baf92baf7ed3f35 msg="GET /ready (503) 2.75706ms"
level=debug ts=2020-07-22T11:54:28.924758717Z caller=logging.go:44 traceID=24777c76608db518 msg="GET /ready (503) 2.989636ms"
```

My cortex config:
```
config:
  query_range:
    results_cache:
      cache:
        memcached_client:
          addresses: dns+memcached-results.ocp-supporting-services.svc.cluster.local:11211
          service: memcached-results
  chunk_store:
    chunk_cache_config:
      memcached_client:
        addresses: dns+memcached-chunk.ocp-supporting-services.svc.cluster.local:11211
        service: memcached-chunk
    write_dedupe_cache_config:
      memcached_client:
        addresses: dns+memcached-write-dedupe.ocp-supporting-services.svc.cluster.local:11211
        service: memcached-write-dedupe
  server:
    log_level: debug
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600
    grpc_server_max_concurrent_streams: 1000
  schema:
    configs:
    - from: 2020-07-07
      store: cassandra
      object_store: cassandra
      schema: v10
      index:
        prefix: index_
        period: 72h
      chunks:
        prefix: chunk_
        period: 72h
  auth_enabled: false
  limits:
    accept_ha_samples: true
    ha_cluster_label: cluster
    ha_replica_label: replica
    ingestion_rate: 250000
    ingestion_burst_size: 500000
  distributor:
    ha_tracker:
      enable_ha_tracker: true
      kvstore:
        store: etcd
        prefix: "collectors/"
        etcd:
          endpoints:
          - etcd-0.etcd-headless.ocp-supporting-services.svc.cluster.local:2379
          - etcd-1.etcd-headless.ocp-supporting-services.svc.cluster.local:2379
          - etcd-2.etcd-headless.ocp-supporting-services.svc.cluster.local:2379
          dial_timeout: 10s
          max_retries: 10
  ingester_client:
      grpc_client_config:
        # Configure the client to allow messages up to 100MB.
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        use_gzip_compression: true
  ingester:
    lifecycler:
      join_after: 30s
      final_sleep: 0s
      num_tokens: 512
      ring:
        replication_factor: 1
        kvstore:
          store: etcd
          prefix: "collectors/"
          etcd:
            endpoints:
            - etcd-0.etcd-headless.ocp-supporting-services.svc.cluster.local:2379
            - etcd-1.etcd-headless.ocp-supporting-services.svc.cluster.local:2379
            - etcd-2.etcd-headless.ocp-supporting-services.svc.cluster.local:2379
            dial_timeout: 10s
            max_retries: 10
        heartbeat_timeout: 1m
  storage:
    cassandra:
      addresses: "cassandra-0.cassandra.ocp-supporting-services.svc.cluster.local,cassandra-1.cassandra.ocp-supporting-services.svc.cluster.local,cassandra-2.cassandra.ocp-supporting-services.svc.cluster.local"
      keyspace: cortex
      auth: false
    index_queries_cache_config:
      memcached_client:
        addresses: dns+memcached-index-queries.ocp-supporting-services.svc.cluster.local:11211
        service: memcached-index-queries
```

Also, just so you know, I'm running it via cortex-helm-chart's latest version.

I also have set `terminationGracePeriodSeconds` to `2400` so that the handover succeeds. But I still see that the ingester is not coming up. Do I need to configure something else as well to ensure that a new ingester comes up even if the old one fails to hand over? Also what exactly happens to the data if an ingester cannot hand over? How much data is lost?
