### ISSUE TITLE
Cassandra Schema causes query errors when chunks is not Specified.

### ISSUE THREAD

**Issue by jonathansm1th** [cortexproject/cortex#2925]
My use case is Cassandra for index only. Object_store chunks are stored separately in S3. The Cassandra schema causes the following query error if you do not specify the `chunks:` `prefix` values: 

> msg="failed to flush user" err="line 1:13 no viable alternative at input '(' (INSERT INTO  [(]...)

Given this schema ( no `chunks:` specified )
```yaml
    - from: 2020-07-22
      store: cassandra
      object_store: s3
      schema: v10
      index:
        prefix: index_
        period: 168h
```

What is unmarshalled with defaults, has chunks.prefix as "", which appears to cause Cassandra query errors due to the empty prefix (table name).

```yaml
  - from: 2020-07-22    
    store: cassandra
    object_store: s3
    schema: v10
    index:
      prefix: index_
      period: 1w
      tags: {}
    chunks:
      prefix: ""
      period: 0s
      tags: {}
```

Once again, this time defining the `chunks:` element resolves the error, but creates unused `chunks_` tables in Cassandra.

```yaml
  configs:
  - from: "2020-07-22"
    store: cassandra
    object_store: s3
    schema: v10
    index:
      prefix: index_
      period: 1w
      tags: {}
    chunks:
      prefix: chunk_
      period: 1w
      tags: {}
    row_shards: 16
```

Here is a similar issue (however, without separately using S3 for chunk storage) https://github.com/cortexproject/cortex/issues/1769
