### ISSUE TITLE
Prometheus-compatible end point /api/v1/rules does not return all namespaces

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [cortexproject/cortex#2947]
These are some dummy namespaces I have on my cortex instance for experimenting (the following output is from `/rules`):

```
asdf:
- name: MyVM
  interval: 0s
  rules:
  - record: ""
    alert: NeverFires
    expr: rate(process_cpu_seconds_total[1m]) > 10000
    for: 1m
    labels: {}
    annotations: {}
rules:
- name: AllInstances
  interval: 0s
  rules:
  - record: ""
    alert: DownStatus
    expr: up == 0
    for: 5s
    labels:
      severity: something
    annotations:
      arbitrarykey: Just some test.
      title: Instance {{ $labels.instance }} is down.
- name: RecordingGroup
  interval: 0s
  rules:
  - record: job:http_inprogress_requests:sum
    alert: ""
    expr: sum(http_inprogress_requests) by (job)
    for: 0s
    labels: {}
    annotations: {}
```

`/api/v1/rules` however, returns only the namespace called `rules`.
