### ISSUE TITLE
Prometheus-compatible API provides unexpected, inconsistent payloads when rule expressions contain bugs

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [cortexproject/cortex#2948]
I have the following rule group in one of my namespaces that contains a buggy rule and it results in the whole group not being returned by `/api/v1/rules`:

```yml
- name: AllInstances
  interval: 0s
  rules:
  - record: ""
    alert: DownStatus
    expr: up == 0
    for: 5s
    labels:
      severity: something
    annotations:
      arbitrarykey: Just some test.
      title: Instance {{ $labels.instance }} is down.
  - record: ""
    alert: BuggyRule
    expr: up * on (job) up
    for: 5s
    labels: {}
    annotations: {}
```

So I thought that maybe having a buggy rule in a group would result in it not being returned. But then I copied that rule to a different group and the behavior there is different - the group is still returned but without the buggy rule.

```yml
- name: MyVM
  interval: 0s
  rules:
  - record: ""
    alert: NeverFires
    expr: rate(process_cpu_seconds_total[1m]) > 10000
    for: 1m
    labels: {}
    annotations: {}
  - record: ""
    alert: LowCPUUsage
    expr: rate(process_cpu_seconds_total[1m]) <= 50
    for: 5s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} has had low CPU usage for more than 5 seconds.'
      title: Instance {{ $labels.instance }} - low CPU usage!
  - record: ""
    alert: BuggyRule
    expr: up * on (job) up
    for: 5s
    labels: {}
    annotations: {}
```

**What I would expect**

All rule groups and rules within them to always be returned. And the buggy rule being in an error state just like would be the case with Prometheus:
```json
{
  "state": "pending",
  "name": "BuggyRule",
  "query": "up * on(job) up",
  "duration": 5,
  "labels": {},
  "annotations": {},
  "alerts": [
    {
      "labels": {
        "alertname": "BuggyRule",
        "job": "mypc"
      },
      "annotations": {},
      "state": "pending",
      "activeAt": "2020-07-29T10:33:08.326990857Z",
      "value": "0e+00"
    }
  ],
  "health": "err",
  "lastError": "found duplicate series for the match group {job=\"doesntexist\"} on the right hand-side of the operation: [{__name__=\"up\", instance=\"localhost:56486\", job=\"doesntexist\"}, {__name__=\"up\", instance=\"localhost:56487\", job=\"doesntexist\"}];many-to-many matching not allowed: matching labels must be unique on one side",
  "evaluationTime": 0.000213305,
  "lastEvaluation": "2020-07-29T14:26:23.328386809+02:00",
  "type": "alerting"
}
```
