### ISSUE TITLE
IAM authentication support in ruler and alertmanager S3 client

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3034]
I've been reported that the "chunks storage" S3 client (which is also used by the ruler and alertmanager) doesn't support IAM authentication, while the S3 client we use in the blocks storage does. We need investigate and eventually fix it.

_Longer shot would be re-using the blocks storage S3 client for the ruler and alertmanager as well, which is something discussed in https://github.com/cortexproject/cortex/issues/2262 and attempted in https://github.com/cortexproject/cortex/pull/2489._

**Comment by qinxx108** [comment]
Our configuration for S3 client for block store: Values.s3.endpoint is  s3-us-west-2.amazonaws.com, Values.s3.bucketName will be our bucket name
```
 tsdb:
      dir: /data/tsdb
      backend: s3
      s3:
        endpoint: {{ .Values.s3.endpoint }}
        bucket_name: {{ .Values.s3.bucketName }}


```
The credential provided by the serviceaccount define as 
  ```
serviceAccounts:
    - metadata:
        name: ingester
        namespace: ${CORTEX_NAMESPACE}
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
            Resource:
              - "arn:aws:s3:::${S3_BUCKET_NAME}"
              - "arn:aws:s3:::${S3_BUCKET_NAME}/*"
          - Effect: Allow
            Action:
              - "kms:GenerateDataKey*"
            Resource:
              - "${S3_KMS_KEY}"
```

But for "chunks storage" S3 client (which is also used by the ruler and alertmanager)

We have to use 
`- -alertmanager.storage.s3.url=s3://$(S3_ACCESS_KEY_ID):$(S3_SECRET_KEY_ID)@{{ .Values.aws.region }}/{{ .Values.alertmgr.s3.bucketName }}`

Ideally we should be use the same definition to use serviceaccount to assume iam role for s3 bucket credential
