### ISSUE TITLE
field local not found in type ruler.RuleStoreConfig

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3038]
I tried configuring `ruler` as shown in the [example config](https://github.com/cortexproject/cortex/blob/9c6b2293ef1bc654ccdf16177f803546cf2715da/docs/configuration/single-process-config.yaml#L91-L97):
```yml
ruler:
  storage:
    type: 'local'
    local:
      directory: '/etc/cortex/rules'
  enable_alertmanager_v2: true
  enable_api: true
```
But when I tried to restart the service I got back:
```
error loading config from /etc/cortex/config.yml: Error parsing config file: yaml: unmarshal errors:
  line 64: field local not found in type ruler.RuleStoreConfig
```
I have no idea what I'm doing wrong and I'm running `1.2.0`.
