### ISSUE TITLE
The -target=all flag does not include alertmanager

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3041]
I'm running a 3 host cluster with `1.3.0-rc.1` and I'm trying to run Alertmanager serivce with the following config:
```yml
alertmanager:
  external_url: 'https://alerts.example.org/'
  cluster_bind_address: '10.1.33.0:9094'
  cluster_advertise_address: '10.1.33.0'
  data_dir: '/var/tmp/cortex/alertmnanager'
  retention: 120h
  storage:
    type: local
    local:
      path: '/var/tmp/cortex/alerts'
```
But I don't see the service listening on port `9094` at all:
```
admin@master-03.do-ams3.metrics.hq:~ % sudo netstat -lpnt | grep cortex
tcp        0      0 10.1.33.0:9095          0.0.0.0:*               LISTEN      27780/cortex        
tcp6       0      0 :::9092                 :::*                    LISTEN      27780/cortex 
```
And I don't see the service in the return value from `/services`:
```
 % curl -s http://10.1.33.0:9092/services | grep -A1 '<tr>' | grep td
					<td>memberlist-kv</td>
					<td>store</td>
					<td>server</td>
					<td>ring</td>
					<td>distributor</td>
					<td>ingester</td>
					<td>query-frontend</td>
					<td>querier</td>
					<td>ruler</td>
					<td>table-manager</td>
```
Both configured directories exist and are owned by service user.
I'm not sure what more I'm supposed to do.

**Comment by pstibrany** [comment]
Alert Manager is not part of "all" target, and must be run on its own (by using `-target=alertmanager` or in config file: `target: alertmanager`).

**Comment by jakubgs** [comment]
Ooooooh, that makes sense. I totally missed that. Thanks.

Though question, what's the advantage of running alertmanager via Cortex as opposed to running Alertmanager directly?

**Comment by pstibrany** [comment]
> Though question, what's the advantage of running alertmanager via Cortex as opposed to running Alertmanager directly?

I will leave answering that question to others, as my knowledge of AM is very low :) (Sorry!) (@gotjosh @jtlisi @annanay25?)

**Comment by jakubgs** [comment]
Though to be fair, when I see `-target=all` I kinda assume `all` means "all", not "all except alertmanager".
```
 % /usr/local/bin/cortex -h | grep -A 1 '\-target'
  -target string
    	The Cortex service to run. Use "-modules" command line flag to get a list of available options. (default "all")
```
The help message says nothing about it. And I don't see anything about that here:
https://cortexmetrics.io/docs/configuration/arguments/

**Comment by pstibrany** [comment]
That is a very good point. Can we reopen this issue, and rename it to document "all" target properly?

**Comment by jakubgs** [comment]
Does make me wonder though, what's stopping alertmanager from running alongside other routines in Cortex.

**Comment by pstibrany** [comment]
> Does make me wonder though, what's stopping alertmanager from running alongside other routines in Cortex.

There can be different reasons. One is that multiple Cortex instances in "single-binary" (target=all) mode can work together. There are however some services that require exactly one instance, and if they were started multiple times, they would fail.

Another reason is that some targets are only used in special situations (eg. "compactor", "flusher").

**Comment by jakubgs** [comment]
Not sure if that's true for Alertmanager as I have it running in a cluster on my infra without Cortex. There's a flag called `--cluster.peer` for specifying peers in the alertmanager cluster to connect to. Unless I'm misunderstanding you.

**Comment by pstibrany** [comment]
Cortex AlertManager is different from Prometheus one, although Cortex reuses parts of the original.

**Comment by jakubgs** [comment]
Wait, does that mean that Cortex's alertmanager doesn't run in a cluster? Then how does it dedupe alerts?

**Comment by pstibrany** [comment]
> Wait, does that mean that Cortex's alertmanager doesn't run in a cluster? Then how does it dedupe alerts?

I'm not exactly sure *how* but documentation says that it *does* deduplicate alerts ;-) (https://cortexmetrics.io/docs/architecture/#alertmanager)

**Comment by bboreham** [comment]
Duplicate of #1722 

> Eg. Cortex' AM supports multi-tenancy, so it actually instantiates one "Prometheus" AM per tenant.

One per Cortex alertmanager per tenant, i.e. if you have 3 Cortex alertmanagers and 100 tenants then there are 300 "Prometheus" alertmanagers.

Alert deduplication is done exactly the same as in Prometheus, per tenant.

**Comment by jakubgs** [comment]
I'm not sure what you mean by "tenant". What is a tenant in this context? A prometheus instance writing to Cortex?

**Comment by bboreham** [comment]
Yes we should define "tenant".  #3023 

This looks ok: https://en.wikipedia.org/wiki/Multitenancy "A tenant is a group of users who share a common access with specific privileges to the software instance."  In Cortex, those "users" need to be understood as both human and system accounts.

The way we use it in Cortex a single tenant could have multiple Prometheus.

**Comment by jakubgs** [comment]
Thanks for explaining. So if I'm running 3 Cortex hosts in a cluster, and I also run Cortex alertmanager on each of those hosts, and I have 3 Prometheus instances in separate DCs writing to that Cortex cluster, that would mean each of the alertmanager instances actually runs 3 instances under the hood for each tenant?

**Comment by jakubgs** [comment]
I don't get it. I'm running my server with:
```
/usr/local/bin/cortex -target=alertmanager -config.file=/etc/cortex-alertmanager/config.yml
```
and
```yml
---
target: alertmanager
alertmanager:
  external_url: 'https://alerts.example.org/'
  cluster_bind_address: '10.1.2.3:9094'
  cluster_advertise_address: '10.1.2.3'
  data_dir: '/var/tmp/cortex-alertmanager/data'
  retention: 120h
  storage:
    type: local
    local:
      path: '/var/tmp/cortex-alertmanager/conf'
```
But I'm getting:
```
listen tcp :80: bind: permission denied
```
As if it's trying to start the HTTP server, even though I clearly state I want `alertmanager`.
