### ISSUE TITLE
remote_write: setting OrgId via username/bearer

### ISSUE THREAD

**Issue by fxnn** [cortexproject/cortex#3048]
The [docs|https://cortexmetrics.io/docs/production/auth/] state:

> When configuring the `remote_write` API in Prometheus there is no way to add extra headers. The user and password fields of http Basic auth, or Bearer token, can be used to convey the tenant ID and/or credentials.

I setup Cortex using your provided [helm charts|https://github.com/cortexproject/cortex-helm-chart], but I cannot set OrgId via basic auth or Bearer token. When e.g. configuring Prometheus like this:

```
    remoteWrite:
      - url: http://cortex.cortex.svc.cluster.local/api/prom/push
        bearer_token: my_org_id
```

Or this:

```
    remoteWrite:
      - url: http://cortex.cortex.svc.cluster.local/api/prom/push
        basic_auth:
          username: my_org_id
          password: my_org_id
```

I always receive

```
ts=2020-08-17T06:56:32.850Z caller=dedupe.go:112 component=remote level=error remote_name=8b2ffd url=http://cortex.cortex.svc.cluster.local/api/prom/push msg="non-recoverable error" count=5 err="server returned HTTP status 401 Unauthorized: no org id"
```

Is the documentation outdated here?

Thanks in advance,
Felix
