### ISSUE TITLE
querier/store-gateway panic on startup with memberlist

### ISSUE THREAD

**Issue by carlpett** [cortexproject/cortex#3057]
Building a new setup with v1.3.0-rc.2, blocks storage and memberlist, and I'm seeing panic on startup for querier and store-gateway. I'm guessing I'm misconfiguring something, but it'd be nice if it told me what instead of panic:ing :smile: 

`store-gateway`:
```
level=info ts=2020-08-19T13:33:55.253845687Z caller=main.go:162 msg="Starting Cortex" version="(version=1.3.0-rc.2, branch=HEAD, revision=8d6a5730c)"
level=info ts=2020-08-19T13:33:55.254211262Z caller=server.go:194 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x295f8b2]

goroutine 1 [running]:
github.com/cortexproject/cortex/pkg/ring/kv/memberlist.(*KVInitService).GetMemberlistKV(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/kv_init_service.go:38 +0x22
github.com/cortexproject/cortex/pkg/ring/kv.createClient(0xc00014d0d0, 0xa, 0x3705515, 0xb, 0x370db5f, 0xe, 0x0, 0x0, 0x4a817c800, 0x0, ...)
        /go/src/github.com/cortexproject/cortex/pkg/ring/kv/client.go:145 +0x6a5
github.com/cortexproject/cortex/pkg/ring/kv.NewClient(0xc00014d0d0, 0xa, 0x3705515, 0xb, 0x370db5f, 0xe, 0x0, 0x0, 0x4a817c800, 0x0, ...)
        /go/src/github.com/cortexproject/cortex/pkg/ring/kv/client.go:122 +0x132
github.com/cortexproject/cortex/pkg/storegateway.NewStoreGateway(0x1, 0xc00014d0d0, 0xa, 0x3705515, 0xb, 0x370db5f, 0xe, 0x0, 0x0, 0x4a817c800, ...)
        /go/src/github.com/cortexproject/cortex/pkg/storegateway/gateway.go:86 +0x2dd
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).initStoreGateway(0xc000762a80, 0x0, 0xc0005ee908, 0x0, 0xc0005ee8a0)
        /go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:558 +0x200
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc00000f518, 0x7ffcd3bef846, 0xd, 0xd, 0xc0005ee958, 0x3e8e801)
        /go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:87 +0x26f
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run(0xc000762a80, 0xc000679cc0, 0x4)
        /go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:282 +0xb0
main.main()
        /go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:164 +0xb0a
```

`querier`:
```
level=info ts=2020-08-19T13:43:36.04965265Z caller=main.go:162 msg="Starting Cortex" version="(version=1.3.0-rc.2, branch=HEAD, revision=8d6a5730c)"
level=info ts=2020-08-19T13:43:36.050622855Z caller=server.go:194 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2020-08-19T13:43:36.052718115Z caller=experimental.go:19 msg="experimental feature in use" feature="Gossip memberlist ring"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29749d0]

goroutine 1 [running]:
github.com/cortexproject/cortex/pkg/ring/kv.createClient(0xc000b782f0, 0xa, 0x3705515, 0xb, 0x370db5f, 0xe, 0x0, 0x0, 0x4a817c800, 0x0, ...)
        /go/src/github.com/cortexproject/cortex/pkg/ring/kv/client.go:145 +0x6a0
github.com/cortexproject/cortex/pkg/ring/kv.NewClient(0xc000b782f0, 0xa, 0x3705515, 0xb, 0x370db5f, 0xe, 0x0, 0x0, 0x4a817c800, 0x0, ...)
        /go/src/github.com/cortexproject/cortex/pkg/ring/kv/client.go:122 +0x132
github.com/cortexproject/cortex/pkg/querier.NewBlocksStoreQueryableFromConfig(0x14, 0x1bf08eb000, 0x10100, 0x2faf080, 0x0, 0x0, 0x8bb2c97000, 0xdf8475800, 0x37256c8, 0x16, ...)
        /go/src/github.com/cortexproject/cortex/pkg/querier/blocks_store_queryable.go:178 +0x74d
github.com/cortexproject/cortex/pkg/cortex.initQueryableForEngine(0xc000b78328, 0x6, 0x7fff3d558853, 0x7, 0x0, 0x36ff6b0, 0x9, 0x0, 0x37091c3, 0xd, ...)
        /go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:265 +0x176
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).initStoreQueryables(0xc000880000, 0x3f0f620, 0xc0003960c0, 0xc00077cfc0, 0xc0001776a0)
        /go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:210 +0x100
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc000ada0e8, 0x7fff3d558853, 0x7, 0x7, 0xc000177820, 0x3e8e801)
        /go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:87 +0x26f
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run(0xc000880000, 0xc000b7dac0, 0x4)
        /go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:282 +0xb0
main.main()
        /go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:164 +0xb0a
```

Config file:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

memberlist:
  join_members:
  - cortex-gossip:7947
  abort_if_cluster_join_fails: false

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

    join_after: 10s
    observe_period: 10s

distributor:
  ring:
    kvstore:
      store: memberlist

store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 1

storage:
  engine: blocks

blocks_storage:
  backend: gcs
  tsdb:
    dir: /tmp/storage/tsdb
  bucket_store:
    sync_dir: /tmp/storage/tsdb-sync
```

Anything else I can supply?
