### ISSUE TITLE
Alertmanager config from /api/v1/alerts is different from /alertmanager/api/v2/status

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [cortexproject/cortex#3101]
When POSTing a simple config to `/api/v1/alerts`, such as:
```
alertmanager_config: |
  global: 
    smtp_smarthost: 'localhost:25' 
    smtp_from: 'andreas.opferkuch@grafana.com' 
  route: 
    receiver: dummy
  receivers: 
    - name: dummy
      email_configs: 
      - to: 'andreas.opferkuch@grafana.com' 
```

... it looks exactly like that when doing a GET on `/api/v1/alerts`:
```
"global: \n  smtp_smarthost: 'localhost:25' \n  smtp_from: 'andreas.opferkuch@grafana.com' \nroute: \n  receiver: asdf\nreceivers: \n  - name: asdf\n    email_configs: \n    - to: 'andreas.opferkuch@grafana.com' \n"
```

... but on `/alertmanager/api/v2/status`, it is extended by many more props:
```
"global:\n  resolve_timeout: 5m\n  http_config: {}\n  smtp_from: andreas.opferkuch@grafana.com\n  smtp_hello: localhost\n  smtp_smarthost: localhost:25\n  smtp_require_tls: true\n  pagerduty_url: https://events.pagerduty.com/v2/enqueue\n  opsgenie_api_url: https://api.opsgenie.com/\n  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/\n  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/\nroute:\n  receiver: asdf\nreceivers:\n- name: asdf\n  email_configs:\n  - send_resolved: false\n    to: andreas.opferkuch@grafana.com\n    from: andreas.opferkuch@grafana.com\n    hello: localhost\n    smarthost: localhost:25\n    headers:\n      From: andreas.opferkuch@grafana.com\n      Subject: '{{ template \"email.default.subject\" . }}'\n      To: andreas.opferkuch@grafana.com\n    html: '{{ template \"email.default.html\" . }}'\n    require_tls: true\ntemplates: []\n"
```

This is an issue because it's not transparent to a user who interacts with `/api/v1/alerts` what the actual configuration ends up being.
