### ISSUE TITLE
Alertmanager: Wrong input can wipe config

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [cortexproject/cortex#3142]
These are two examples I've found of POSTing wrong input to `/api/v1/alerts` that results in Alertmanager returning `2XX` and setting the config to an empty string:

- Wrong indentation of content
```
alertmanager_config: |
global: 
  smtp_smarthost: 'localhost:25' 
  smtp_from: 'andreas.opferkuch@grafana.com' 
route: 
  receiver: asdf
receivers: 
  - name: asdf
    email_configs: 
    - to: 'andreas.opferkuch@grafana.com' 
```

- Invalid field name (note the typo in `aalertmanager_config`)
```
aalertmanager_config: |
  global: 
    smtp_smarthost: 'localhost:25' 
    smtp_from: 'andreas.opferkuch@grafana.com' 
  route: 
    receiver: asdf
  receivers: 
    - name: asdf
      email_configs: 
      - to: 'andreas.opferkuch@grafana.com' 
```
