### ISSUE TITLE
Unable to use Cassandra as chunk object, Index and Delete request store altogether

### ISSUE THREAD

**Issue by SumitKu91** [cortexproject/cortex#3280]
I have cortex running with Cassandra chunk storage. While trying to configure the delete series functionality I have set All the 3 sections index, object, and delete request store as Cassandra. The config looks like below:
```
retention_deletes_enabled: true

schema:
  configs:
  - from: 2020-09-26
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 24h
    chunks:
      prefix: chunk_
      period: 24h

storage:
  cassandra:
    addresses: <host_ip>
    keyspace: cortex

  delete_store:
    store: cassandra

purger:
  enable: true
  object_store_type: cassandra
  delete_request_cancel_period: 2m

```
But I get an error saying choose another storage type.
`level=error ts=2020-10-05T07:54:33.5847602Z caller=log.go:149 msg="error running cortex" err="Unrecognized storage client cassandra, choose one of: aws, s3, gcs, azure, filesystem\nerror initialising module: purger\ngithub.com/cortexproject/cortex/pkg/util/modules.`

Observations:
I am able to run the delete series functionality with Cassandra as index object chunk store and Boltdb filesystem as delete request store.

Could you please help me if there is any issue with the config? Also if there is a tested config for this scenario please do share.
Thanks.
