### ISSUE TITLE
Ingester target not showing the ingester ring on the http server

### ISSUE THREAD

**Issue by roidelapluie** [cortexproject/cortex#3284]
**Describe the bug**

When I set the `target=ingester`, I don't see the ingester ring in the web UI. I think that it should be there.

**To Reproduce**
1. Start Cortex 1.4.0
2. Start cortex

```
/usr/local/bin/cortex-linux-amd64 -config.file=/etc/cortex/cortex-distributor.yml -target ingester
```

![ing](https://user-images.githubusercontent.com/291750/95198846-2cc15780-07dc-11eb-9346-70f35cdabb80.png)

**Expected behavior**

We can see the ingester ring from the ingesters.

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**

```
blocks_storage:
  backend: s3
  bucket_store:
    sync_dir: /data/cortex/tsdb-sync
  s3:
    access_key_id: XX
    bucket_name: prd-prometheus
    endpoint: XX
    secret_access_key: XX
  tsdb:
    dir: /data/cortex/tsdb
ingester:
  lifecycler:
    interface_names:
    - ens160
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  walconfig:
    wal_enabled: true
memberlist:
  bind_port: 8401
  join_members:
  - 172.20.1.133:8400
server:
  grpc_listen_address: 172.20.1.133
  grpc_listen_port: 9011
  http_listen_address: 127.0.0.1
  http_listen_port: 9011
storage:
  engine: blocks
```
