### ISSUE TITLE
[ruler] unbounded growth in group evaluation latency after last rule is deleted

### ISSUE THREAD

**Issue by nicolai86** [cortexproject/cortex#3359]
**Describe the bug**
When the very last rule is deleted the ruler enters a state where the group evaluation latency is growing unbounded. Once this state is entered new rules are not picked up, and the only way to get the rulers to evaluate any rules again is to restart the rulers.

**To Reproduce**
Steps to reproduce the behaviour:

1. Start Cortex, with a rulers and an alertmanager. I used 3 rulers with memberlist and 3 alertmanagers in HA configuration, but it really doesn't matter.

2. Create tenant alert configuration, ie this one:
```
> POST /api/v1/alerts HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/yaml
X-Scope-Orgid: tenant-0

---
alertmanager_config: |
  global:
    resolve_timeout: 5s
  route:
    receiver: webhook
    group_interval: 1m
  receivers:
    - name: webhook
      webhook_configs:
      - send_resolved: false
        url: http://alertmanager-sns-forwarder-svc.cortex:9087/alert/us-west-2/611128412359/test

HTTP/1.1 201 Created
Content-Length: 0
Date: Sat, 17 Oct 2020 02:10:30 GMT
```
Note that I've port-forward the alertmanager to localhost:8080 in this example

3. create ruler configuration for tenant:
```
POST /api/prom/rules/alarms-0-000 HTTP/1.1
Host: 127.0.0.1:8081
Content-Type: application/yaml
X-Scope-Orgid: tenant-0

name: "alarms-1-001"
interval: 60s
rules:
- alert: alarm-1
  annotations:
    message: test 1
  expr: vector(1)
  labels:
    severity: none

< HTTP/1.1 202 Accepted
Content-Length: 58
Content-Type: application/json
Date: Sat, 17 Oct 2020 02:10:30 GMT

{"status":"success","data":null,"errorType":"","error":""}
```
Note that I've port-forwarded the ruler to localhost:8081 in this example
4. wait for rule to be evaluated at least once.
5. delete rule config
```
> DELETE /api/prom/rules/alarms-0-000 HTTP/1.1
Host: 127.0.0.1:8081
Content-Type: application/yaml
X-Scope-Orgid: tenant-0

< HTTP/1.1 202 Accepted
Content-Length: 58
Content-Type: application/json
Date: Sat, 17 Oct 2020 02:14:59 GMT
{"status":"success","data":null,"errorType":"","error":""}
```
6. delete alertmanager config

```
> DELETE /api/v1/alerts HTTP/1.1
Host: 127.0.0.1:8080
X-Scope-Orgid: tenant-0

< HTTP/1.1 200 OK
Date: Sat, 17 Oct 2020 02:15:00 GMT
Content-Length: 0
```
7. wait until files are deleted from ruler/ alertmanager store
8. follow step 2. and 3. to create alertmanager and rule configuration again

**Expected behavior**
The ruler should evaluate the rules again. However, the rules are not picked up, and the ruler doesn't perform any action.
[Example 1](https://snapshot.raintank.io/dashboard/snapshot/8381v1WkWs0i6w1obRNmxW9nFu2rrI6m) [Example 2, after 26h](https://snapshot.raintank.io/dashboard/snapshot/qRvSrKPtqv2tDvH3f5TCFFoU8un4U1xu)

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

alertmanager configuration
```
alertmanager:
  data_dir: /data/alertmanager
  external_url: /alertmanager
  cluster_bind_address: "0.0.0.0:9094"
  storage:
    type: s3
    s3:
      s3: s3://us-west-2/<some-bucket>
  enable_api: true
```

ruler configuration:
```
ruler:
  storage:
    type: s3
    s3:
      s3: s3://us-west-2/<another-bucket>
  ring:
    kvstore:
      store: memberlist
      prefix: ruler/
  alertmanager_url: http://alertmanager.cortex.svc.cluster.local/alertmanager/
  enable_sharding: true
  enable_api: true
```

memberlist
```
memberlist:
  bind_port: 7946
  join_members:
    - ingester-memberlist.cortex.svc.cluster.local:7946
    - store-gateway-memberlist.cortex.svc.cluster.local:7946
    - distributor-memberlist.cortex.svc.cluster.local:7946
    - compactor-memberlist.cortex.svc.cluster.local:7946
  abort_if_cluster_join_fails: false
```
