### ISSUE TITLE
cortex version 1.4.0  - Cassandra.table-options does not seem to work

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#3376]
**Describe the bug**
Trying to set default_time_to_live for tables in cortex_new namespace.  Use flag cassandra.table-options in table-manager deployment definition.
```
containers:
      - name: table-manager
        image: quay.io/cortexproject/cortex:v1.4.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=table-manager
        - -server.http-listen-port=80
        - -cassandra.addresses=cassandra.monitoring.svc.cluster.local
        - -cassandra.keyspace=cortex_new
        - -cassandra.timeout=1000ms
        - -cassandra.replication-factor=3
        - -cassandra.table-options="default_time_to_live = 7776000"
```
If I don't use -cassandra.table-options then tables are created fine

**Environment:**
 - Infrastructure: GKE
 - Deployment tool: K8s deployment definition.yaml file

**Storage Engine**
Cassandra for both chunks and index
- [ X] Chunks

**Additional Context**

```
│ level=error ts=2020-10-21T23:24:00.035833075Z caller=table_manager.go:243 msg="error syncing tables" err="130 errors: line 0:-1 no viable alternative at input '<EOF>'; line 0:-1 no viable alternative at in │
│ level=info ts=2020-10-21T23:25:59.915806453Z caller=table_manager.go:333 msg="synching tables" expected_tables=130                                                                                            │
```
