### ISSUE TITLE
Alertmanager failing to connect to cluster

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3389]
## Descrition
I'm trying to get Alertmanager service to work in a cluster, but when I try to run 3 services in 3 different hosts they fail to connect with:
```
Failed to join 10.1.1.2: received invalid msgType (72), expected pushPullMsg (6) from=10.1.1.2:9101
```

# Config
I'm running `1.4.0` with the following config:
```yaml
---
target: 'alertmanager'

server:
  http_listen_port: 9101
  http_listen_address: '0.0.0.0'
  grpc_listen_port: 9102
  grpc_listen_address: '10.1.1.1'
  log_level: 'debug'

alertmanager:
  data_dir: '/var/lib/cortex-alertmanager'
  retention: 120h
  enable_api: true
  poll_interval: 60s
  cluster_bind_address: "10.1.1.1:9103"
  cluster_advertise_address: "10.1.1.1:9103"
  external_url: "https://alerts.example.org/"

  peers:
    - "10.1.1.2:9101"
    - "10.1.1.3:9101"

  storage:
    type: "local"
    local:
      path: "/var/tmp/cortex-alertmanager"
```
But when it starts to try to connect to the `peers`:
```
[DEBUG] memberlist: Initiating push/pull sync with:  10.1.32.207:9101
```
It just fails with either:
```
[DEBUG] memberlist: Failed to join 10.1.1.2: read tcp 10.1.1.1:36470->10.1.1.2:9101: i/o timeout
```
or
```
[DEBUG] memberlist: Failed to join 10.1.1.2: received invalid msgType (72), expected pushPullMsg (6) from=10.1.1.2:9101
```
Which error happens appears to be random.
Sometimes I restart the service and get the timeout, sometimes I get the invalid message.

## Expected Behavior
An Alertmanager cluster is created.

## Setup
I'm just running the binary release of `1.4.0` from GitHub via a System service.
