### ISSUE TITLE
Cortex ruler ring status pages and ingester ring are the same

### ISSUE THREAD

**Issue by roidelapluie** [cortexproject/cortex#3408]
**Describe the bug**

My ruler and my ingester are launched in 2 different processes, however the ruler and ingester ring web pages are showing the same address.

The ruler ring status at /ring is showing the ingester instances instead of the rulers instances. /ingester/ring is showing the ingesters as well.

**To Reproduce**
1. Start Cortex 1.4.0 with ruler and ingester
2. look the ruler ring status

**Expected behavior**

ruler ring status shows rulers

**Environment:**
 - Infrastructure: virtual machine
 - Deployment tool: ansible

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

ruler relevant config:

```
memberlist:
  bind_port: 8407
  join_members:
  - x.inuits.eu:8401
  - y.inuits.eu:8401
server:
  grpc_listen_address: 172.1.1.13
  grpc_listen_port: 9916
  http_listen_address: 127.0.0.1
  http_listen_port: 9016
```

ingester relevant config:

```
memberlist:
  bind_port: 8401
  join_members:
  - x.inuits.eu:8401
  - y.inuits.eu:8401
server:
  grpc_listen_address: 172.1.1.13
  grpc_listen_port: 9911
  http_listen_address: 127.0.0.1
  http_listen_port: 9011
```

the ring status is showing

172.1.1.13:**9911**
