### ISSUE TITLE
api: "set rule group" endpoint accepts rule with `expr: null`, treating it as a string

### ISSUE THREAD

**Issue by domasx2** [cortexproject/cortex#3413]
**Describe the bug**
Noticed some odd behaviour: posting a rule group with rule that contains a null expr `expr: null` is accepted. Then when you query this group, rule is returned as if having `expr: "null"`. This can't be right :) I think it shouldn't accept null exprs?

**To Reproduce**
1. Using cortex docker image `cortexproject/cortex:master-a6292c1`
2. Post a rule group that contains a rule with `expr: null` for example:

```
POST http://cortex/api/v1/rules/default
Content-Type: text/yaml

name: zz
rules:
  - alert: za
    expr: null

HTTP/1.1 202 Accepted
```

3. Then query rules config and see that `expr` is now a sring with value `"null"`:
```
GET http://cortex/api/v1/rules

HTTP/1.1 200 OK
Content-Type: application/yaml
Date: Wed, 28 Oct 2020 15:14:05 GMT
Content-Length: 80
Connection: close

default:
    - name: zz
      rules:
        - alert: za
          expr: "null"

```

**Expected behavior**
Should probably reject `expr: null`, same as it does empty string. Afaik `null` is a special value in yaml and should not be interpreted as a string.

**Environment:**
 - Infrastructure: my sweet tuxedo xa15 workstation with Ubuntu 20.04
 - Deployment tool: docker compose

**Storage Engine**
- [ ] Blocks
- [ ] Chunks
- [x] I have no idea

**Additional Context**
