### ISSUE TITLE
Inconsistent S3 parameters across configs

### ISSUE THREAD

**Issue by andersosthus** [cortexproject/cortex#3424]
**Describe the bug**
Cortex 1.4.0

There are some mismatch in how S3 is configured.

In `blocks_storage` I can do this, and it works fine (using EC2 instance profile):
```
blocks_storage:
  backend: s3
  s3:
    endpoint: s3.dualstack.eu-west-1.amazonaws.com
    bucket_name: MYBUCKET
```

In `ruler`, if I do this, the ruler fails to look up rules, giving a 403 (using EC2 instance profile):
```
ruler:
  storage:
    type: s3
    s3:
      endpoint: s3.dualstack.eu-west-1.amazonaws.com
      bucketnames: MYBUCKET
```
The logs say:
```
level=error ts=2020-10-29T20:42:13.550239824Z caller=ruler.go:366 msg="unable to poll for rules" err="AccessDenied: Access Denied\n\tstatus code: 403, request id: XXX, host id: XXX"
```

But if I do this, the ruler works fine (still using same EC2 instance profile):
```
ruler:
  storage:
    type: s3
    s3:
      s3: https://eu-west-1/MYBUCKET
```

Also, the `storage.s3.bucketnames` should probably be renamed `s3.bucket_names` to align with the `blocks_storage.s3.bucket_name`

**To Reproduce**
See above

**Expected behavior**
Expected to be able to configure S3 in a consistent manner across the different config sections.

**Environment:**
 - Infrastructure: Kubernetes on EC2 with IAM Instance Profiles

**Storage Engine**
- [X] Blocks
- [ ] Chunks
