### ISSUE TITLE
How is the Query Frontend supposed to be configured?

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3430]
## Description

I'm running a 3 node Cortex `1.4.0` cluster with `-target=all` and I'm seeing pretty bad query performance in Grafana.
I figured my issue is not using the [Query Frontend](https://cortexmetrics.io/docs/architecture/#query-frontend) to parallelize the queries. But the documentation is quite confusing.

You can find a config of one of my nodes [here](https://gist.github.com/jakubgs/7e79e718541691ddc69aee844ca3393d).

## Details

Based on [the docs](https://cortexmetrics.io/docs/architecture/#query-frontend):

>The query frontend is an __optional service__ providing the querier’s API endpoints and can be used to accelerate the read path.

But if we check `-modules` we see that `frontend` is not optional, but rather included in the `all` target:
```
 > cortex -modules | grep frontend
query-frontend *
```
Which means I'm already running a `query-frontend` service on each node:
```
 > curl -s 'http://localhost:9092/services' | grep -A1 query-frontend
					<td>query-frontend</td>
					<td>Running</td>
```
But my query performance is very bad, so I thought that maybe I'm using the wrong endpoint.
But when I checked the codebase I could not identify any special path prefix for the `query-frontend`:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/api/api.go#L414-L420
It seems to me like `query-frontend` is already available under the `PrometheusHTTPPrefix` path which is `/prometheus`.

I found this comment: https://github.com/cortexproject/cortex/issues/2921#issuecomment-662998729

>If you're running the query-frontend in front of a Cortex cluster, the suggested way is not using the downstream URL but configuring the querier worker to connect to the query-frontend (and here we do support SRV records).

Which suggests that my configuration should have the `querier` talk to the `query-frontend`. But how is that supposed to work if I have multiple `query-frontend`s, one for each Cortex instance? Should each Cortex instance `querier` have it's own `query-frontend` configured as `frontend_worker.frontend_address`?

Another thing is, why is the flag called `-querier.frontend-address` but the config option is `frontend_worker.frontend_address`?

Or should I run a separate `-target=query-frontend` instance of Cortex on a separate host(probably same as my Grafana) and have the `querier` services connect to that single `query-frontend`?

**Comment by jakubgs** [comment]
I have a process running with `-target=query-frontend` with the following config:
```yaml
---
auth_enabled: false

# ---------------------- MemberList -----------------------
memberlist:
  node_name: 'cortex-query-frontend'

# ---------------------- Server ---------------------------
server:
  http_listen_address: '0.0.0.0'
  http_listen_port: 9092
  grpc_listen_address: '10.1.31.152'
  grpc_listen_port: 9095
  log_level: 'debug'

# ---------------------- Query Frontend -------------------
frontend:
  max_outstanding_per_tenant: 200
```
But when I try to access to `/prometheus` API it it times out:
```
 > curl -sv http://10.1.31.152:9092/prometheus/api/v1/labels --max-time 10
*   Trying 10.1.31.152:9092...
* TCP_NODELAY set
* Connected to 10.1.31.152 (10.1.31.152) port 9092 (#0)
> GET /prometheus/api/v1/labels HTTP/1.1
> Host: 10.1.31.152:9092
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Operation timed out after 10001 milliseconds with 0 bytes received
* Closing connection 0
```
And the logs show it fails with `499`:
```
caller=logging.go:66 traceID=2790c310606cc5fc msg="GET /prometheus/api/v1/labels (499) 10.001303726s"
```
My 3 Cortex cluster nods have this in their config:
```yaml
frontend_worker:
  frontend_address: '10.1.31.152:9095'
```
Based on https://github.com/cortexproject/cortex/issues/2921#issuecomment-662998729 comment my understanding is that `query_frontend` config does not need to have `downstream_url` set. Correct?

>If you're running the query-frontend in front of a Cortex cluster, the suggested way is not using the downstream URL but configuring the querier worker to connect to the query-frontend

But it doesn't seem to be connecting.
