### ISSUE TITLE
HA tracker shows incorrect userid<>cluster associations after some time

### ISSUE THREAD

**Issue by zdykstra** [cortexproject/cortex#3463]
**Describe the bug**
I have 6 instances of prometheus running - three clusters of two nodes each running on top of Mesos/Marathon. I'm templating in a `cluster` external label based on the MESOS_APP_ID environment variable, and a `__replica__` external label based on the MESOS_CONTAINER_NAME value. MESOS_CONTAINER_NAME is unique per container, and is not recycled to the best of my knowledge.

After some time, the userid / cluster mappings are incorrect, with one User ID eventually having entries for multiple different clusters. I've confirmed that my prometheus instances are not templating out prometheus.yaml incorrectly, resulting in mis-matched User ID / Cluster values. I can gracefully restart all of the distributor containers and for a time the table is correct; one User ID mapped to one cluster.

The 'Time Until Update' and 'Time Until Failover' columns end up running to ~ negative 2 minutes 10 seconds before they reset to positive values and start counting down again.

**To Reproduce**
I don't have an explicit case that can reproduce this issue on demand.  My Cortex stack is running `version=1.4.0, branch=HEAD, revision=23554ce02`

The Prometheus instances pushing to Cortex were restarted along with the distributor processes 9 days ago, and have been running since then. I realize there's not a lot to go on here, so I'll be happy to provide any additional clues I can.

**Expected behavior**

While no handoff occurs, there will be one cluster associated with one user ID in the /distributor/ha_tracker status page.

**Environment:**
 - Infrastructure: Mesos/Marathon deploying Cortex applications in locally built containers
 - Deployment tool: Marathon

**Storage Engine**
- [ ] Blocks
- [x] Chunks

**Additional Context**

![image](https://user-images.githubusercontent.com/13874853/98179857-682b7080-1ec5-11eb-941c-a45110d309cd.png)

Configuration file used by each Cortex process (Querier, Ingester, Distributor, etc): [config.yaml.txt](https://github.com/cortexproject/cortex/files/5491030/config.yaml.txt)

**Comment by zdykstra** [comment]
I've updated my local cluster to v1.5.0 and the problem is still unfortunately present in this version as well.

**Comment by pracucci** [comment]
Thanks @zdykstra for your report and sorry for the late reply.

Is the `user` and `cluster` association correct in the exported metric `cortex_ha_tracker_elected_replica_changes_total` or `cortex_ha_tracker_elected_replica_timestamp_seconds`?

**Comment by zdykstra** [comment]
It looks like the issue is reflected there as well:

```
# TYPE cortex_ha_tracker_elected_replica_changes_total counter
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c3605/primary",user="c3605"} 576
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c3605/primary",user="c3893"} 230
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c3821/primary",user="c3821"} 3
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c3821/primary",user="c3893"} 187
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c3893/primary",user="c3893"} 1
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c5181/primary",user="c3893"} 209
cortex_ha_tracker_elected_replica_changes_total{cluster="/prometheus/c5181/primary",user="c5181"} 1
```

```
# TYPE cortex_ha_tracker_elected_replica_timestamp_seconds gauge
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c3605/primary",user="c3605"} 1.605625257e+09
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c3605/primary",user="c3893"} 1.605624999e+09
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c3821/primary",user="c3821"} 1.605625255e+09
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c3821/primary",user="c3893"} 1.605625164e+09
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c3893/primary",user="c3893"} 1.605625261e+09
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c5181/primary",user="c3893"} 1.605625104e+09
cortex_ha_tracker_elected_replica_timestamp_seconds{cluster="/prometheus/c5181/primary",user="c5181"} 1.605625265e+09
```

Between any given reload of the distributors, only one user seems to be associated with multiple clusters. In this case, c3893 seems to be friends with everybody.

There have been a few prometheus daemon reloads inside my containers since I originally opened this issue, but none of the containers holding the prometheus pollers have been restarted in ~20 days.

**Comment by pracucci** [comment]
Could you show me the actual remote write config of two different Prometheus servers which are expected to remote write to Cortex as different tenants, and could you also show me the actual remote write config of two Prometheus replicas of the same HA cluster, please?

**Comment by zdykstra** [comment]
User c3893 HA 1
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: /prometheus/c3893/primary
    __replica__: mesos-bcd23035-95c2-48b9-ad23-4fa222b06fdc
remote_write:
  - url: http://1.2.3.4:9009/api/v1/push
    basic_auth:
      username: c3893
      password: 155513993cc24ba78dd2164f1a44b41d
scrape_configs:
...
```
User c3893 HA 2
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: /prometheus/c3893/primary
    __replica__: mesos-3dabe77e-43d1-4fe2-8edb-1fd6cb9c0015
remote_write:
  - url: http://1.2.3.4:9009/api/v1/push
    basic_auth:
      username: c3893
      password: 155513993cc24ba78dd2164f1a44b41d
scrape_configs:
...
```

User c5181:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: /prometheus/c5181/primary
    __replica__: mesos-531834cc-206f-4c36-8776-59868e1464a6
remote_write:
  - url: http://1.2.3.4:9009/api/v1/push
    basic_auth:
      username: c5181
      password: 0882cbe4612c409b8349cdceb5cf1a53
scrape_configs:
...
```

User c3821:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: /prometheus/c3821/primary
    __replica__: mesos-024756a3-c7bb-468a-be0e-6fb4e7a409a2
remote_write:
  - url: http://1.2.3.4:9009/api/v1/push
    basic_auth:
      username: c3821
      password: 3c43a83634721a18937cf0bb57838cca
scrape_configs:
...
```

**Comment by zdykstra** [comment]
This is tentatively resolved by the following limits block:

```
limits:
  max_queriers_per_tenant: 4
  accept_ha_samples: true
  ha_cluster_label: "__cluster__"
  ha_replica_label: "__replica__"
  drop_labels:
    - "__cluster__"
    - "__replica__"
```

Each of my HA prometheus instances now attach `__cluster__` and `__replica__` as external labels, which are then subsequently dropped by the distributors. Based on per-user ingest rate graphs, HA is still being respected. I'll check `/distributor/ha_tracker` tomorrow to confirm that the mappings are still accurate, but they've been correct for the last two hours of runtime.
