### ISSUE TITLE
How to specify the bucket for GCS in block storage.

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#3489]
**Describe the bug**
Trying to specify the GCS bucket to be use for block storage but coult not get anything to recognize it.  The documentation did not have any example for it

I have tried the followings :

`-blocks-storage.gcs.bucket-name="https://storage.googleapis.com/storage/v1/b/bucketName"`

then 
` -blocks-storage.gcs.bucket-name="gs://bucketName"`

then
`-blocks-storage.gcs.bucket-name="https://console.cloud.google.com/storage/browser/bucketName"`  

Nothing seemed to work for compactor
got the following error message for the K8s pod running compactor

`caller=compactor.go:311 component=compactor msg="failed to discover users from bucket" err="storage: bucket doesn't exist"`

I know the bucket exist and created.

Cortex 1.4.0

Running on GKE

Trying to use Block storage

**Comment by pstibrany** [comment]
`-blocks-storage.gcs.bucket-name=bucket-name`

**Comment by pstibrany** [comment]
Sorry for the confusion. This is just a name of the bucket, GCS client already knows how to access it. You can check the example config file here: https://cortexmetrics.io/docs/configuration/single-process-config-blocks.yaml

**Comment by mizunos** [comment]
Here is what my compactor deployment file look like 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compactor
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      name: compactor
  template:
    metadata:
      labels:
        name: compactor
    spec:
      nodeSelector:
        dedicated: cortex
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "cortex"
          effect: "NoSchedule"
      containers:
      - name: compactor
        image: quay.io/cortexproject/cortex:v1.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secret/storage.json
        args:
        - -target=compactor
        - -store.engine=blocks
        - -compactor.ring.store=consul
        - -compactor.ring.consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -compactor.deletion-delay=6h
        - -compactor.sharding-enabled=false
        - -compactor.compaction-concurrency=3
        - -compactor.block-ranges=2h0m0s
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name="edge-monitor-block-storage"      
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: storage-key
          items:
          - key: storage.json
            path: storage.json
```

I have change the bucket to just the bucket name but still get the same problem for the compactor - Her is the error log

```
level=info ts=2020-11-12T17:46:22.309214049Z caller=main.go:178 msg="Starting Cortex" version="(version=1.4.0, branch=HEAD, revision=23554ce02)"                                                                                                  │
│ level=info ts=2020-11-12T17:46:22.30981851Z caller=server.go:225 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"                                                                                                                  │
│ level=info ts=2020-11-12T17:46:22.310584598Z caller=module_service.go:58 msg=initialising module=memberlist-kv                                                                                                                                    │
│ level=info ts=2020-11-12T17:46:22.310648336Z caller=module_service.go:58 msg=initialising module=server                                                                                                                                           │
│ level=info ts=2020-11-12T17:46:22.310868741Z caller=module_service.go:58 msg=initialising module=compactor                                                                                                                                        │
│ level=info ts=2020-11-12T17:46:22.311862543Z caller=blocks_cleaner.go:101 component=cleaner msg="started hard deletion of blocks marked for deletion"                                                                                             │
│ level=error ts=2020-11-12T17:46:22.485841563Z caller=blocks_cleaner.go:112 component=cleaner msg="failed to hard delete blocks marked for deletion" err="failed to discover users from bucket: storage: bucket doesn't exist"                     │
│ level=info ts=2020-11-12T17:46:22.486105553Z caller=compactor.go:308 component=compactor msg="discovering users from bucket"                                                                                                                      │
│ level=info ts=2020-11-12T17:46:22.486526042Z caller=cortex.go:341 msg="Cortex started"                                                                                                                                                            │
│ level=error ts=2020-11-12T17:46:22.654506387Z caller=compactor.go:311 component=compactor msg="failed to discover users from bucket" err="storage: bucket doesn't exist"                                                                          │
│ level=info ts=2020-11-12T17:46:42.424351369Z caller=compactor.go:308 component=compactor msg="discovering users from bucket"                                                                                                                      │
│ level=error ts=2020-11-12T17:46:42.557494511Z caller=compactor.go:311 component=compactor msg="failed to discover users from bucket" err="storage: bucket doesn't exist"
```

What am I missing.  Thanks
