### ISSUE TITLE
CORTEX ON K8s: all data lost in Grafana if I restart the pod running Cortex.

### ISSUE THREAD

**Issue by tomjohnburton** [cortexproject/cortex#3490]
**Describe the bug**
I am running Cortex as a single instance. I am using chunk storage with dynamoDB. I have set up Grafana to point to the Cortex service (http://cortex.infra:9009/api/prom) as per instructions. When I try and test what happens if the cortex pod were to restart, I see that all the data in Grafana has disappeared. 

**Expected behavior**
Grafana should load all saved data from dynamoDB

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Storage Engine**
- [ ] Blocks
- [x ] Chunks

**Additional Context**

`prometheus.yml`
```
    global:
      external_labels:
        cluster: dev
        __replica__: a
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    remote_read:
    - url: http://cortex.infra:9009/prometheus/api/v1/read
    remote_write:
    - url: http://cortex.infra:9009/api/prom/push
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
```

`cortex.yaml`
```
    auth_enabled: false
    
    server:
      http_listen_port: 9009
    
      # Configure the server to allow messages up to 100MB.
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    
    distributor:
      shard_by_all_labels: true
      ha_tracker:
        enable_ha_tracker: false
        kvstore:
          store: inmemory
      pool:
        health_check_ingesters: true

    limits:
      accept_ha_samples: true
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
      
      index_tables_provisioning:
        enable_inactive_throughput_on_demand_mode: true  
        provisioned_write_throughput: 100
        provisioned_read_throughput: 10 
        write_scale:
          enabled: true
          min_capacity: 50
          max_capacity: 300
        read_scale:
          enabled: true
          min_capacity: 10
          max_capacity: 200  
    
      chunk_tables_provisioning:
        enable_inactive_throughput_on_demand_mode: true  
        provisioned_write_throughput: 100
        provisioned_read_throughput: 10
        write_scale:
          enabled: true
          min_capacity: 50
          max_capacity: 300
        read_scale:
          enabled: true
          min_capacity: 10
          max_capacity: 200
      
    
    ingester_client:
      grpc_client_config:
        # Configure the client to allow messages up to 100MB.
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: gzip
    
    ingester:
      # We want our ingesters to flush chunks at the same time to optimise
      # deduplication opportunities.
      spread_flushes: true
      chunk_age_jitter: 0
      
      walconfig:
        wal_enabled: true
        recover_from_wal: true
        wal_dir: /tmp/cortex/wal
    
      lifecycler:
        join_after: 0
        min_ready_duration: 0s
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /tmp/cortex/wal/tokens
    
        # Use an in memory ring store, so we don't need to launch a Consul.
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    
    purger:
      object_store_type: dynamodb

    storage:
      aws:
        dynamodb:
          dynamodb_url: dynamodb://eu-central-1
          api_limit: 4
          metrics:
            url: http://prometheus-server-a.monitoring.svc.cluster.local
            target_queue_length: 10000
            queue_length_query: "sum(avg_over_time(cortex_ingester_flush_queue_length{job=\"cortex\"}[2m]))"

            # query to fetch throttle rates per table
            # CLI flag: -metrics.write-throttle-query
            # write_throttle_query: "sum(rate(cortex_dynamo_throttled_total{operation='DynamoDB.BatchWriteItem'}[1m])) by (table) > 0"
      
            # query to fetch write capacity usage per table
            # CLI flag: -metrics.usage-query
            # write_usage_query: "sum(rate(cortex_dynamo_consumed_capacity_total{operation='DynamoDB.BatchWriteItem'}[15m])) by (table) > 0"
      
            # query to fetch read capacity usage per table
            # CLI flag: -metrics.read-usage-query
            # read_usage_query: "sum(rate(cortex_dynamo_consumed_capacity_total{operation='DynamoDB.QueryPages'}[1h])) by (table) > 0"
      
            # query to fetch read errors per table
            # CLI flag: -metrics.read-error-query
            # read_error_query: "sum(increase(cortex_dynamo_failures_total{operation='DynamoDB.QueryPages',error='ProvisionedThroughputExceededException'}[1m])) by (table) > 0"

```

`schema.yaml`
```
    configs:
      - from: "2020-11-11"
        schema: v9
        chunks:
          period: 1w
          prefix: dev_chunks_
          tags:
            provisioner: cortex
            cluster: dev
            type: chunks
        index:
          period: 1w
          prefix: dev_index_
          tags:
            provisioner: cortex
            cluster: dev
            type: index
        object_store: aws-dynamo
        store: aws-dynamo
```

Logs on start

```
level=info ts=2020-11-12T12:40:03.556536165Z caller=main.go:187 msg="Starting Cortex" version="(version=1.5.0, branch=HEAD, rev
ision=86d95e7)"
level=info ts=2020-11-12T12:40:03.556877324Z caller=server.go:225 http=[::]:9009 grpc=[::]:9095 msg="server listening on addres
ses"
level=info ts=2020-11-12T12:40:03.557076935Z caller=modules.go:583 msg="RulerStorage is not configured in single binary mode an
d will not be started."
level=info ts=2020-11-12T12:40:03.56488934Z caller=modules.go:593 msg="RulerStorage is nil.  Not starting the ruler."
level=warn ts=2020-11-12T12:40:03.566357992Z caller=modules.go:285 msg="Worker address is empty in single binary mode.  Attempt
ing automatic worker configuration.  If queries are unresponsive consider configuring the worker explicitly." address=127.0.0.1
:9095
level=info ts=2020-11-12T12:40:03.56653671Z caller=module_service.go:58 msg=initialising module=querier
level=info ts=2020-11-12T12:40:03.566774091Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2020-11-12T12:40:03.566822565Z caller=module_service.go:58 msg=initialising module=query-frontend-tripperware
level=info ts=2020-11-12T12:40:03.566862248Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2020-11-12T12:40:03.566874683Z caller=module_service.go:58 msg=initialising module=query-frontend
level=info ts=2020-11-12T12:40:03.566916203Z caller=module_service.go:58 msg=initialising module=ring
level=info ts=2020-11-12T12:40:03.566917958Z caller=module_service.go:58 msg=initialising module=store
level=info ts=2020-11-12T12:40:03.566951131Z caller=module_service.go:58 msg=initialising module=table-manager
level=info ts=2020-11-12T12:40:03.567062557Z caller=client.go:242 msg="value is nil" key=collectors/ring index=1
level=info ts=2020-11-12T12:40:03.567093629Z caller=table_manager.go:324 msg="synching tables" expected_tables=4
level=info ts=2020-11-12T12:40:03.567127859Z caller=module_service.go:58 msg=initialising module=distributor-service
level=info ts=2020-11-12T12:40:03.567251971Z caller=module_service.go:58 msg=initialising module=ingester-service
level=info ts=2020-11-12T12:40:03.567280509Z caller=ingester.go:238 msg="recovering from WAL"
level=info ts=2020-11-12T12:40:03.567300579Z caller=wal.go:523 msg="recovering from checkpoint"
level=info ts=2020-11-12T12:40:03.567364512Z caller=wal.go:566 msg="no checkpoint found"
level=info ts=2020-11-12T12:40:03.567385474Z caller=wal.go:530 msg="recovered from checkpoint" time=67.641µs
level=info ts=2020-11-12T12:40:03.567413932Z caller=wal.go:533 msg="no segments found, skipping recover from segments"
level=info ts=2020-11-12T12:40:03.567431294Z caller=ingester.go:245 msg="recovery from WAL completed" time=131.546µs
level=error ts=2020-11-12T12:40:03.567866319Z caller=lifecycler.go:515 msg="error in getting tokens from file" err="open /tmp/c
ortex/wal/tokens: no such file or directory"
level=info ts=2020-11-12T12:40:03.567968611Z caller=lifecycler.go:547 msg="instance not found in ring, adding with no tokens" r
ing=ingester
level=info ts=2020-11-12T12:40:03.568125384Z caller=lifecycler.go:394 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2020-11-12T12:40:03.568254121Z caller=cortex.go:355 msg="Cortex started"
level=warn ts=2020-11-12T12:40:05.402030541Z caller=metrics_autoscaling.go:365 query="sum(avg_over_time(cortex_ingester_flush_q
ueue_length{job=\"cortex\"}[2m]))" start=2020-11-12T12:38:04.356231577Z end=2020-11-12T12:40:04.35623328Z step=1m0s warnings="u
nsupported value type"
level=warn ts=2020-11-12T12:40:06.431681536Z caller=metrics_autoscaling.go:365 query="sum(rate(cortex_dynamo_throttled_total{op
eration=\"DynamoDB.BatchWriteItem\"}[1m])) by (table) > 0" start=2020-11-12T12:40:05.402100834Z end=2020-11-12T12:40:05.4021028
94Z step=1s warnings="unsupported value type"

```
