### ISSUE TITLE
CORTEX HA: Strange error while trying to configure HA Tracker

### ISSUE THREAD

**Issue by tomjohnburton** [cortexproject/cortex#3492]
**Describe the bug**
Trying to configure HA tracking for my HA Prometheus set up. Upon enabling `ha_tracker`, my Cortex instance freaks out and start firing thousands of these errors.

```
cortex-67d4f97f9c-czbqg cortex level=error ts=2020-11-12T16:49:54.247606905Z caller=client.go:152 msg="error decoding key" key=ha-tracker/fake/dev err="unexpected EOF"
cortex-67d4f97f9c-czbqg cortex level=error ts=2020-11-12T16:49:54.24763606Z caller=client.go:152 msg="error decoding key" key=ha-tracker/fake/dev err="unexpected EOF"
cortex-67d4f97f9c-czbqg cortex level=error ts=2020-11-12T16:49:54.24767293Z caller=client.go:152 msg="error decoding key" key=ha-tracker/fake/dev err="unexpected EOF"
cortex-67d4f97f9c-czbqg cortex level=warn ts=2020-11-12T16:49:54.247758623Z caller=logging.go:71 traceID=6fba51e6ffc58c67 msg="POST /api/prom/push (500) 804.897µs Response: \"failed to CAS ha-tracker/fake/dev\\n\" ws: false; Content-Encoding: snappy; Content-Length: 6168; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.21.0; X-Prometheus-Remote-Write-Version: 0.1.0; "
```

**Configuration**
`cortex.yaml`
```
...
    distributor:
      shard_by_all_labels: true
      ha_tracker:
        enable_ha_tracker: true <<--- enabling this causes the problem
        kvstore:
          store: inmemory
      pool:
        health_check_ingesters: true

    limits:
      accept_ha_samples: true
      ha_replica_label: "zone"
...
```

`prometheus.yaml`
```
  prometheus.yml: |
    global:
      external_labels:
        cluster: dev
        zone: a
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
....
```

**Storage Engine**
- [ ] Blocks
- [x] Chunks

I'm sure I am just missing something here. TIA
