### ISSUE TITLE
All ingesters reboot after a query execution.

### ISSUE THREAD

**Issue by drequena** [cortexproject/cortex#3500]
**Describe the bug**
Hello everybody.
I'm currently running Cortex 1.5 and I'm experiencing ingesters going down (OOMKill) when prometheus-adapter executes the following query: `sum({namespace!="",__name__!~"^container_.*"})`
To give more context, my environment have 2.6M active time series, in a ingestion rate of 96K reqps, a replication factor of 2  and 6h of in-memory retention. By the math present in the Docs, my ingesters should be using around 4GB of RAM, but since the reboots, I have setup a memory limit to 7GB and scale from 8 to 12 ingesters, in order to "protect" my cortex from rebooting.  (That didn't help, by the way).

**To Reproduce**
a snip of my current config:
```
server:
  http_listen_address: ""
  http_listen_port: 8080
  http_listen_conn_limit: 0
  grpc_listen_address: ""
  grpc_listen_port: 9095
  grpc_listen_conn_limit: 0
  http_tls_config:
    cert_file: ""
    key_file: ""
    client_auth_type: ""
    client_ca_file: ""
  grpc_tls_config:
    cert_file: ""
    key_file: ""
    client_auth_type: ""
    client_ca_file: ""
  register_instrumentation: true
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 2m0s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_connection_idle: 2562047h47m16.854775807s
  grpc_server_max_connection_age: 2562047h47m16.854775807s
  grpc_server_max_connection_age_grace: 2562047h47m16.854775807s
  grpc_server_keepalive_time: 2h0m0s
  grpc_server_keepalive_timeout: 20s
  log_format: logfmt
  log_level: info
  log_source_ips_enabled: false
  log_source_ips_header: ""
  log_source_ips_regex: ""
  http_path_prefix: ""
querier:
  max_concurrent: 20
  timeout: 2m0s
  iterators: false
  batch_iterators: true
  ingester_streaming: false
  max_samples: 50000000
  query_ingesters_within: 6h0m0s
  query_store_after: 0s
  max_query_into_future: 10m0s
  default_evaluation_interval: 1m0s
  active_query_tracker_dir: /data/cortex/querier
  lookback_delta: 5m0s
  store_gateway_addresses: ""
  store_gateway_client:
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_insecure_skip_verify: false
  second_store_engine: ""
  use_second_store_before_time: "0"
  shuffle_sharding_ingesters_lookback_period: 0s
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: false
    grpc_compression: gzip
    rate_limit: 0
    rate_limit_burst: 0
    backoff_on_ratelimits: false
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 10
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_insecure_skip_verify: false
ingester:
  walconfig:
    wal_enabled: true
    checkpoint_enabled: true
    recover_from_wal: true
    wal_dir: /data/wal
    checkpoint_duration: 20m0s
    flush_on_shutdown_with_wal_enabled: false
  lifecycler:
    ring:
      kvstore:
        store: consul
        prefix: collectors/
        consul:
          host: cortex-consul-server:8500
          acl_token: ""
          http_client_timeout: 20s
          consistent_reads: true
          watch_rate_limit: 1
          watch_burst_size: 1
        etcd:
          endpoints: []
          dial_timeout: 10s
          max_retries: 10
          tls_enabled: false
          tls_cert_path: ""
          tls_key_path: ""
          tls_ca_path: ""
          tls_insecure_skip_verify: false
        multi:
          primary: ""
          secondary: ""
          mirror_enabled: false
          mirror_timeout: 2s
      heartbeat_timeout: 1m0s
      replication_factor: 2
      zone_awareness_enabled: false
    num_tokens: 512
    heartbeat_period: 5s
    observe_period: 0s
    join_after: 0s
    min_ready_duration: 1m0s
    interface_names:
    - eth0
    - en0
    final_sleep: 10s
    tokens_file_path: /data/tokens
    availability_zone: ""
    address: ""
    port: 0
    id: cortex-distributor-766dc86c65-7hxcp
  max_transfer_retries: 0
  flush_period: 1m0s
  retain_period: 5m0s
  max_chunk_idle_time: 5m0s
  max_stale_chunk_idle_time: 2m0s
  flush_op_timeout: 1m0s
  max_chunk_age: 6h0m0s
  chunk_age_jitter: 0s
  concurrent_flushes: 50
  spread_flushes: true
  metadata_retain_period: 10m0s
  rate_update_period: 15s
  active_series_metrics_enabled: false
  active_series_metrics_update_period: 1m0s
  active_series_metrics_idle_timeout: 10m0s
flusher:
  wal_dir: wal
  concurrent_flushes: 50
  flush_op_timeout: 2m0s
  exit_after_flush: true
```

**Expected behavior**
This query shouldn't bring cortex ingesters to its knees, specially with so much extra memory added to it.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Storage Engine**
- [ X] Blocks

**Additional Context**
In order to capture the problem, we have removed the memory limits from ingesters k8 statefullset.
My work collage created a feel heap dumps, seconds before ingesters started to reboot.
https://github.com/hugobcar/cortex-heapdump
