### ISSUE TITLE
Support running cortex inside istio service mesh

### ISSUE THREAD

**Issue by papovyr** [cortexproject/cortex#3642]
Distributor is not able to deliver data to ingester (as its speaking with ingesters directly and hostname is not set) 
Is there any knowledge base how Run cortex in istio service mesh ?

**Environment:**
 - Infrastructure: EKS (s3 + dynamodb)
 - Deployment tool: helm

Thank you,

**Comment by pracucci** [comment]
I'm not familiar with Istio or service meshes in general, so I'm just going to share some details about how Cortex works. 

Distributors, as well as queriers or rulers, need to be able to directly connect to ingesters discovered via the hash ring. The ingesters IP address exposed in the ring must be directly addressable by other Cortex components, but you can control it via the `-ingester.lifecycler.addr` CLI option (set it to the IP address of a specific ingester).

**Comment by pstibrany** [comment]
Note that we use the ring, and thus direct connection to IPs in some other places as well:
- queriers connecting to store-gateways
- rulers connecting to each other

I'm not aware of anyone using Cortex with Istio.

**Comment by simonxmh** [comment]
+1 we are also running into issues running Cortex with Istio, especially running with the mTLS.
Distributor -> ingester , query-frontend -> queriers are both restricted from communicating.

**Comment by snuggie12** [comment]
I'm attempting to get loki in microservices mode working and seeing the same issues you all are mentioning. I think it could work if you could tell the distributor or querier to use a DNS entry instead of an IP address. For example, there currently exists `loki-ingester-0.loki-ingester-headless.monitoring.svc.cluster.local` in my installation. You can then create a `ServiceEntry` tracking those to make it work.

**Comment by pracucci** [comment]
> I think it could work if you could tell the distributor or querier to use a DNS entry instead of an IP address.

Cortex (as well as Loki) services need to directly address ingesters, due to how sharding and replication works. For this reason, we have a shared hash ring where ingesters are registered by IP and other services (ie. distributors, queriers, rulers) directly address ingesters by IP. Direct addressing is required and something I see it difficult to move away.

That being said, to my understand it could work to you if each ingester would be addressed by a per-pod hostname instead of IP. Is my understanding correct?

**Comment by snuggie12** [comment]
I believe so. This is how something like zookeeper or kafka works:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ingester
spec:
  hosts:
  - ingester-0.ingester-headless.monitoring.svc.cluster.local
  - ingester-1.ingester-headless.monitoring.svc.cluster.local
  - ingester-2.ingester-headless.monitoring.svc.cluster.local
  ports:
  - name: grpc
    number: 9095
    protocol: TCP
```
