### ISSUE TITLE
Cortex GKE/GCS Block storage configuration problem

### ISSUE THREAD

**Issue by MRostanski** [cortexproject/cortex#3737]
Hello, 

We are trying to run Cortex on GKE cluster (1.16.15-gke.7800) with blocks storage, using Consul as KV and GKE as a block storage and with Helm.

1. We are doing everything in single namespace, named "cortex".
2. We have deployed Consul for key-value store, using Helm 3.

Repo: https://helm.releases.hashicorp.com

Chart: consul-0.29.0 (appVersion: 1.9.2)

```bash
helm upgrade --install consul hashicorp/consul -f values.yaml -n cortex 
```

values for consul:

```yaml
global:
  datacenter: redacted
ui:
  service:
    type: "LoadBalancer"
syncCatalog:
  enabled: true
```

The operation is successful - Consul UI is visible and working under LoadBalancer address. To eliminate possible issues, it is not restricted with any ACLs.

A "collectors/" folder can be created easily in Consul KV Store, confirmed in UI.

3. We are using helm deploy for Cortex as follows:

Repo: 	https://cortexproject.github.io/cortex-helm-chart

Chart: 0.3.0 (appVersion: v1.6.0, however image tag in default chart values is: v1.4.0)

Changes in our-values.yaml:

```yaml
config:
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: consul
          consul:
            host: "consul-consul-server.cortex.svc.cluster.local:8500"
   storage:
    engine: blocks
  querier:
    iterators: true # This option needs be set both on the store-gateway and querier when running in microservices mode.
  distributor:
    ring:
      kvstore:
        store: consul
        consul:
          host: "consul-consul-server.cortex.svc.cluster.local:8500"
  blocks_storage:
    backend: gcs
    gcs:
      bucket_name: aiops-central-cortex-test
  compactor:
    sharding_enabled: true
    # Sharding is required if you run multiple compactor instances
    # https://cortexmetrics.io/docs/configuration/configuration-file/
    sharding_ring:
      kvstore:
        store: consul
        consul:
          host: "consul-consul-server.cortex.svc.cluster.local:8500"
          consistent_reads: true # Enable consistent reads

  store_gateway:
    sharding_enabled: true # This option needs be set both on the store-gateway and querier when running in microservices mode.
    sharding_ring:
      kvstore:
        store: consul
        consul:
          host: "consul-consul-server.cortex.svc.cluster.local:8500"
          consistent_reads: true
```

The default config.schema in values.yaml is left. As we understand, in https://cortexmetrics.io/docs/chunks-storage/schema-configuration/ it is written:

"The schema config is used only by the chunks storage, while it’s not used by the blocks storage engine."

That's why we removed this section in our values.yaml (left default). And, as according to https://cortexmetrics.io/docs/blocks-storage/ - both the table-manager and the schema config are not used by the blocks storage - we have removed "table-manager" section as well.

However, it is said in the above documentation, that "The general configuration documentation also applies to a Cortex cluster running the blocks storage. The blocks storage can be enabled switching the storage engine to blocks". Also, according to the docs, the "storage" section (storage_config) should also be used only in case of chunks storage engine (https://cortexmetrics.io/docs/configuration/configuration-file/), however there is also "chunk_store" section, dedicated to chunks storage configuration, which is a bit misleading.
So, we tried removing "storage" section completely and we just added a section for blocks storage into config.blocks_storage for gcs.

This configuration results in errors at first, but then some services are started, some not.

alertmanager:

```txt
level=info ts=2021-01-24T17:23:11.567600858Z caller=main.go:178 msg="Starting Cortex" version="(version=1.4.0, branch=HEAD, revision=23554ce02)"
(...) 
level=info ts=2021-01-24T17:23:11.770909377Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=200.101783ms
level=info ts=2021-01-24T17:23:12.573772453Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=1.00296701s
level=warn ts=2021-01-24T17:23:12.719392972Z caller=multitenant.go:289 component=MultiTenantAlertmanager msg="error fetching all configurations, backing off" err="Get \"http://cortex-configs.cortex.svc.cluster.local:8080/private/api/prom/configs/alertmanager\": dial tcp 10.240.176.171:8080: connect: connection refused"
```

..but it eventually starts.

I think the example for blocks storage should be more explicitly described in the chart repository.

**ACTUAL PROBLEM**

The above example runs every component without restarts and everything seems in order. But the queriers (and ruler) show some errors constantly every minute:

```txt
level=error ts=2021-01-24T20:04:16.288531704Z caller=pool.go:161 msg="error removing stale clients" err="too many failed ingesters"
```

Also, when trying to remote_write, we get constant errors from ingesters and on nginx 500 error codes. 

This is not the case of wrong/missing GCP credentials, because we are set up Nodes Service Account to be able to write to GCS anywhere:

```txt
root@pod:/# gsutil cp test.txt gs://redacted-cortex-test/
Copying file://test.txt [Content-Type=text/plain]...
/ [1 files][    0.0 B/    0.0 B]                                                
Operation completed over 1 objects.     
```

The ingester logs seem fine:

```txt
level=info ts=2021-01-24T20:25:47.137986286Z caller=main.go:178 msg="Starting Cortex" version="(version=1.4.0, branch=HEAD, revision=23554ce02)"
level=info ts=2021-01-24T20:25:47.138270961Z caller=server.go:225 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-01-24T20:25:47.143587046Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2021-01-24T20:25:47.143728187Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2021-01-24T20:25:47.143777616Z caller=module_service.go:58 msg=initialising module=ingester-service
level=info ts=2021-01-24T20:25:47.143814335Z caller=ingester_v2.go:1012 msg="opening existing TSDBs"
level=info ts=2021-01-24T20:25:47.143846681Z caller=ingester_v2.go:1078 msg="successfully opened existing TSDBs"
level=info ts=2021-01-24T20:25:47.143884194Z caller=lifecycler.go:495 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2021-01-24T20:25:47.143984722Z caller=cortex.go:341 msg="Cortex started"
level=info ts=2021-01-24T20:25:47.188301186Z caller=lifecycler.go:519 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2021-01-24T20:25:47.200509417Z caller=lifecycler.go:371 msg="auto-joining cluster after timeout" ring=ingester 
```
