### ISSUE TITLE
Compactor errors with 204 No Content

### ISSUE THREAD

**Issue by nivekuil** [cortexproject/cortex#3823]
**Describe the bug**
The compactor seems to treat a 204 response as a failed delete, but I think it should be correct: https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html

Example logs from the compactor:
`  level=error ts=2021-02-13T20:48:19.559803519Z caller=compactor.go:512 component=compactor msg="failed to compact user blocks" user=fake err="compaction: sync: filter metas: filter blocks marked for deletion: get file: 01EWVJGNFM38BZZ40SETQ6NKR1/deletion-mark.json: 204 No Content"
`
`level=error ts=2021-02-13T20:47:30.315004291Z caller=blocks_cleaner.go:141 component=cleaner msg="failed to run blocks cleanup and maintenance" err="failed to delete blocks for user: fake: get file: 01EWVJGNFM38BZZ40SETQ6NKR1/deletion-mark.json: 204 No Content"`
`level=warn ts=2021-02-13T20:47:30.314910976Z caller=blocks_cleaner.go:288 component=cleaner org_id=fake msg="failed blocks cleanup and maintenance" err="get file: 01EWVJGNFM38BZZ40SETQ6NKR1/deletion-mark.json: 204 No Content"`
`level=warn ts=2021-02-13T20:47:30.267520397Z caller=blocks_cleaner.go:297 component=cleaner org_id=fake msg="failed to migrate block deletion marks to the global markers location" err="2 errors: 204 No Content; 204 No Content"`

**To Reproduce**

Running Cortex on master-cdb4a8d, block storage and blocks index enabled, writing to SeaweedFS 2.24 S3 gateway.

**Expected behavior**
The compactor correctly deletes stuff.

**Comment by pstibrany** [comment]
These errors are not from doing delete operations, but "Get" (reading object) operations, where 204 status code is treated as error.

**Comment by pracucci** [comment]
@pstibrany is correct. However the errors you're getting may be feel you're running multiple compactor replicas without having enabled the sharding. Could you share more details about your setup?

Be aware that the errors you're getting are related to the migration of deletion marks to the global location. Once you run the migration once, you can disable it forever in the compactor setting `-compactor.block-deletion-marks-migration-enabled=false`.

**Comment by nivekuil** [comment]
Initially, I had a single-binary cortex running in a Docker Swarm cluster.  That worked fine.  Trying out the blocks storage, it seemed like I needed a compactor running or the query wouldn't be able to see data beyond the current day or so.  The single binary config without any flags seems to omit a compactor (nothing in logs), so I spun out another service with -target=compactor, which did start with the compactor module.  So I think I only have one compactor running.

These two services should be part of the same memberlist gossip ring.  However, it seems like their communication is flapping.  They are part of the same memberlist only briefly before disconnecting, with logs like:

```
ts=2021-02-15T16:19:37.832369665Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:19:38.332956163Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48562"
ts=2021-02-15T16:19:38.333251448Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:19:45.831888801Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:19:46.832294351Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:19:47.332936976Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48596"
ts=2021-02-15T16:19:47.333484677Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:19:49.832198187Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:19:54.831710365Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:20:03.831195059Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:20:06.86824428Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:20:08.832256543Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:20:09.333227212Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48704"
ts=2021-02-15T16:20:09.333356425Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:20:16.831834153Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:20:17.832188514Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:20:18.332710984Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48736"
ts=2021-02-15T16:20:18.332813307Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:20:20.832259193Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:20:25.831718903Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:20:33.831466448Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:20:36.869375028Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:20:37.832337825Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:20:38.332971221Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48836"
ts=2021-02-15T16:20:38.333332831Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:20:45.831954182Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:20:46.832353551Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:20:47.332921679Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48864"
ts=2021-02-15T16:20:47.333535264Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:20:49.832359196Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:20:54.831821833Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:21:03.832437432Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:21:06.870479297Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:21:07.832380374Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:21:08.333646685Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48968"
ts=2021-02-15T16:21:08.334423457Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:21:15.831922847Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:21:15.832846615Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:21:16.333642529Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:48998"
ts=2021-02-15T16:21:16.333858766Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:21:19.832254718Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:21:23.832284435Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:21:33.832047291Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:21:36.870173183Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:21:37.832210824Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:21:38.333056529Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49102"
ts=2021-02-15T16:21:38.333749112Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:21:45.831857151Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:21:46.832454771Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:21:47.333254803Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49142"
ts=2021-02-15T16:21:47.333550881Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:21:49.832222174Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:21:54.831845732Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:22:03.830848865Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:22:06.869938677Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:22:08.832248203Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:22:09.332696715Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49236"
ts=2021-02-15T16:22:09.332961532Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:22:16.831909076Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:22:17.832236065Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:22:18.332897101Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49270"
ts=2021-02-15T16:22:18.333475249Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:22:20.832223188Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:22:25.831822949Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:22:33.832297471Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:22:36.869160035Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:22:37.832287671Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:22:38.332988311Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49366"
ts=2021-02-15T16:22:38.333389096Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:22:45.831775145Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:22:45.833154501Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:22:46.333927665Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49394"
ts=2021-02-15T16:22:46.334082125Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
ts=2021-02-15T16:22:49.832089069Z caller=memberlist_logger.go:74 level=info msg="Marking compactor-a5cf99da as failed, suspect timeout reached (0 peer confirmations)"
ts=2021-02-15T16:22:53.832272242Z caller=memberlist_logger.go:74 level=info msg="Suspect compactor-a5cf99da has failed, no acks received"
ts=2021-02-15T16:23:03.830697819Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: main-bdfce6e4)"
level=info ts=2021-02-15T16:23:06.869687702Z caller=memberlist_client.go:456 msg="re-joined memberlist cluster" reached_nodes=2
ts=2021-02-15T16:23:08.832099081Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'compactor-a5cf99da' from=172.18.0.13:7946"
ts=2021-02-15T16:23:09.332739414Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node compactor-a5cf99da from=172.18.0.13:49630"
ts=2021-02-15T16:23:09.333612147Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: EOF"
```
So there looks to be something wrong with my setup as well. Config that differs from the defaults:
```
auth_enabled: false
blocks_storage:
  bucket_store:
    bucket_index:
      enabled: true
    sync_dir: /tmp/cortex/tsdb-sync
  s3:
    access_key_id: a40647552592722aa9fe3dad17805876
    bucket_name: cortex
    endpoint: s3:8333
    insecure: true
    secret_access_key: '********'
  tsdb:
    dir: /tmp/cortex/tsdb
    flush_blocks_on_shutdown: true
    wal_compression_enabled: true
compactor:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
distributor:
  ring:
    kvstore:
      store: memberlist
  shard_by_all_labels: true
frontend:
  compress_responses: true
  log_queries_longer_than: 1s
frontend_worker:
  match_max_concurrent: true
ingester:
  lifecycler:
    final_sleep: 5s
    join_after: 10s
    min_ready_duration: 0s
    num_tokens: 512
    observe_period: 10s
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
ingester_client:
  grpc_client_config:
    grpc_compression: gzip
    max_send_msg_size: 104857600
memberlist:
  dead_node_reclaim_time: 30m0s
  join_members:
  - tasks.cortex:7946
  - tasks.cortex-compactor:7946
  node_name: main
  rejoin_interval: 30s
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      redis:
        endpoint: redis:6379
        expiration: 24h0m0s
        max_connection_age: 30m0s
  split_queries_by_interval: 24h0m0s
server:
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
storage:
  engine: blocks
store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
```

Is a 204 on reading an empty file out of spec for an S3 gateway in general, or is that correct and Cortex expects there to be content in the files it's trying to read, and correctly errors out due to something else wrong?
