### ISSUE TITLE
dns error: no such host

### ISSUE THREAD

**Issue by mhaddon** [cortexproject/cortex#3966]
**Describe the bug**
I get DNS issues when trying to run cortex

Such as:

```
level=info ts=2021-03-17T23:22:54.652031315Z caller=main.go:178 msg="Starting Cortex" version="(version=1.4.0, branch=HEAD, revision=23554ce02)"
level=info ts=2021-03-17T23:22:54.652370205Z caller=server.go:225 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2021-03-17T23:22:54.652890205Z caller=session.go:286 module=gocql client=index-read msg="dns error" error="lookup : no such host"
level=error ts=2021-03-17T23:22:54.653142466Z caller=log.go:149 msg="error running cortex" err="gocql: unable to create session: failed to resolve any of the provided hostnames\ngithub.com/cortexproject/cortex/pkg/chunk/cassandra.(*Config).session\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/cassandra/storage_client.go:126\ngithub.com/cortexproject/cortex/pkg/chunk/cassandra.NewStorageClient\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/cassandra/storage_client.go:226\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewIndexClient\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:233\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:174\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).initChunkStore\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:362\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:87\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:316\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:180\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\ngithub.com/cortexproject/cortex/pkg/chunk/cassandra.NewStorageClient\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/cassandra/storage_client.go:228\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewIndexClient\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:233\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:174\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).initChunkStore\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:362\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:87\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:316\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:180\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/go/src/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:176\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).initChunkStore\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:362\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:87\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:316\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:180\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:89\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:316\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:180\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
stream closed             
```

I have this error on the ingester, querier, ruler and table-manager.

**To Reproduce**
Install cortex with helm

**Expected behavior**
Not this

**Environment:**
 - Infrastructure: Kubernetes 1.17 - GKE STABLE
 - Deployment tool: Helm

**Storage Engine**
- [ x ] Blocks
- [ ] Chunks

**Additional Context**
```
    values: |
      alertmanager:
        replicas: 1
      distributor:
        replicas: 1
      ingester:
        replicas: 1
      ruler:
        replicas: 1
      querier:
        replicas: 1
      query_frontend:
        replicas: 1
      table_manager:
        replicas: 1
      configs:
        replicas: 1
      nginx:
        replicas: 1
      store_gateway:
        replicas: 1
      compactor:
        replicas: 1
      serviceAccount:
        create: true
        name: cortex
        annotations:
          iam.gke.io/gcp-service-account: x
      ingress:
        enabled: false
      config:
        blocks_storage:
          backend: gcs
          gcs:
            bucket_name: x
```
