### ISSUE TITLE
Store Gateway fails health checks while loading blocks

### ISSUE THREAD

**Issue by cabrinha** [cortexproject/cortex#3974]
**Describe the bug**
store-gateway statefulset pods take a really long time to pass liveness / readiness probes while loading blocks.

The pod is up and doing it's job but since the liveness probe fails, the container is restarted, forcing the pod to start all over again.

**To Reproduce**
1. Start Cortex 1.7.0
2. Have a lot of blocks in s3, with store-gateway running as a stateful set
3. Liveness probe failed: HTTP probe failed with statuscode: 503
4. Readiness probe failed: Get http://192.168.19.242:8080/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
5. Logs show "loaded new block", which is great.

**Expected behavior**
store-gateway should respond to ready/liveness probes during block loading

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool:  helm

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**
https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L1058-L1072

Looks like the helm chart tries to work around this by setting failure thresholds very high, which isn't the best.

Also, I'm running 5 instances of store-gateway joined in a ring by consul, but for some reason it takes a very long time for them to sync. Over 30 minutes in some cases.

I do have `-blocks-storage.bucket-store.bucket-index.enabled` set to `true`.

```yaml
  config:
    auth_enabled: true
    blocks_storage:
      s3:
        endpoint: ""
        bucket_name: ""
      bucket_store:
        bucket_index:
          enabled: true
```

**Comment by pracucci** [comment]
The store-gateway is not ready to serve queries until the initial sync is done. The readiness probe intentionally fails until the store-gateway is not ready.

> I'm running 5 instances of store-gateway joined in a ring by consul, but for some reason it takes a very long time for them to sync. Over 30 minutes in some cases.

Few suggestions to speed up store-gateway:
1. Make sure the compactor is running and catching up (we expect 1 block per day per tenant for any data older than 24h)
2. Make sure metadata cache (memcached) is configured
3. Make sure store-gateway sharding is enabled
4. If needed, scale up store-gateways, so each gateway will load less blocks

**Comment by cabrinha** [comment]
> The store-gateway is not ready to serve queries until the initial sync is done. The readiness probe intentionally fails until the store-gateway is not ready.

That's acceptable, but can we make sure the livenessprobe will pass during block loading?

> > I'm running 5 instances of store-gateway joined in a ring by consul, but for some reason it takes a very long time for them to sync. Over 30 minutes in some cases.
> 
> Few suggestions to speed up store-gateway:
> 
> 1. Make sure the compactor is running and catching up (we expect 1 block per day per tenant for any data older than 24h)

I only have 1 tenant at the moment. Compactor does show some errors for certain blocks:
```
{"caller":"compactor.go:456","component":"compactor","err":"compaction: group 0@17918867045866434399: block with not healthy index found data/compact/0@17918867045866434399/01EZZ9TYWEHHP1B727PX90SWSK; Compaction level 1; Labels: map[__org_id__:platform]: 4/4978394 series have an average of 1.000 out-of-order chunks: 24.250 of these are exact duplicates (in terms of data and time range)","level":"error","msg":"failed to compact user blocks","ts":"2021-03-19T18:02:53.288979391Z","user":"platform"}
```

Not sure what to do about this.

> 2. Make sure metadata cache (memcached) is configured

Would this be memcached-blocks-metadata? I'm using the statefulset here: https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L1375

Here is the relevant section of my config:
```yaml
config:
  blocks_storage:
    bucket_store:
        metadata_cache:
          backend: memcached
          memcached:
            addresses: dnssrvnoa+_cortex-memcached-blocks-metadata._tcp.cortex-memcached-blocks-metadata.cortex.svc.cluster.local
```

Anything else I'm missing?

> 3. Make sure store-gateway sharding is enabled

It is.

> 4. If needed, scale up store-gateways, so each gateway will load less blocks

Ok, I'll scale up to 16 replicas of the store-gateway.
