### ISSUE TITLE
Ingester and Frontend Services will use Automatic Private IP Addressing if encountered first

### ISSUE THREAD

**Issue by jbvmio** [cortexproject/cortex#4014]
**Describe the bug**
Most like an error in configuration:

/v1/distributor/all_user_stats shows the following error:
rpc error: code = Unimplemented desc = unknown service cortex.Ingester

Attempting to remote write to the distributor also displays the same error:
```
{"caller":"logging.go:71","level":"warn","msg":"POST /v1/api/v1/push (500) 1.704742ms Response: \"rpc error: code = Unimplemented desc = unknown service cortex.Ingester\\n\" ws: false; Content-Encoding: snappy; Content-Length: 5001; Content-Type: application/x-protobuf; User-Agent: cortex-tenant; X-Cortex-Tenant-Client: x.x.x.x:2238; X-Cortex-Tenant-Reqid: daffa99b-fdc2-4063-b425-9c7cee097b0e; X-Prometheus-Remote-Write-Version: 0.1.0; X-Scope-Orgid: default; ","traceID":"4869661e7b4b9092","ts":"2021-03-25T21:28:41.397695895Z"}
```

**To Reproduce**
Deploy Cortex in microservices mode on ECS Fargate, each service running in a separate task. Use memberlist for the ring.

Configs:
```
storage:
  engine: blocks

blocks_storage:
  bucket_store:
    bucket_index:
      enabled: true
    chunks_cache:
      backend: memcached
      memcached:
        addresses: dnssrv+memcached.cortex
    index_cache:
      backend: memcached
      memcached:
        addresses: dnssrv+memcached.cortex
    metadata_cache:
      backend: memcached
      memcached:
        addresses: dnssrv+memcached.cortex
    sync_dir: /cortex-data
  s3:
    bucket_name: etr-cortex-ingester-bucket
    endpoint: s3.us-east-1.amazonaws.com
    signature_version: v2
  tsdb:
    dir: /cortex-data

distributor:
  extend_writes: false
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      consul:
        host: consul.cortex:8500
  ring:
    kvstore:
      store: memberlist
  sharding_strategy: shuffle-sharding

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
      zone_awareness_enabled: true

memberlist:
  join_members:
  - dnssrv+ingester-ring.cortex:7946
  node_name: distributor-ue1
  rejoin_interval: 1m0s

store_gateway:
  sharding_enabled: true
  sharding_ring:
    instance_availability_zone: us-east-1a
    kvstore:
      store: memberlist
    replication_factor: 2
    zone_awareness_enabled: true
  sharding_strategy: shuffle-sharding

```

**Expected behavior**
Expected to see tenant stats or something other than the error message when clicking "Usage Statistics" on Distributor Endpoint.

Expected successful remote writes instead of the error message shown above.

**Environment:**
 - Infrastructure: AWS ECS Fargate
 - Deployment tool: Terraform

**Storage Engine**
- [x ] Blocks

**Additional Context**
Is there any documentation when deploying in microservices mode? Most examples only show single binary mode. When providing configs, for example, config validation can take place for missing details for completely different service that what is specified as the "target". I've noticed that validation can be run before it is even discovered what "target" has been assigned by using target=ugh. Does the block storage config need to match on the distributor and the ingester for example?
