### ISSUE TITLE
Querier not able to connect to store-gateway ring (etcd)

### ISSUE THREAD

**Issue by vicmania2007** [cortexproject/cortex#4022]
**Describe the bug**

Cortex version - 1.7.0

Cortex querier is not able to connect to the ring created by store-gateway. The ring is created when checked via /store-gateway/ring endpoint. Also the documentation is confusing/not clear as to what is the exact spec/config to be added in the querier end to know the destination of the store-gateway ring. I asked this in cortex slack channel https://cloud-native.slack.com/archives/CCYDASBLP/p1616696353176400. Couldnt get a good response.

**To Reproduce**
1. Start Cortex Storegateway with sharding enabled and pointing towards the ring.
``` CLI arguments
containers:
        - name: cortex
          image: "quay.io/cortexproject/cortex:v1.7.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-target=store-gateway"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379"
            - "-store-gateway.tenant-shard-size=2"
```
Config arguments:
```
store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore: 
      store: etcd
      prefix: "store_gateway/"
```
2. Check the /storew-gateway/ring, if the ring is formed.
3. Start querier with following CLI arguments
```
- "-target=querier"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-store-gateway.sharding-ring.store=etcd"
            - "-store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379"
            # - "-store-gateway.sharding-ring.etcd.endpoints='cortex-etcd-0.cortex-etcd-headless.default.svc.cluster.local:2379'"
            # - "-store-gateway.sharding-ring.etcd.endpoints='cortex-etcd-1.cortex-etcd-headless.default.svc.cluster.local:2379'"
            # - "-store-gateway.sharding-ring.etcd.endpoints='cortex-etcd-2.cortex-etcd-headless.default.svc.cluster.local:2379'"
            - "-store-gateway.sharding-ring.prefix=store_gateway/"
            - "-store-gateway.tenant-shard-size=2"
            - "-querier.scheduler-address=cortex-query-scheduler-headless.default.svc.cluster.local:9095"
            - "-querier.query-ingesters-within=24h5m"
            - "-querier.query-store-after=24h"
            - "-querier.shuffle-sharding-ingesters-lookback-period=24h10m"
```
4. Getting error in querier, that the ring is not able to formed.
`{"caller":"log.go:150","err":"etcdclient: no available endpoints\nerror initialising module: ring\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/__w/cortex/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/__w/cortex/cortex/pkg/util/modules/modules.go:75\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:365\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:189\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","level":"error","msg":"error running cortex","ts":"2021-03-26T19:58:56.45984514Z"}`

**Expected behavior**
Querier should be able to connect to the ring of store-gateway.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
Kubernetes (1.1.15)
 - Deployment tool: [e.g., helm, jsonnet] -  Helm

**Storage Engine**
- [yes] Blocks 
- [ ] Chunks

**Additional Context**

**Comment by vicmania2007** [comment]
Also tried with config field values as suggested in slack channel. Tried various fields under **querier** config. For all the values, i tried i got error, **not in querier config file.**

```
querier:
  default_evaluation_interval: 15s
  **<ring/sharding-ring/store-gateway/store_gateway>**
  kvstore: 
    store: etcd
    prefix: "store_gateway/"
    etcd:
      endpoints: http://cortex-etcd.default.svc.cluster.local:2379
```

**Comment by pracucci** [comment]
> `etcdclient: no available endpoints`

Looks like the store-gateway ring's etcd endpoints is empty. I can see `-store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379` has been set so I'm not sure what's happening here. Could you double check the CLI flags applied to the pod once running, please?


> Tried various fields under querier config. For all the values, i tried i got error, not in querier config file.

You need to pass the store-gateway ring config to the querier, similarly to what you did with CLI flags (passing `-store-gateway.sharding-ring.*` CLI flags to querier too).

_This is a common config pattern in Cortex. If a service X needs a config which is originally set to Y, just set the Y config to the service X too._

**Comment by vicmania2007** [comment]
> Looks like the store-gateway ring's etcd endpoints is empty. I can see -store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379 has been set so I'm not sure what's happening here. Could you double check the CLI flags applied to the pod once running, please?

**Sure, see this**
**Querier deployment to check the CLI flags that are applied to pod once running.**
```
akc describe deployment cortex-querier
Name:                   cortex-querier
Namespace:              default
CreationTimestamp:      Mon, 29 Mar 2021 10:50:21 -0400
Labels:                 app=cortex-querier
                        chart=cortex-0.2.0
                        heritage=Tiller
                        release=cortex
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=cortex-querier,release=cortex
Replicas:               3 desired | 3 updated | 3 total | 0 available | 3 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 0 max surge
Pod Template:
  Labels:       app=cortex-querier
                name=cortex-querier
                release=cortex
                target=querier
  Annotations:  checksum/config: 6dd406f10b037c8f1727c9703989ae342b09846df41aea9dacbd8d76a7c6fde4
                prometheus.io/port: http-metrics
                prometheus.io/scrape: true
  Containers:
   cortex:
    Image:      quay.io/cortexproject/cortex:v1.7.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      -target=querier
      -config.file=/etc/cortex/cortex.yaml
      -store-gateway.sharding-ring.store=etcd
      -store-gateway.sharding-ring.prefix=store_gateway/
      -store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379
      -querier.scheduler-address=cortex-query-scheduler-headless.default.svc.cluster.local:9095
      -querier.query-ingesters-within=24h5m
      -querier.query-store-after=24h
      -querier.shuffle-sharding-ingesters-lookback-period=24h10m
    Limits:
      cpu:     600m
      memory:  2Gi
    Requests:
      cpu:        600m
      memory:     1Gi
    Liveness:     http-get http://:http-metrics/ready delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http-metrics/ready delay=120s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from storage (rw)
      /etc/cortex from config (rw)
  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cortex
    Optional:    false
   storage:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  cortex-querier-6644f7cdd (3/3 replicas created)
NewReplicaSet:   <none>
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  46s   deployment-controller  Scaled up replica set cortex-querier-6644f7cdd to 3
```
**End points to see the etcd endpoints that were created**
```
akc get endpoints
NAME                                     ENDPOINTS                                                             AGE
cortex                                   172.16.5.244:443,172.16.6.112:443,172.16.7.115:443 + 3 more...        14d
cortex-compactor                         172.16.4.182:8080,172.16.5.230:8080,172.16.7.99:8080                  11d
cortex-distributor                       172.16.3.223:8080,172.16.4.190:8080,172.16.5.240:8080 + 2 more...     12d
cortex-etcd                              172.16.3.213:2380,172.16.4.181:2380,172.16.6.95:2380 + 3 more...      12d
cortex-etcd-headless                     172.16.3.213:2380,172.16.4.181:2380,172.16.6.95:2380 + 3 more...      12d
cortex-ingester                          172.16.3.216:8080,172.16.5.239:8080,172.16.7.100:8080                 12d
cortex-poc-memcached-chunk-headless      172.16.4.198:11211,172.16.4.200:11211,172.16.4.198:9150 + 1 more...   4d23h
cortex-poc-memcached-index-headless      172.16.4.196:11211,172.16.4.197:11211,172.16.4.196:9150 + 1 more...   5d1h
cortex-poc-memcached-metadata-headless   172.16.4.199:11211,172.16.4.201:11211,172.16.4.199:9150 + 1 more...   4d23h
cortex-poc-memcached-result-headless     172.16.4.202:11211,172.16.4.203:11211,172.16.4.202:9150 + 1 more...   3d23h
cortex-querier                                                                                                 13m
cortex-store-gateway                     172.16.3.250:9095,172.16.6.151:9095,172.16.7.139:9095 + 3 more...     20m
kubernetes                               10.3.114.44:443,10.3.114.45:443,10.3.114.47:443                       160d
prometheus-service                       172.16.6.99:80,172.16.7.104:80                                        6d19h
```

> You need to pass the store-gateway ring config to the querier, similarly to what you did with CLI flags (passing -store-gateway.sharding-ring.* CLI flags to querier too).

**Yeah i have set the same CLI for both store-gateway and querier. Store-gateway picks it up and creates the ring. Not sure why querier is not picking it up.** 
```
CLI set for store-gateway
          args:
            - "-target=store-gateway"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-store-gateway.sharding-enabled=true"
            - "-store-gateway.sharding-ring.store=etcd"
            - "-store-gateway.sharding-ring.prefix=store_gateway/"
            - "-store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379"
            - "-store-gateway.tenant-shard-size=2"
CLI for querier (shown in earlier describe deployment)
           args:
            - "-target=querier"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-store-gateway.sharding-ring.store=etcd"
            - "-store-gateway.sharding-ring.prefix=store_gateway/"
            - "-store-gateway.sharding-ring.etcd.endpoints=http://cortex-etcd.default.svc.cluster.local:2379"
            - "-querier.scheduler-address=cortex-query-scheduler-headless.default.svc.cluster.local:9095"
            - "-querier.query-ingesters-within=24h5m"
            - "-querier.query-store-after=24h"
            - "-querier.shuffle-sharding-ingesters-lookback-period=24h10m"
```
**Ring:**            
            
![image](https://user-images.githubusercontent.com/6048841/112858036-7b5ef880-907f-11eb-8f39-4ea5969867f9.png)

**Comment by containerpope** [comment]
I had the same issue, when I tried to add store-gateway ring settings to querier component, it immediately crashes with an error message, that the querier has no configuration flags for the ring. 

```yaml
querier:
  active_query_tracker_dir: /data/cortex/querier
  query_ingesters_within: 725m #12h 5m
  query_store_after: 720m #12h 
  query_store_for_labels_enabled: true
  store_gateway:
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: consul
        prefix: 'collectors/'
        consul:
          host: 'consul-consul-server:8500'
          http_client_timeout: '20s'
          consistent_reads: true
```
Did I get the documentation wrong on that point? I also drilled down in the querier go interface, not finding any keys for the ring storage. 

At first I had a config like this, which resulted in gaps for the Grafana queries in the graphs.
```yaml
querier:
  active_query_tracker_dir: /data/cortex/querier
  query_ingesters_within: 725m #12h 5m
  query_store_after: 720m #12h 
  query_store_for_labels_enabled: true
  store_gateway_addresses: cortex-store-gateway-headless:9095
```
I assumed, it was only looking into one store-gateway, so I tried the ring settings, but ended with crashing containers. 

Now I have configured it without any store-gateway flags and it works correct.
```yaml
querier:
  active_query_tracker_dir: /data/cortex/querier
  query_ingesters_within: 725m #12h 5m
  query_store_after: 720m #12h 
  query_store_for_labels_enabled: true
```

My querier has no flags at all for store-gateway:
```yaml
apiVersion: v1
kind: Pod
...
  containers:
  - args:
    - -target=querier
    - -config.file=/etc/cortex/cortex.yaml
    - -querier.frontend-address=cortex-query-frontend-headless.base-monitoring.svc.cluster.local:9095
    - -config.expand-env=true
...
```

Am I doing something fundamentally wrong here?
