### ISSUE TITLE
Store Gateway pods take hours and up to 1.7TB to become ready

### ISSUE THREAD

**Issue by cabrinha** [cortexproject/cortex#4075]
**Describe the bug**
Store Gateway pods take a long time ( one hour or more ) and up to 1.7TB to become ready

**To Reproduce**
1. Start Cortex v1.8.0
2. Have around 3.5 million active series
3. have store-gateway use PVC, 16 replicas, StatefulSet
4. Restart any pod, watch it consume a ton of disk while logging "loaded new block" for an hour or two
5. After sync success, disk usage drops to about 300GB until any ring change happens, then process will repeat

**Expected behavior**

**Environment:**
 - Infrastructure: Kubernetes / EKS
 - Deployment tool: helm

**Storage Engine**
- [ x ] Blocks
- [ ] Chunks

**Additional Context**

## Logs
```
{"caller":"bucket.go:513","elapsed":"1.066348466s","id":"01F23HA5AC86T4B5FQPPRF6851","level":"info","msg":"loaded new block","org_id":"platform","ts":"2021-04-13T22:49:57.480691954Z"}
{"caller":"bucket_stores.go:148","level":"info","msg":"successfully synchronized TSDB blocks for all users","ts":"2021-04-13T22:49:57.659385458Z"}
{"caller":"gateway.go:254","level":"info","msg":"waiting until store-gateway is ACTIVE in the ring","ts":"2021-04-13T22:49:57.677126749Z"}
{"caller":"gateway.go:258","level":"info","msg":"store-gateway is ACTIVE in the ring","ts":"2021-04-13T22:49:57.778188744Z"}
{"caller":"cortex.go:412","level":"info","msg":"Cortex started","ts":"2021-04-13T22:49:57.778277785Z"}
```

## Config
```yaml
# cortex main config file
  config:
    auth_enabled: true
    blocks_storage:
      s3:
        endpoint: ""
        bucket_name: ""
      bucket_store:
        index_header_lazy_loading_enabled: true
        bucket_index:
          enabled: true
        chunks_cache:
          backend: memcached
          memcached:
            addresses: dnssrvnoa+_cortex-memcached._tcp.cortex-memcached.cortex.svc.cluster.local
        index_cache:
          backend: memcached
          memcached:
            addresses: dnssrvnoa+_cortex-memcached-blocks-index._tcp.cortex-memcached-blocks-index.cortex.svc.cluster.local
        metadata_cache:
          backend: memcached
          memcached:
            addresses: dnssrvnoa+_cortex-memcached-blocks-metadata._tcp.cortex-memcached-blocks-metadata.cortex.svc.cluster.local
        sync_dir: "data"
      tsdb:
        dir: "/data"
        retention_period: 3h
```

**Comment by jtlisi** [comment]
@cabrinha Have you enabled sharding in your store-gateways? If not, each store gateway will think it's responsible for the entire set of blocks in your S3 bucket.

The following snippet with a valid KV store config added should work:

```yaml
store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      #      <insert KV store config here>
      # for example:
      # store: consul
      # consul:
      #   host: consul-host:8500
```

**Comment by cabrinha** [comment]
> @cabrinha Have you enabled sharding in your store-gateways? If not, each store gateway will think it's responsible for the entire set of blocks in your S3 bucket.
> 
> The following snippet with a valid KV store config added should work:
> 
> ```yaml
> store_gateway:
>   sharding_enabled: true
>   sharding_ring:
>     kvstore:
>       #      <insert KV store config here>
>       # for example:
>       # store: consul
>       # consul:
>       #   host: consul-host:8500
> ```

Yes:
```yaml
    store_gateway:
      sharding_enabled: true
      sharding_ring:
        kvstore:
          consul:
            host: consul-server.cortex.svc.cluster.local:8500
```

Ownership is around 6% each:
![Screen Shot 2021-04-14 at 9 24 54 AM](https://user-images.githubusercontent.com/775203/114745235-561aed00-9d03-11eb-9b62-c3e72ef7db2a.png)

This is what a restart event looks like in terms of PVC usage:
![Screen Shot 2021-04-14 at 9 24 14 AM](https://user-images.githubusercontent.com/775203/114745243-57e4b080-9d03-11eb-813d-9dd2fc2adc62.png)
