### ISSUE TITLE
Alertmanager configuration load with error

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#4080]
**Describe the bug**
I manage to load alertmanager configuration yaml to Cortex running on GKE via curl command. I encounter 2 issues 
Greatly appreciate any help on this. 

1 - I found the following error in the log that I have no idea what they are 

```
level=warn ts=2021-04-15T01:50:06.693667893Z caller=multitenant.go:490 component=MultiTenantAlertmanager msg="error while synchronizing alertmanager configs" err="proto: wrong wireType = 7 for field Templates"                         │
│ level=debug ts=2021-04-15T01:50:09.168065745Z caller=logging.go:66 traceID=741f72798c13fec9 msg="GET /metrics (200) 5.92689ms"                                                                                                            │
│ level=info ts=2021-04-15T01:50:16.510737959Z caller=multitenant.go:508 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"                                                                               │
│ level=debug ts=2021-04-15T01:50:16.575067049Z caller=nflog.go:336 user="0 Content-Type:application/yaml" component=nflog msg="Running maintenance"                                                                                        │
│ level=debug ts=2021-04-15T01:50:16.575166228Z caller=nflog.go:338 user="0 Content-Type:application/yaml" component=nflog msg="Maintenance done" duration=109.645µs size=0                                                                 │
│ level=error ts=2021-04-15T01:50:16.575191109Z caller=nflog.go:365 user="0 Content-Type:application/yaml" component=nflog msg="Running maintenance failed" err="open data/nflog:0 Content-Type:application/yaml.1c3c21ac7b03829: no such f │
│ ile or directory"
```

2 - When  I try to get the config back using GET api/v1/rules,  it cannot bring back anything even though the logs showed the configuration is there

```
 http http://alertmanager.monitoring.svc.cluster.local/api/v1/alerts X-Scope-OrgID:0 Content-Type:application/yaml
HTTP/1.1 404 Not Found
Content-Length: 30
Content-Type: text/plain; charset=utf-8
Date: Thu, 15 Apr 2021 01:57:01 GMT
X-Content-Type-Options: nosniff

alertmanager config not found
```
The above was run from a pod within the same cluster where alertmanager resides using httpie tool (similar to curl)

**Environment:**
 - Infrastructure: GKE 1.16
 - Deployment tool: K8s deployment files
 - cortex v.1.7.0
 

**Storage Engine**
- [ x ] Blocks
- [ ] Chunks

**Additional info

Alertmanager config file in yaml

```
template_files:
  default_template: |
    {{ define "__alertmanager" }}AlertManager{{ end }}
    {{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver | urlquery }}{{ end }}
alertmanager_config: |
  global:
    resolve_timeout: 10m
  templates:
    - 'default_template'
  route:
    group_wait: 10s
    group_interval: 1m 
    repeat_interval: 10m
    receiver: slack_receiver
    routes:
      - receiver: "slack_receiver"
        match_re:
          severity: critical|warning
        continue: true

  receivers:
  - name: slack_receiver
    slack_configs:
    - send_resolved: true
      api_url: '<>'
      channel: '#test-gw-alert'
      text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
```

K8s alertmanager deployment 

```
        args:
        - -target=alertmanager
        - -log.level=debug
        - -server.http-listen-port=80
        - -alertmanager.storage.retention=240h
        - -alertmanager.configs.poll-interval=10s
        - -alertmanager.configs.url=http://configs.monitoring.svc.cluster.local:80
        - -alertmanager.web.external-url=/api/prom/alertmanager
        - -experimental.alertmanager.enable-api=true
        - -alertmanager.sharding-ring.store=consul
        - -alertmanager.sharding-ring.consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -alertmanager.sharding-enabled=true
        - -alertmanager.sharding-ring.prefix=alertmanagers/
        - -alertmanager.storage.type=gcs
        - -alertmanager.storage.gcs.bucketname=edge-monitor-block-storage
        - -alertmanager.storage.path=data/
        - -experimental.alertmanager.enable-api=true
```
