### ISSUE TITLE
Ring error in Ruler logs even in single pod mode

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#4123]
**Describe the bug**

See this throughout the ruler log even when ruler was deployed as a single instance.  What do I need to do fix this

```
 ruler-7df4c897d4-84trm:level=info ts=2021-04-26T16:57:05.31456259Z caller=fetcher.go:458 org_id=0 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.58701779s cached=2015 returned=2015 partial=0                                                      │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:06.995619294Z caller=client.go:233 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"                 │
│ ruler-7df4c897d4-84trm:level=debug ts=2021-04-26T16:57:07.156214188Z caller=module_service.go:48 msg="module waiting for initialization" module=ruler waiting_for=distributor-service                                                                                                      │
│ ruler-7df4c897d4-84trm:level=debug ts=2021-04-26T16:57:07.156270203Z caller=module_service.go:48 msg="module waiting for initialization" module=ruler waiting_for=memberlist-kv                                                                                                            │
│ ruler-7df4c897d4-84trm:level=info ts=2021-04-26T16:57:07.156284449Z caller=module_service.go:58 msg=initialising module=ruler                                                                                                                                                              │
│ ruler-7df4c897d4-84trm:level=info ts=2021-04-26T16:57:07.156318018Z caller=ruler.go:400 msg="ruler up and running"                                                                                                                                                                         │
│ ruler-7df4c897d4-84trm:level=debug ts=2021-04-26T16:57:07.156333481Z caller=ruler.go:436 msg="syncing rules" reason=initial                                                                                                                                                                │
│ ruler-7df4c897d4-84trm:level=info ts=2021-04-26T16:57:07.156745962Z caller=cortex.go:389 msg="Cortex started"                                                                                                                                                                              │
│ ruler-7df4c897d4-84trm:level=debug ts=2021-04-26T16:57:08.081383287Z caller=logging.go:66 traceID=5262ce9adfa640af msg="GET /metrics (200) 7.85762ms"                                                                                                                                      │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:14.166373526Z caller=client.go:233 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"                 │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:17.724429833Z caller=pool.go:161 msg="error removing stale clients" err="empty ring"                                                                                                                                                │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:23.434239193Z caller=client.go:233 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"                 │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:32.724324043Z caller=pool.go:161 msg="error removing stale clients" err="empty ring"                                                                                                                                                │
│ ruler-7df4c897d4-84trm:level=debug ts=2021-04-26T16:57:38.081120368Z caller=logging.go:66 traceID=7374741e517afa21 msg="GET /metrics (200) 7.967016ms"                                                                                                                                     │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:42.369889362Z caller=client.go:233 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"                 │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:57:47.724396383Z caller=pool.go:161 msg="error removing stale clients" err="empty ring"                                                                                                                                                │
│ ruler-7df4c897d4-84trm:level=error ts=2021-04-26T16:58:02.724365859Z caller=pool.go:161 msg="error removing stale clients" err="empty ring" 

```
Ruler is deployed in K8s as 1 replica - Deployment .yaml is as followed

```
      - name: ruler
        image: quay.io/cortexproject/cortex:v1.7.0
        imagePullPolicy: IfNotPresent
        env:            
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secret/storage.json
        args:
        - -target=ruler
        - -log.level=debug
        - -store.engine=blocks
        - -server.http-listen-port=80
        - -ruler.configs.url=http://configs.monitoring.svc.cluster.local:80
        - -ruler.alertmanager-url=/api/prom/alertmanager
        - -ruler.external.url=/api/prom/ruler
        - -ruler.storage.type=gcs
        - -ruler.storage.gcs.bucketname=<'block storage for ruler and alert'>
        - -ruler.evaluation-interval=10m
        - -ruler.poll-interval=10m
        - -ruler.rule-path=/rules
        - -experimental.ruler.enable-api=true
        - -querier.store-gateway-addresses=store-gateway.monitoring.svc.cluster.local:9095
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=<'ingester block storage'>
        - -blocks-storage.bucket-store.sync-interval=5m
        - -blocks-storage.bucket-store.max-concurrent=10
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.postings-compression-enabled=true
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
        - name: secrets
          mountPath: /etc/secret
          readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: schema-config
        - name: secrets
          secret:
            secretName: storage-key
            items:
            - key: storage.json
              path: storage.json
```

**Environment:**
 - Infrastructure: K8s
 - Deployment tool:  Deployment .yaml using kubctl

**Storage Engine**
- [ X] Blocks
- [ ] Chunks

**Additional Context**

**Comment by mizunos** [comment]
Another note in this - Distributor is deployed as replica of 2 with the following configuration

```
      containers:
      - name: distributor
        image: quay.io/cortexproject/cortex:v1.7.0
        imagePullPolicy: IfNotPresent
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/secret/storage.json      
        args:
        - -target=distributor
        - -log.level=debug
        - -server.http-listen-port=80
        - -store.engine=blocks
        - -consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=<'block storage name'>
        - -distributor.ingestion-rate-limit=60000
        - -distributor.ingestion-burst-size=100000
        - -ingester.max-series-per-metric=100000
```

**Comment by mizunos** [comment]
Something realy went worng with the write path since I upgraded to 1.8.0

I redeploy the distributor with only one replica.  I have this error message in the log.

```
distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.49795822Z caller=main.go:188 msg="Starting Cortex" version="(version=1.8.0, branch=HEAD, revision=51662ea)"                                                                 │
│ distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.498216404Z caller=server.go:229 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"                                                                             │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499003786Z caller=api.go:126 msg="api: registering route" methods=GET path=/config auth=false                                                                              │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499110643Z caller=api.go:126 msg="api: registering route" methods=GET path=/ auth=false                                                                                    │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499136603Z caller=api.go:126 msg="api: registering route" methods=GET path=/debug/fgprof auth=false                                                                        │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499172199Z caller=api.go:126 msg="api: registering route" methods=GET path=/memberlist auth=false                                                                          │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499335552Z caller=api.go:126 msg="api: registering route" methods=GET,POST path=/ingester/ring auth=false                                                                  │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499364785Z caller=api.go:126 msg="api: registering route" methods=GET,POST path=/ring auth=false                                                                           │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.49959416Z caller=api.go:126 msg="api: registering route" methods=POST path=/api/v1/push auth=true                                                                          │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499628277Z caller=api.go:126 msg="api: registering route" methods=GET path=/distributor/all_user_stats auth=false                                                          │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.49965322Z caller=api.go:126 msg="api: registering route" methods=GET path=/distributor/ha_tracker auth=false                                                               │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499682572Z caller=api.go:126 msg="api: registering route" methods=POST path=/api/prom/push auth=true                                                                       │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499714035Z caller=api.go:126 msg="api: registering route" methods=GET path=/all_user_stats auth=false                                                                      │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499741606Z caller=api.go:126 msg="api: registering route" methods=GET path=/ha-tracker auth=false                                                                          │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499765423Z caller=api.go:126 msg="api: registering route" methods=GET path=/services auth=false                                                                            │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499883672Z caller=module_service.go:49 msg="module waiting for initialization" module=distributor-service waiting_for=memberlist-kv                                        │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499914397Z caller=module_service.go:49 msg="module waiting for initialization" module=ring waiting_for=server                                                              │
│ distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.499903356Z caller=module_service.go:59 msg=initialising module=server                                                                                                       │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499916559Z caller=module_service.go:49 msg="module waiting for initialization" module=memberlist-kv waiting_for=server                                                     │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.499964579Z caller=module_service.go:49 msg="module waiting for initialization" module=ring waiting_for=memberlist-kv                                                       │
│ distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.499999058Z caller=module_service.go:59 msg=initialising module=memberlist-kv                                                                                                │
│ distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.500125758Z caller=module_service.go:59 msg=initialising module=ring                                                                                                         │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.500154273Z caller=module_service.go:49 msg="module waiting for initialization" module=distributor-service waiting_for=ring                                                 │
│ distributor-85c4c669-b8dfn:level=debug ts=2021-04-27T05:35:48.500344083Z caller=module_service.go:49 msg="module waiting for initialization" module=distributor-service waiting_for=server                                               │
│ distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.500387524Z caller=module_service.go:59 msg=initialising module=distributor-service                                                                                          │
│ distributor-85c4c669-b8dfn:level=info ts=2021-04-27T05:35:48.500545235Z caller=cortex.go:412 msg="Cortex started"                                                                                                                        │
│ distributor-85c4c669-b8dfn:level=error ts=2021-04-27T05:35:48.506924593Z caller=client.go:234 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0. │
│ 0.1:8500: connect: connection refused"                                                                                                                                                                                                   │
│ distributor-85c4c669-b8dfn:level=warn ts=2021-04-27T05:35:48.674945105Z caller=logging.go:71 traceID=69e357786b208d68 msg="POST /api/prom/push (500) 479.008µs Response: \"DoBatch: InstancesCount <= 0\\n\" ws: false; Connection: clos │
│ e; Content-Encoding: snappy; Content-Length: 6369; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.17.1; X-Forwarded-For: 10.30.8.29; X-Forwarded-Host: pushgateway-integration.arcusaas.com; X-Forwarded-Port: 443; X-Fo │
│ rwarded-Proto: https; X-Prometheus-Remote-Write-Version: 0.1.0; X-Real-Ip: 10.30.8.29; X-Request-Id: 6e01b53293dd7de61c5e26160db417d5; X-Scheme: https; X-Scope-Orgid: 0; "                                                              │
│ distributor-85c4c669-b8dfn:level=warn ts=2021-04-27T05:35:48.763135322Z caller=logging.go:71 traceID=756a6dff567db6a3 msg="POST /api/prom/push (500) 569.175µs Response: \"DoBatch: InstancesCount <= 0\\n\" ws: false; Connection: clos │
│ e; Content-Encoding: snappy; Content-Length: 2511; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.17.1; X-Forwarded-For: 10.30.15.217; X-Forwarded-Host: pushgateway-integration.arcusaas.com; X-Forwarded-Port: 443; X- │
│ Forwarded-Proto: https; X-Prometheus-Remote-Write-Version: 0.1.0; X-Real-Ip: 10.30.15.217; X-Request-Id: 68a6c5b55c036b60babe949829c92889; X-Scheme: https; X-Scope-Orgid: 0; "
```
I can no longer see the ingester leaving and joining the ring.  Ingester Ring configuration show no ingesters at all even though all the ingester pods are running and seem to be doing OK.

Here is  the config of the distributor

```
     containers:
      - name: distributor
        image: quay.io/cortexproject/cortex:v1.8.0
        imagePullPolicy: IfNotPresent
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/secret/storage.json      
        args:
        - -target=distributor
        - -log.level=debug
        - -server.http-listen-port=80
        - -store.engine=blocks
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=<'ingester block-storage'>
        - -distributor.ingestion-rate-limit=60000
        - -distributor.ingestion-burst-size=100000
        - -ingester.max-series-per-metric=100000

```

And the following is the ingester configuration (statefulset of 8)

```
      - name: ingester
          image: quay.io/cortexproject/cortex:v1.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret/storage.json          
          args:
            - -target=ingester
            - -log.level=debug
            - -ingester.join-after=15s
            - -store.engine=blocks
            - -ingester.wal-enabled=true
            - -ingester.wal-dir=/tmp/ingester
            - -ingester.checkpoint-duration=30m
            - -ingester.recover-from-wal=true
            - -ingester.tokens-file-path=/tmp/ingester/
            - -ingester.max-chunk-age=12h
            - -ingester.flush-on-shutdown-with-wal-enabled=true
            - -ingester.chunk-age-jitter=0m
            - -ingester.max-series-per-metric=100000
            - -ingester.spread-flushes=true
            - -distributor.replication-factor=3
            - -consul.hostname=consul.monitoring.svc.cluster.local:8500
            - -blocks-storage.backend=gcs
            - -blocks-storage.gcs.bucket-name=<'block storage name'>
            - -blocks-storage.bucket-store.sync-interval=5m
            - -blocks-storage.bucket-store.max-concurrent=100
            - -blocks-storage.bucket-store.index-cache.backend=memcached
            - -blocks-storage.bucket-store.index-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
            - -blocks-storage.bucket-store.index-cache.postings-compression-enabled=true
            - -blocks-storage.bucket-store.chunks-cache.backend=memcached
            - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
            - -blocks-storage.tsdb.block-ranges-period=2h0m0s
            - -blocks-storage.tsdb.retention-period=6h0m0s    
            - -blocks-storage.tsdb.flush-blocks-on-shutdown=true   
          ports:
          - containerPort: 80

```
Any help is greatly appreciated as my whole enivronment is down at this time.
