### ISSUE TITLE
Cannot get alert Cortex ruler to fire and trigger Cortex Alertmanager notification

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#4155]
I am so close to start using Cortex for my environment.  One the last steps is to have ruler and alert manager to work together for alerting and notifications. I was able to load rules into ruler and alert manager configuration for notification to slack for alert event
I have 1 rule setup for testing but I have not seen any alert generated.  There are no error shown in   ruler log or alertmanager log. Using the same promql expression for the rules cause alert to fires when setting it up using Grafana for alerting so I am know sure where to look for now.

Here is the rule example

```
- name: duplicated_example_processes
    rules:
      - alert: DuplicatedExampleProcessesDetected
        expr: namedprocess_namegroup_num_procs{groupname="example.exe", job="process-exporter"} / on(gateway_id) group_left(nodename) node_uname_info{job="node-exporter"} > 1
        for: 5m
        labels:
          severity: critical
          condition: "Duplicated example.exe Processes"
        annotations:
          title: "From Cortex - Duplicated example.exe Processes Detected."
          description: "Duplicated example.exe Processes Detected for {{ $labels.nodename }}"
          current_value: "{{ $value }}"
```

The log for ruler show no error
```
level=debug ts=2021-05-04T00:05:37.561751566Z caller=rule_store.go:147 msg="loading rule group" key="rules/0/Z2F0ZXdheS1hbGVydHM=/aGlnaF9pb193YWl0" user=0               │
│ level=debug ts=2021-05-04T00:05:40.156916265Z caller=logging.go:66 traceID=48151ed4eb67d668 msg="GET /metrics (200) 9.288538ms"                                          │
│ level=debug ts=2021-05-04T00:06:10.155993563Z caller=logging.go:66 traceID=468df027ef8a697d msg="GET /metrics (200) 8.428179ms"                                          │
│ level=debug ts=2021-05-04T00:06:40.156864992Z caller=logging.go:66 traceID=6a8aa2203cf98cff msg="GET /metrics (200) 9.326593ms"                                          │
│ level=debug ts=2021-05-04T00:07:10.156721992Z caller=logging.go:66 traceID=400a66ed85ab0f63 msg="GET /metrics (200) 9.206659ms"                                          │
│ level=debug ts=2021-05-04T00:07:25.43240661Z caller=fetcher.go:321 org_id=0 component=block.BaseFetcher msg="fetching meta data" concurrency=20                          │
│ level=info ts=2021-05-04T00:07:28.296961255Z caller=fetcher.go:476 org_id=0 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.864629 │
│ level=debug ts=2021-05-04T00:07:40.157353061Z caller=logging.go:66 traceID=14fb2f1f07d10273 msg="GET /metrics (200) 9.658405ms"                                          │
│ level=debug ts=2021-05-04T00:08:10.156036806Z caller=logging.go:66 traceID=6ff4dd1b2921f297 msg="GET /metrics (200) 8.488392ms"
```

The log for alertmanager  show no alert fired

Any help on how I can debug this is greatly appreciate.   Both `alertmanager` and `ruler` configuration is stored in GCS so no local file.

**Expected behavior**
Expect the alert to set off and `alertmanager` to send alert to slack channel.  Same promql expression being used for alerting using grafana cause alert to be sent to slack channel.

**Environment:**
 - Infrastructure: K8s, GKE
 - Deployment tool: K8s deployment yaml

**Storage Engine**
- [ X] Blocks
- [ ] Chunks

**Additional Context**

**Comment by pracucci** [comment]
> The log for alertmanager show no alert fired

Are you running it with debug log level?

**Comment by pracucci** [comment]
> Any help on how I can debug this is greatly appreciate

Have you configured the alertmanager endpoint in the ruler? Could you show the ruler config?

**Comment by mizunos** [comment]
@pracucci  - I currently run all services with log level at debug.  Here is a sample of alertmanager log.  There is only one org/user =0 and one config to send alert to Slack.  I also confirmed that I can get to https://.../api/prom/alertmanager as the web-external url config.

```
level=info ts=2021-05-04T16:09:00.057617859Z caller=multitenant.go:537 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"                                          │
│ level=debug ts=2021-05-04T16:09:00.118767353Z caller=multitenant.go:619 component=MultiTenantAlertmanager msg="adding configurations" num_configs=1                                                  │
│ level=debug ts=2021-05-04T16:09:00.118828695Z caller=multitenant.go:666 component=MultiTenantAlertmanager msg="setting config" user=0                                                                │
│ level=info ts=2021-05-04T16:09:10.057710288Z caller=multitenant.go:537 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"                                          │
│ level=debug ts=2021-05-04T16:09:10.108619019Z caller=multitenant.go:619 component=MultiTenantAlertmanager msg="adding configurations" num_configs=1                                                  │
│ level=debug ts=2021-05-04T16:09:10.108701356Z caller=multitenant.go:666 component=MultiTenantAlertmanager msg="setting config" user=0                                                                │
│ level=info ts=2021-05-04T16:09:20.057582755Z caller=multitenant.go:537 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"                                          │
│ level=debug ts=2021-05-04T16:09:20.152039593Z caller=multitenant.go:619 component=MultiTenantAlertmanager msg="adding configurations" num_configs=1                                                  │
│ level=debug ts=2021-05-04T16:09:20.152199553Z caller=multitenant.go:666 component=MultiTenantAlertmanager msg="setting config" user=0                                                                │
│ level=debug ts=2021-05-04T16:09:23.084234589Z caller=logging.go:66 traceID=df6da47082c3554 msg="GET /metrics (200) 29.212436ms"                                                                      │
│ level=info ts=2021-05-04T16:09:30.057488047Z caller=multitenant.go:537 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"                                          │
│ level=debug ts=2021-05-04T16:09:30.192394577Z caller=multitenant.go:619 component=MultiTenantAlertmanager msg="adding configurations" num_configs=1                                                  │
│ level=debug ts=2021-05-04T16:09:30.19247389Z caller=multitenant.go:666 component=MultiTenantAlertmanager msg="setting config" user=0                                                                 │
│ level=info ts=2021-05-04T16:09:40.057624049Z caller=multitenant.go:537 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"                                          │
│ level=debug ts=2021-05-04T16:09:40.157099657Z caller=multitenant.go:619 component=MultiTenantAlertmanager msg="adding configurations" num_configs=1                                                  │
│ level=debug ts=2021-05-04T16:09:40.157162373Z caller=multitenant.go:666 component=MultiTenantAlertmanager msg="setting config" user=0
```


Here is the configuration for ruler

```
     containers:
      - name: ruler
        image: quay.io/cortexproject/cortex:v1.8.0
        imagePullPolicy: IfNotPresent
        env:            
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secret/storage.json
        args:
        - -target=ruler
        - -log.level=debug
        - -store.engine=blocks
        - -server.http-listen-port=80
        - -ruler.configs.url=http://configs.monitoring.svc.cluster.local:80
        - -ruler.alertmanager-url=/api/prom/alertmanager
        - -ruler.external.url=/api/prom/ruler
        - -ruler.storage.type=gcs
        - -ruler.storage.gcs.bucketname=<config bucket>
        - -ruler.evaluation-interval=10m
        - -ruler.poll-interval=10m
        - -ruler.rule-path=/rules
        - -experimental.ruler.enable-api=true
        - -consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -querier.store-gateway-addresses=store-gateway.monitoring.svc.cluster.local:9095
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=<ingestion bucket>
        - -blocks-storage.bucket-store.sync-interval=5m
        - -blocks-storage.bucket-store.max-concurrent=10
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.postings-compression-enabled=true
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=memcached.monitoring.svc.cluster.local:11211
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
        - name: secrets
          mountPath: /etc/secret
          readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: schema-config
        - name: secrets
          secret:
            secretName: storage-key
            items:
            - key: storage.json
              path: storage.json
```

And here is the `alertmanager` config

```
      containers:
      - name: alertmanager
        image: quay.io/cortexproject/cortex:v1.8.0
        imagePullPolicy: IfNotPresent
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/secret/storage.json      
        args:
        - -target=alertmanager
        - -log.level=debug
        - -server.http-listen-port=80
        - -alertmanager.storage.retention=240h
        - -alertmanager.configs.poll-interval=10s
        - -alertmanager.configs.url=http://configs.monitoring.svc.cluster.local:80
        - -alertmanager.web.external-url=/api/prom/alertmanager
        - -experimental.alertmanager.enable-api=true
        - -alertmanager.storage.type=gcs
        - -alertmanager.storage.gcs.bucketname=<config bucket>
        - -alertmanager.storage.path=data/
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets 
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: storage-key
          items:
          - key: storage.json
            path: storage.json
```
