### ISSUE TITLE
ingester shutdown and horizontal pod autoscaling

### ISSUE THREAD

**Issue by mrmassis** [cortexproject/cortex#4159]
Hi,
Im looking for a method to make a shutdown in series from memory when the kubernete HPA remove an ingester instance. My approach is in pod put:

```
...
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - wget -T 5 http://localhost:8080/shutdown -O -
...
```

And config a grace period to 10min. 

My question : is it enought to continues use the HPA and liveness? My restriction is avoid human intervation.

Tkz
