### ISSUE TITLE
Rules in configmap

### ISSUE THREAD

**Issue by cloudcafetech** [cortexproject/cortex#4166]
New in cortex, can any one help me to setup rules in configmap?

**Comment by pracucci** [comment]
This is quite a generic question. The ruler supports different storage backends:
https://cortexmetrics.io/docs/configuration/configuration-file/#ruler_storage_config

If you use the `local` backend, then you can configure your rules in a configmap and get them loaded by the ruler. The configmap should contain the rule files as you would do in Prometheus, mount them into a directory within the ruler pod and then configure the local storage directory to the path where these rules files are mounted in pod:

```
local:
  # Directory to scan for rules
  # CLI flag: -ruler-storage.local.directory
  [directory: <string> | default = ""]
```

**Comment by cloudcafetech** [comment]
Will it work as below (took it from Loki)

```
ruler:      storage:        type: local        local:          directory: /etc/loki/rules      ring:        kvstore:          store: memberlist      rule_path: /temp/loki/rules-temp      alertmanager_url: http://kubemon-alertmanager.monitoring.svc.cluster.local:9093      external_url: https://alertmanager.xx      enable_api: true      enable_alertmanager_v2: true
```

**Comment by cloudcafetech** [comment]
Edited ```ruler-dep.yaml``` as below ...

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ruler
  template:
    metadata:
      labels:
        name: ruler
    spec:
      containers:
      - name: ruler
        image: quay.io/cortexproject/cortex:v1.8.1
        imagePullPolicy: IfNotPresent
        args:
        - -target=ruler
        - -log.level=debug
        - -server.http-listen-port=80
        - -ruler.configs.url=http://configs.monitoring.svc.cluster.local:80
        - -ruler.alertmanager-url=http://alertmanager.monitoring.svc.cluster.local/alertmanager/
        - -ruler-storage.backend=local
        - -ruler-storage.local.directory=/etc/cortex/rules
        - -consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -s3.url=s3://admin:admin2675@172.31.46.72:9000/monitoring
        - -s3.force-path-style=true
        - -dynamodb.url=dynamodb://user:pass@dynamodb.monitoring.svc.cluster.local:8000
        - -schema-config-file=/etc/cortex/schema.yaml
        - -store.chunks-cache.memcached.hostname=memcached.monitoring.svc.cluster.local
        - -store.chunks-cache.memcached.timeout=100ms
        - -store.chunks-cache.memcached.service=memcached
        - -distributor.replication-factor=1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/cortex
          name: config
        - mountPath: /etc/cortex/rules
          name: alert
        - mountPath: /temp
          name: temp
      volumes:
        - configMap:
            name: schema-config
          name: config
        - configMap:
            name: cortex-alert-config
          name: alert
        - emptyDir: {}
          name: temp
```

Getting below error.

```
[root@ip-172-31-46-72 k8s-cortex]# oc get po
NAME                                          READY   STATUS             RESTARTS   AGE
alertmanager-6cb94db65b-dcn69                 1/1     Running            2          14m
configs-5fdbcd7dcf-d5x66                      1/1     Running            0          14m
configs-db-7577d48bd6-9dmsl                   1/1     Running            0          14m
consul-7645b66b9d-7khg8                       1/1     Running            0          14m
distributor-84885dd984-bhbkz                  1/1     Running            0          14m
dynamodb-5fb595f677-mjwht                     1/1     Running            0          14m
ingester-5c665f95cc-sxm8b                     1/1     Running            0          14m
kubemon-grafana-0                             1/1     Running            0          14m
kubemon-kube-state-metrics-6bc8b9946b-c57md   2/2     Running            0          14m
kubemon-node-exporter-xr9tx                   1/1     Running            0          14m
kubemon-prometheus-0                          1/1     Running            0          14m
memcached-59b9c6746-fsrhr                     1/1     Running            0          14m
nginx-6445958699-5qn7t                        1/1     Running            0          14m
querier-65b865dc5c-rhsxg                      1/1     Running            0          14m
query-frontend-6f7b494cbb-vll7t               1/1     Running            0          14m
retrieval-7fc5d79746-9fdv7                    1/1     Running            0          14m
ruler-87776dd4f-l9qn7                         0/1     CrashLoopBackOff   5          3m51s
table-manager-f9bb4595-8vdpc                  1/1     Running            0          14m


[root@ip-172-31-46-72 k8s-cortex]# oc logs -f ruler-87776dd4f-l9qn7
flag provided but not defined: -ruler-storage.local.directory
Run with -help to get list of available parameters

```
