### ISSUE TITLE
Problem with alertmanager

### ISSUE THREAD

**Issue by mrmassis** [cortexproject/cortex#4232]
After upgrade de Cortex from v1.8.1 to v1.9.0 the Alertmanager stop to woker. When I start in microservice mode the alertmanager component broken and show the follown message in log.

```
flag provided but not defined: -cluster.peer
Run with -help to get list of available parameters
```

the command line inside the pod:
```
    -target=alertmanager
      -config.file=/etc/cortex/cortex.yaml
      -alertmanager.configs.url=http://storage-cortex-configs.mon.svc.cluster.local:8080
      -cluster.peer=storage-cortex-alertmanager-0.storage-cortex-alertmanager-headless.mon.svc.cluster.local:9094
      -cluster.peer=storage-cortex-alertmanager-1.storage-cortex-alertmanager-headless.mon.svc.cluster.local:9094
      -cluster.peer=storage-cortex-alertmanager-2.storage-cortex-alertmanager-headless.mon.svc.cluster.local:9094
```

my alertmanager config:

``` 
alertmanager:
  cluster:
    listen_address: 0.0.0.0:9094
    peers: storage-cortex-alertmanager-headless.mon.svc
  data_dir: /data/alertmanager
  enable_api: true
  external_url: /alertmanager
  persist_interval: 15m
  retention: 120h
  sharding_enabled: true
  sharding_ring:
    kvstore:
      prefix: alertmanager/
      store: memberlist
alertmanager_storage:
  backend: s3
  s3:
    bucket_name: YYYY
    endpoint: XXXX
```

Cortex v1.9.0, i used the helm to deployment
