### ISSUE TITLE
What's the difference between storage_config and blocks_storage_config?

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#4233]
I'm baffled by the discrepancies in configuration. There's:
```yaml
# The storage_config configures where Cortex stores the data (chunks storage
# engine).
[storage: <storage_config>]
```
But it contains keys like `aws.s3` and `aws.bucketnames`, so the comment seems incorrect.

There's:
```yaml
# The blocks_storage_config configures the blocks storage.
[blocks_storage: <blocks_storage_config>]
```
Which also contains keys like `s3.endpoint` and `s3.bucket_name`, so it kinda duplicates what's in `storage_config`.

Are those two exclusive? Should the be configured together? Do they configure the same thing? I don't get it.

**Comment by jakubgs** [comment]
The documentation for Blocks Storage says to configure `storage`:
```yaml
storage:
  # The storage engine to use. Use "blocks" for the blocks storage.
  # CLI flag: -store.engine
  engine: blocks
```
https://cortexmetrics.io/docs/blocks-storage/#configuration

Does that mean that `blocks_storage` should be ignored and not configured?
