### ISSUE TITLE
Ruler module does not get initialized in 1.9 single process

### ISSUE THREAD

**Issue by zaharidichev** [cortexproject/cortex#4239]
**Describe the bug**
While migrating from 1.7 to 1.9 I have observed that the ruler component does not run when trying to run cortex in a single process under docker-compose. 

**To Reproduce**
We recently transitioned from cortex 1.7 to 1.9 in our docker compose env where we were running it as a single process. We were running pretty much all services including the alertmanager. Curently with the very same targets, we are not able to get the ruler up and running. So at the moment routes such as `/api/v1/rules/{ns} ` are not present. Not sure why this is happening but I remember we had a [similar problem](https://github.com/cortexproject/cortex/issues/3041#issuecomment-801997535) with alertmanager on 1.7. (therefore having to explicitly specify it). This is how our cortex service looks like in docker-compose:

```
cortex:
    image: quay.io/cortexproject/cortex:v1.9.0
    command:
    - "--config.file=/etc/cortex/cortex.yml"
    - "--target=all,alertmanager"
    ports:
    - "9009:9009"
    volumes:
    - ./config/dev-cortex.yml:/etc/cortex/cortex.yml
    - ./target/cortex-rules:/tmp/cortex-rules
    - ./target/alertmanager-configs:/tmp/alertmanager-configs
    environment:
    - "JAEGER_AGENT_HOST=jaeger"
    - "JAEGER_AGENT_PORT=6831"
    - "JAEGER_TAGS=app=cortex"
    - "JAEGER_SAMPLER_TYPE=const"
    - "JAEGER_SAMPLER_PARAM=1"
```

The services running with this config on 1.9:

```
alertmanager
distributor-service 	
ingester-service 	
memberlist-kv 	
querier
query-frontend
query-frontend-tripperware
ring	
server
store-gateway
store-queryable
```

The ones running on 1.7:
```
alertmanager
distributor-service
ingester-service
memberlist-kv
querier
query-frontend
query-frontend-tripperware
ring
ruler
server
store-gateway
store-queryable
```

So I wonder, why is the ruler  not running on 1.9. Am I missing something here?

**Comment by zaharidichev** [comment]
I think I found the problem . The `storage` section of the ruler config was deprecated and hence we decided to transition to `ruler_storage`: 

```yaml
ruler:
  enable_api: true
  enable_sharding: false
  alertmanager_url: "http://cortex:9009/api/prom/alertmanager"

ruler_storage:
  backend: local
  local:
    directory: /tmp/cortex-rules/orgs
```

However there is this piece of code that requires the storage section to be configured in singly binary mode to init the ruler-storage module which is required by the ruler:  https://github.com/cortexproject/cortex/blob/master/pkg/cortex/modules.go#L640

Either I do not fully understand this, or this needs to check whether any of the configs are set and the way it is written is buggy.
