### ISSUE TITLE
Use prometheus alertmanager 

### ISSUE THREAD

**Issue by cloudcafetech** [cortexproject/cortex#4266]
We are running prometheus alertmanager and deployed cortex as manifest from k8s folder.

Please help me to modify ruler (ruler-dep.yaml) to use prometheus alertmanager.

Thanks in advance.

**Comment by gotjosh** [comment]
Can you please try searching/using the discussions? I believe this has been answered a couple of times there - given this is not really an issue I would say we should close this @pracucci.

**Comment by cloudcafetech** [comment]
can you please provide me some pointers.

**Comment by mizunos** [comment]
Cortex Alertmanager take care of notification based on alerts generated by ruler.  I use grafana `cortextool` to manage both - The basic workflow is as followed
1 - create rules in the form of a yaml file 
2 - lint the rules 
3 - load the rules
4 - create alertmanager configuration in the form of a yaml file
5 - load alertmanager configuration

here is the link to alertmanager configuration guide 
https://cortexmetrics.io/docs/guides/alertmanager-configuration/
Link to install cortextool

https://github.com/grafana/cortex-tools/releases

sample of rule.yml file

```
namespace: "gateway-alerts"
groups:
  - name: "gateway_container_restart_count"
    rules:
      - alert: GatewayContainerRestartCount10
        expr: kube_pod_container_status_restarts_total{namespace="default", pod="gateway-0", container="gateway", job="kubernetes-state-metrics"} / on(gateway_id) group_left(node) kube_node_labels{k8s_app="kube-state-metrics"} > 10
        for: 1m
        labels:
          severity: critical
          condition: "Gateway Restarts > 10"
        annotations:
          title: "High Gateway Container Restart Count Detected."
          description: "Gateway Container Restart Count > 10 for {{ $labels.node }}"
          current_value: "{{ $value }}"
  - name: high_io_wait
    rules:
      - alert: "I/O Wait (avg) > 50%"
        expr: avg by (gateway_id, nodename) (irate(node_cpu_seconds_total{mode="iowait",job="node-exporter"}[5m])) * 100 / on(gateway_id) group_left(nodename) node_uname_info{job="node-exporter"} > 50
        for: 5m
        labels:
          severity: critical
          condition: "I/O Wait (avg) > 50"
        annotations:
          title: "From Cortex - High I/O Wait (avg) Detected."
          description: "High I/O Wait (avg) Detected for {{ $labels.nodename }}"
          current_value: "{{ $value }}"
```

sample of alertmanager yaml notifiction to slack file
```
global:
  resolve_timeout: 10m
  slack_api_url: <redacted slack webhook>
route:
  group_wait: 10s
  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group
  group_interval: 1m 
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 10m
  receiver: slack_receiver
  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: slack_receiver
      match_re:
        severity: critical|warning
      continue: true
receivers:
- name: slack_receiver
  slack_configs:
  - send_resolved: true
    channel: '#test-cortex-alert'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if .CommonLabels.alertname }}{{ .CommonLabels.alertname }}{{ else }}Multiple Alerts Open{{ end }}{{ if .CommonLabels.node }} for {{ .CommonLabels.node }}{{ else if .CommonLabels.nodename }} for {{ .CommonLabels.nodename }}{{ end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}
              *Description:* {{ .Annotations.description }}
                 • *Environment:* {{ if .Labels.environment }}`{{ .Labels.environment }}`{{ else }}`N/A`{{ end }}
                 • *Hostname:* {{ if .Labels.node }}`{{ .Labels.node }}`{{ else if .Labels.nodename }}`{{ .Labels.nodename }}`{{ else }}`N/A`{{ end }}
                 • *Gateway guid:* {{ if .Labels.gateway_id }}`{{ .Labels.gateway_id }}`{{ else }}`N/A`{{ end }}
                 • *Condition:* {{ if .Labels.condition }}`{{ .Labels.condition }}`{{ else }}`N/A`{{ end }}
                 • *Current value:* {{ if .Annotations.current_value }}`{{ .Annotations.current_value }}`{{ else }}`N/A`{{ end }}
                 • *Opened at:* {{ if .StartsAt }}`{{ .StartsAt }}`{{ else }}`N/A`{{ end }}
                 • *Closed at:* {{ if eq .Status "resolved" }}`{{ .EndsAt }}`{{ else }}`Unresolved, alert still active.`{{ end }}
              {{ end }}
```

Ruler need to know where to send alert to so the parameter of ruler.alertmanager-url must point to the right endpoint.  Tha's the part that cause the most of my issues once I figure out how to get rules and notification in place.  Hope this help
