### ISSUE TITLE
Problems with alertmanager in v1.9

### ISSUE THREAD

**Issue by mrmassis** [cortexproject/cortex#4280]
Hi,
im trying start the Cortex 1.9 in production. So, a lot of the changes ocurred in alertmanager and now my alertmanage dont work.

My configs:
```
alertmanager:
    data_dir: /data/alertmanager
    retention: 120h
    external_url: http://spi-mon-storage-cortex-alertmanager.mon.svc.infra.(...)/alertmanager
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: memberlist
        prefix: alertmanager/
    cluster:
      listen_address: "0.0.0.0:9094"
      peers: spi-mon-storage-cortex-alertmanager-headless
    enable_api: true
    persist_interval: 15m
  alertmanager_storage:
    backend: s3
    configdb:
      configs_api_url: http://spi-mon-storage-cortex-configs.mon.svc.infra.(...):8080
    s3:
      endpoint: s3.i02.estaleiro.serpro.gov.br
      bucket_name: prod-cortex-alertmanager
```

and i receive the follow error:
```
level=debug ts=2021-06-14T20:32:15.336412165Z caller=tcp_transport.go:388 msg=FinalAdvertiseAddr advertiseAddr=10.46.16.64 advertisePort=7946
level=debug ts=2021-06-14T20:32:15.336520368Z caller=module_service.go:49 msg="module waiting for initialization" module=memberlist-kv waiting_for=server
level=info ts=2021-06-14T20:32:15.336640653Z caller=module_service.go:59 msg=initialising module=memberlist-kv
level=debug ts=2021-06-14T20:32:15.336733158Z caller=module_service.go:49 msg="module waiting for initialization" module=alertmanager waiting_for=server
level=info ts=2021-06-14T20:32:15.336741553Z caller=module_service.go:59 msg=initialising module=alertmanager
level=debug ts=2021-06-14T20:32:15.336773087Z caller=tcp_transport.go:388 msg=FinalAdvertiseAddr advertiseAddr=10.46.16.64 advertisePort=7946
level=info ts=2021-06-14T20:32:15.337006063Z caller=basic_lifecycler.go:252 component=MultiTenantAlertmanager msg="instance not found in the ring" instance=spi-mon-storage-cortex-alertmanager-0 ring=alertmanager
level=info ts=2021-06-14T20:32:15.337023117Z caller=ring.go:271 msg="ring doesn't exist in KV store yet"
level=info ts=2021-06-14T20:32:15.33716201Z caller=multitenant.go:456 component=MultiTenantAlertmanager waitinguntilalertmanagerisJOININGinthering=(MISSING)
ts=2021-06-14T20:32:15.33970619Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve spi-mon-storage-cortex-ingester-headless.mon.svc: lookup spi-mon-storage-cortex-ingester-headless.mon.svc on 169.254.25.10:53: no such host"
level=debug ts=2021-06-14T20:32:15.339741986Z caller=memberlist_client.go:500 msg="attempt to join memberlist cluster failed" retries=0 err="1 error occurred:\n\t* Failed to resolve spi-mon-storage-cortex-ingester-headless.mon.svc: lookup spi-mon-storage-cortex-ingester-headless.mon.svc on 169.254.25.10:53: no such host\n\n"
level=info ts=2021-06-14T20:32:15.462888318Z caller=multitenant.go:460 component=MultiTenantAlertmanager msg="alertmanager is JOINING in the ring"
level=info ts=2021-06-14T20:32:15.462929993Z caller=multitenant.go:640 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"
level=info ts=2021-06-14T20:32:15.469613193Z caller=basic_lifecycler.go:197 msg="ring lifecycler is shutting down" ring=alertmanager
level=debug ts=2021-06-14T20:32:15.469711723Z caller=memberlist_client.go:808 msg="CAS attempt failed" err="no change detected" retry=true
level=debug ts=2021-06-14T20:32:16.470469565Z caller=broadcast.go:48 msg="Invalidating forwarded broadcast" key=alertmanager/alertmanager version=2 oldVersion=1 content=[spi-mon-storage-cortex-alertmanager-0] oldContent=[spi-mon-storage-cortex-alertmanager-0]
level=info ts=2021-06-14T20:32:16.470531072Z caller=basic_lifecycler.go:363 component=MultiTenantAlertmanager msg="unregistering instance from ring" ring=alertmanager
level=debug ts=2021-06-14T20:32:16.470582632Z caller=broadcast.go:48 msg="Invalidating forwarded broadcast" key=alertmanager/alertmanager version=3 oldVersion=2 content=[spi-mon-storage-cortex-alertmanager-0] oldContent=[spi-mon-storage-cortex-alertmanager-0]
level=info ts=2021-06-14T20:32:16.470593357Z caller=basic_lifecycler.go:234 component=MultiTenantAlertmanager msg="instance removed from the ring" ring=alertmanager
level=error ts=2021-06-14T20:32:16.470699236Z caller=cortex.go:426 msg="module failed" module=alertmanager err="invalid service state: Failed, expected: Running, failure: failed to list users with alertmanager configuration: Get \"http://spi-mon-storage-cortex-configs.mon.svc.cluster.local:8080/private/api/prom/configs/alertmanager\": dial tcp: lookup spi-mon-storage-cortex-configs.mon.svc.cluster.local on 169.254.25.10:53: no such host"
level=debug ts=2021-06-14T20:32:16.470736099Z caller=module_service.go:104 msg="module waiting for" module=memberlist-kv waiting_for=alertmanager
level=debug ts=2021-06-14T20:32:16.470742018Z caller=module_service.go:81 msg=stopping module=server
level=debug ts=2021-06-14T20:32:16.470753676Z caller=module_service.go:81 msg=stopping module=memberlist-kv
ts=2021-06-14T20:32:16.472754143Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with:  10.46.21.61:7946"
level=info ts=2021-06-14T20:32:16.474365049Z caller=memberlist_client.go:521 msg="joined memberlist cluster" reached_nodes=1
level=info ts=2021-06-14T20:32:16.474387975Z caller=memberlist_client.go:558 msg="leaving memberlist cluster"
level=info ts=2021-06-14T20:32:16.938762363Z caller=module_service.go:91 msg="module stopped" module=memberlist-kv
level=info ts=2021-06-14T20:32:16.940323887Z caller=server_service.go:50 msg="server stopped"
level=info ts=2021-06-14T20:32:16.94042225Z caller=module_service.go:91 msg="module stopped" module=server
level=info ts=2021-06-14T20:32:16.940477699Z caller=cortex.go:415 msg="Cortex stopped"
level=error ts=2021-06-14T20:32:16.940603829Z caller=log.go:106 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:461\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:190\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
``` 

whats  wrong?

**Comment by pracucci** [comment]
You got this error:

> level=error ts=2021-06-14T20:32:16.470699236Z caller=cortex.go:426 msg="module failed" module=alertmanager err="invalid service state: Failed, expected: Running, failure: failed to list users with alertmanager configuration: Get \"http://spi-mon-storage-cortex-configs.mon.svc.cluster.local:8080/private/api/prom/configs/alertmanager\": dial tcp: lookup spi-mon-storage-cortex-configs.mon.svc.cluster.local on 169.254.25.10:53: no such host"

Looking at your config:
```
  alertmanager_storage:
    backend: s3
    configdb:
      configs_api_url: http://spi-mon-storage-cortex-configs.mon.svc.infra.(...):8080
    s3:
      endpoint: s3.i02.estaleiro.serpro.gov.br
      bucket_name: prod-cortex-alertmanager
```

configdb and S3 are mutually exclusive. You should remove the `configdb` entry from the config if you want to use S3 (suggested) to store your config.
