### ISSUE TITLE
`/ruler/rule_groups` returns YAML with extra fields

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#4283]
**Describe the bug**
Wanting to download all available rule groups, I used `/ruler/rule_groups` endpoint. Unfortunately, it's output has has lot of extra fields coming from internal YAML structures:

```yaml
"tenant12345":
  metamonitoring:
  - name: alertmanager.rules
    rules:
    - alert:
        kind: 8
        style: 0
        tag: '!!str'
        value: AlertmanagerFailedReload
        anchor: ""
        alias: null
        content: []
        headcomment: ""
        linecomment: ""
        footcomment: ""
        line: 0
        column: 0
      expr:
        kind: 8
        style: 0
        tag: '!!str'
        value: max_over_time(alertmanager_config_last_reload_successful{job="default/alertmanager"}[5m])
          == 0
        anchor: ""
        alias: null
        content: []
        headcomment: ""
        linecomment: ""
        footcomment: ""
        line: 0
        column: 0
      for: 10m
      labels:
        severity: critical
      annotations:
        description: Configuration has failed to load for {{$labels.instance}} in
          {{$labels.cluster}}.
        summary: Reloading an Alertmanager configuration has failed.
...
```

**To Reproduce**
1. Start Cortex https://github.com/cortexproject/cortex/tree/5e508061891aa5637946c0c56fa431960c838346
2. Perform Operations(Read/Write/Others): run "curl http://<ruler>/ruler/rule_groups".

**Expected behavior**
I expected to receive rule groups without extra fields like `anchor`, `alias`, `kind`, etc.

**Storage Engine**
- [x] Blocks
- [ ] Chunks
