### ISSUE TITLE
Not uploading data to s3 (MINIO)

### ISSUE THREAD

**Issue by cloudcafetech** [cortexproject/cortex#4301]
Installed as a distributed mode with Minio (s3) bucket (monitoring).

After a long wait (26 min) data not uploaded in Minio (s3) bucket (monitoring). ```No such error in ingestor```

- Bucket

![image](https://user-images.githubusercontent.com/68260844/122702200-808da700-d26c-11eb-9bc5-823a03e918db.png)

![image](https://user-images.githubusercontent.com/68260844/122702273-a61ab080-d26c-11eb-9e28-7ab45e4fecd1.png)

- Config

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex
  namespace: monitoring
data:
  cortex.yaml: |-
    api:
      prometheus_http_prefix: /prometheus
      response_compression_enabled: true
    auth_enabled: false
    store_gateway:
      sharding_enabled: true
      sharding_ring:
        kvstore:
          consul:
            consistent_reads: true
            host: consul:8500
            http_client_timeout: 20s
    blocks_storage:
      tsdb:
        dir: /data/cortex/tsdb
      bucket_store:
        sync_dir: /data/cortex/tsdb-sync
      backend: s3
      s3:
        bucket_name: monitoring
        endpoint: 172.31.44.205:9000
        access_key_id: admin
        secret_access_key: admin2675
        insecure: true
    chunk_store:
      chunk_cache_config:
        memcached:
          expiration: 1h
        memcached_client:
          timeout: 1s
    distributor:
      pool:
        health_check_ingesters: true
      shard_by_all_labels: true
    frontend:
      log_queries_longer_than: 10s
    ingester:
      lifecycler:
        final_sleep: 0s
        join_after: 0s
        num_tokens: 512
        ring:
          kvstore:
            consul:
              consistent_reads: true
              host: consul:8500
              http_client_timeout: 20s
            prefix: collectors/
            store: consul
          replication_factor: 3
      max_transfer_retries: 0
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      enforce_metric_name: false
      max_query_lookback: 0s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      bind_port: 7946
      join_members: []
    querier:
      active_query_tracker_dir: /data/cortex/querier
      query_ingesters_within: 12h
      store_gateway_addresses: dns+cortex-store-gateway.monitoring:9095
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          memcached:
            expiration: 1h
          memcached_client:
            timeout: 1s
      split_queries_by_interval: 24h
    # https://github.com/cortexproject/cortex/issues/3401#issuecomment-864033508
    ruler:
      alertmanager_url: http://alertmanager:9093/
      enable_alertmanager_discovery: false
      enable_alertmanager_v2: true
      enable_api: true
      external_url: https://alerts.example.org/
      rule_path: /rules
      storage:
        local:
          directory: /etc/cortex/rules/fake
        type: local
    schema:
      configs: []
    server:
      grpc_listen_port: 9095
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      http_listen_port: 8080
    storage:
      aws:
        s3: s3://admin:admin2675@172.31.44.205:9000/monitoing
        s3forcepathstyle: true
      engine: blocks
      index_queries_cache_config:
        memcached:
          expiration: 1
        memcached_client:
          timeout: 1s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
```

Running POD,SVC

```
[root@ip-172-31-44-205 monitoring]# oc get po,svc
NAME                                            READY   STATUS    RESTARTS   AGE
pod/alertmanager-0                              1/1     Running   0          26m
pod/configs-56869844c9-hcsj2                    1/1     Running   0          26m
pod/configs-db-7577d48bd6-vdw74                 1/1     Running   0          26m
pod/consul-7645b66b9d-5b5pv                     1/1     Running   0          26m
pod/cortex-compactor-0                          1/1     Running   0          26m
pod/cortex-distributor-74b9c76877-9mjqd         1/1     Running   2          26m
pod/cortex-distributor-74b9c76877-bwwk6         1/1     Running   2          26m
pod/cortex-ingester-7bb89b8846-2pccx            1/1     Running   0          26m
pod/cortex-ingester-7bb89b8846-mlvpx            1/1     Running   0          26m
pod/cortex-ingester-7bb89b8846-s656c            1/1     Running   0          26m
pod/cortex-nginx-7d76c864-hnhzp                 1/1     Running   0          26m
pod/cortex-querier-775679b568-cqznn             1/1     Running   2          26m
pod/cortex-query-frontend-686f8b55c-9x4dn       1/1     Running   0          26m
pod/cortex-ruler-75b9887876-wwz66               1/1     Running   2          26m
pod/cortex-store-gateway-0                      1/1     Running   2          26m
pod/cortex-table-manager-5cb5f6bd89-8wt8k       1/1     Running   0          26m
pod/grafana-0                                   1/1     Running   0          26m
pod/grafana-agent-deployment-85fdd48954-47bsq   1/1     Running   0          24m
pod/grafana-agent-dh26q                         1/1     Running   0          24m
pod/grafana-agent-rdblw                         1/1     Running   0          24m
pod/kube-state-metrics-5fbbf95c46-67mgp         2/2     Running   0          75m
pod/memcached-59b9c6746-ghj95                   1/1     Running   0          26m
pod/node-exporter-4wkzr                         1/1     Running   0          75m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
service/alertmanager                     NodePort    10.96.94.138    <none>        9093:30093/TCP       26m
service/alertmanager-operated            ClusterIP   None            <none>        6783/TCP,9093/TCP    26m
service/configs                          ClusterIP   10.96.160.42    <none>        80/TCP               26m
service/configs-db                       ClusterIP   10.96.190.211   <none>        5432/TCP             26m
service/consul                           ClusterIP   10.96.95.47     <none>        8500/TCP             26m
service/cortex-compactor                 ClusterIP   10.96.47.18     <none>        8080/TCP             26m
service/cortex-distributor               ClusterIP   10.96.16.211    <none>        8080/TCP             26m
service/cortex-distributor-headless      ClusterIP   None            <none>        8080/TCP,9095/TCP    26m
service/cortex-ingester-headless         ClusterIP   None            <none>        8080/TCP             26m
service/cortex-memberlist                ClusterIP   None            <none>        7946/TCP             26m
service/cortex-nginx                     ClusterIP   10.96.17.70     <none>        80/TCP               26m
service/cortex-querier                   ClusterIP   10.96.20.78     <none>        8080/TCP             26m
service/cortex-query-frontend            ClusterIP   10.96.126.27    <none>        8080/TCP,9095/TCP    26m
service/cortex-query-frontend-headless   ClusterIP   None            <none>        8080/TCP,9095/TCP    26m
service/cortex-ruler                     ClusterIP   10.96.165.231   <none>        8080/TCP             26m
service/cortex-store-gateway             ClusterIP   None            <none>        8080/TCP,9095/TCP    26m
service/cortex-table-manager             ClusterIP   10.96.200.70    <none>        8080/TCP             26m
service/grafana                          NodePort    10.96.168.255   <none>        80:30000/TCP         26m
service/kube-state-metrics               ClusterIP   10.96.80.251    <none>        8080/TCP,8081/TCP    75m
service/memcached                        ClusterIP   None            <none>        11211/TCP,9150/TCP   26m
```

Am I missing any config ?
