### ISSUE TITLE
Higher CPU usage of one ingester

### ISSUE THREAD

**Issue by sreis** [cortexproject/cortex#4329]
**Describe the bug**

In the screenshot below, at around 7h40m ingester-0 started using more CPU than expected and it lasted for a few hours.

![Screenshot from 2021-06-30 11-13-28](https://user-images.githubusercontent.com/495294/123953455-c518f100-d996-11eb-8702-51bdfdee0b41.png)

There's higher latency writing to S3 during this timeframe but I'm not sure if this is a symptom or a cause of the weird behavior.

![Screenshot from 2021-06-30 11-33-18](https://user-images.githubusercontent.com/495294/123953720-15904e80-d997-11eb-9e29-8031f913d6f5.png)

**To Reproduce**
1. Start Cortex (SHA or version): cortexproject/cortex:master-fde0a62
2. Perform Operations(Read/Write/Others): Ingestion

Relevant config sections:

```
ingester:
  active_series_metrics_enabled: true
  lifecycler:
    join_after: 30s
    num_tokens: 512
    observe_period: 30s
    ring:
      kvstore:
        store: memberlist
limits:
  accept_ha_samples: true
  compactor_blocks_retention_period: 61d
  ha_cluster_label: prometheus
  ha_replica_label: prometheus_replica
  ingestion_burst_size: 200000
  ingestion_rate: 100000
  max_global_series_per_user: 10000000
  max_label_names_per_series: 45
  ruler_tenant_shard_size: 3
server:
  grpc_server_max_recv_msg_size: 41943040
  grpc_server_max_send_msg_size: 41943040
storage:
  engine: blocks
```

**Expected behavior**
There was no change in ingestion traffic, so I would expect ingester CPU usage to remain stable.

Screenshot showing ingestion traffic during the timeframe:

![screenshot](https://user-images.githubusercontent.com/495294/123954735-43c25e00-d998-11eb-8727-fe7dc8ada68a.png)

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]: Kubernetes
 - Deployment tool: [e.g., helm, jsonnet]: Custom

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

* The ingester pods don't have any CPU limits set.

* I'm attaching heap, goroutine, and CPU pprof profiles from ingester-0 during and after the high CPU usage and from ingester-1 during the high CPU usage.

[ingester-0.pprof.cortex.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/cortexproject/cortex/files/6740439/ingester-0.pprof.cortex.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[ingester-0.pprof.cortex.goroutine.001.pb.gz](https://github.com/cortexproject/cortex/files/6740440/ingester-0.pprof.cortex.goroutine.001.pb.gz)
[ingester-0.pprof.cortex.samples.cpu.001.pb.gz](https://github.com/cortexproject/cortex/files/6740441/ingester-0.pprof.cortex.samples.cpu.001.pb.gz)
[ingester-0-after.pprof.cortex.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/cortexproject/cortex/files/6740442/ingester-0-after.pprof.cortex.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[ingester-0-after.pprof.cortex.goroutine.001.pb.gz](https://github.com/cortexproject/cortex/files/6740443/ingester-0-after.pprof.cortex.goroutine.001.pb.gz)
[ingester-0-after.pprof.cortex.samples.cpu.001.pb.gz](https://github.com/cortexproject/cortex/files/6740444/ingester-0-after.pprof.cortex.samples.cpu.001.pb.gz)
[ingester-1.pprof.cortex.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/cortexproject/cortex/files/6740445/ingester-1.pprof.cortex.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[ingester-1.pprof.cortex.goroutine.001.pb.gz](https://github.com/cortexproject/cortex/files/6740446/ingester-1.pprof.cortex.goroutine.001.pb.gz)
[ingester-1.pprof.cortex.samples.cpu.001.pb.gz](https://github.com/cortexproject/cortex/files/6740447/ingester-1.pprof.cortex.samples.cpu.001.pb.gz)
