### ISSUE TITLE
TCPTransport: unknown message type

### ISSUE THREAD

**Issue by phin1x** [cortexproject/cortex#4338]
We deployed cortex v1.9.0 in our kubernetes cluster with the latest helm chart. It works fine, but periodically we are getting this error message in the ingester and distributor log:

```
caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
```

This is my config:

```
config:
  auth_enabled: false

  api:
    prometheus_http_prefix: '/prometheus'
    response_compression_enabled: true

  ingester:
    lifecycler:
      ring:
        replication_factor: 3
        kvstore:
          store: memberlist
          prefix: 'collectors/'

  limits:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_query_lookback: 90d
    max_series_per_metric: 0
    ingestion_rate: 100000
    ingestion_burst_size: 150000

  storage:
    engine: blocks

  blocks_storage:
    backend: s3
    s3:
      bucket_name: ${S3_BUCKET_NAME}
      endpoint: ${S3_ENDPOINT}
      access_key_id: "${S3_ACCESS_KEY}"
      secret_access_key: "${S3_SECRET_KEY}"
      insecure: false

  distributor:
    shard_by_all_labels: true
    pool:
      health_check_ingesters: true
    ha_tracker:
      enable_ha_tracker: false
    ring:
      kvstore:
        store: memberlist

  memberlist:
    bind_port: 7946
    join_members:
      - cortex-memberlist

  querier:
    active_query_tracker_dir: /data/cortex/querier
    query_ingesters_within: 12h
    store_gateway_addresses: _grpc._tcp.cortex-store-gateway-headless:9095

  query_range:
    split_queries_by_interval: 24h
    align_queries_with_step: true
    cache_results: true
    results_cache:
      cache:
        # todo: use redis
        enable_fifocache: true
        fifocache:
          max_size_bytes: 100MB

  frontend:
    #  max_outstanding_per_tenant: 1000
    log_queries_longer_than: 10s
```

Is this a bug or do i have an error in my configuration?
