### ISSUE TITLE
Distributor Ring's consul configuration not working

### ISSUE THREAD

**Issue by arnaldomf** [cortexproject/cortex#4385]
**Describe the bug**
I'm trying to configure the consul address for the distributor ring through the configuration file, but Cortex keeps using **localhost:8500**.

**To Reproduce**
1. Cortex Version: (version=1.9.0, branch=HEAD, revision=ed4f339)
2. Write the file `distributor.yaml` with the following content:

```yaml
target: "distributor"
auth_enabled: false
server:
  http_listen_port: 9009
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000
  register_instrumentation: true
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 2m
  log_level: debug
  http_path_prefix: ""
distributor:
  pool:
    client_cleanup_period: 15s
    health_check_ingesters: true
  max_recv_msg_size: 104857600
  remote_timeout: 2s
  extra_queue_delay: 0s
  sharding_strategy: "default"
  shard_by_all_labels: false
  extend_writes: true
  ring:
    kvstore:
      store: "consul"
      prefix: "collectors/"
      consul:
        host: "172.20.255.200:8500"
        acl_token: ""
        http_client_timeout: 20s
        consistent_reads: false
        watch_rate_limit: 1
        watch_burst_size: 1
    heartbeat_period: 5s
    heartbeat_timeout: 1m
    instance_interface_names: [eth0 en0]
  instance_limits:
    max_ingestion_rate: 0
    max_inflight_push_requests: 0
```
3. Start the container with the command

```bash
docker create --name=cortex-distributor1 --network=cortex \
-v $(pwd)/distributor.yaml:/etc/distributor.yaml \
    -p 9004:9009 \
    quay.io/cortexproject/cortex:v1.9.0 \
    -config.file=/etc/distributor.yaml
```

**Expected behavior**

The container cortex-distributor1 should connect to consul at **172.20.255.200:8500**.

**Environment:**
 - Infrastructure: Docker running in a Ubuntu 20.04 laptop. Image: quay.io/cortexproject/cortex:v1.9.0

**Additional Context**
```
level=info ts=2021-07-27T14:28:54.561248774Z caller=main.go:188 msg="Starting Cortex" version="(version=1.9.0, branch=HEAD, revision=ed4f339)"
level=info ts=2021-07-27T14:28:54.562088915Z caller=server.go:239 http=[::]:9009 grpc=[::]:9095 msg="server listening on addresses"
level=debug ts=2021-07-27T14:28:54.562876693Z caller=api.go:128 msg="api: registering route" methods=GET path=/config auth=false
level=debug ts=2021-07-27T14:28:54.563034869Z caller=api.go:128 msg="api: registering route" methods=GET path=/ auth=false
level=debug ts=2021-07-27T14:28:54.563060405Z caller=api.go:128 msg="api: registering route" methods=GET path=/debug/fgprof auth=false
level=debug ts=2021-07-27T14:28:54.563094665Z caller=api.go:128 msg="api: registering route" methods=GET path=/memberlist auth=false
level=debug ts=2021-07-27T14:28:54.563222308Z caller=api.go:128 msg="api: registering route" methods=GET,POST path=/ingester/ring auth=false
level=debug ts=2021-07-27T14:28:54.563251547Z caller=api.go:128 msg="api: registering route" methods=GET,POST path=/ring auth=false
level=debug ts=2021-07-27T14:28:54.563524283Z caller=api.go:128 msg="api: registering route" methods=POST path=/api/v1/push auth=true
level=debug ts=2021-07-27T14:28:54.563562356Z caller=api.go:128 msg="api: registering route" methods=GET path=/distributor/all_user_stats auth=false
level=debug ts=2021-07-27T14:28:54.56359717Z caller=api.go:128 msg="api: registering route" methods=GET path=/distributor/ha_tracker auth=false
level=debug ts=2021-07-27T14:28:54.563620392Z caller=api.go:128 msg="api: registering route" methods=POST path=/api/prom/push auth=true
level=debug ts=2021-07-27T14:28:54.563637729Z caller=api.go:128 msg="api: registering route" methods=GET path=/all_user_stats auth=false
level=debug ts=2021-07-27T14:28:54.563664979Z caller=api.go:128 msg="api: registering route" methods=GET path=/ha-tracker auth=false
level=debug ts=2021-07-27T14:28:54.563692937Z caller=api.go:128 msg="api: registering route" methods=GET path=/services auth=false
level=debug ts=2021-07-27T14:28:54.563764735Z caller=module_service.go:49 msg="module waiting for initialization" module=distributor-service waiting_for=memberlist-kv
level=info ts=2021-07-27T14:28:54.563825413Z caller=module_service.go:59 msg=initialising module=server
level=debug ts=2021-07-27T14:28:54.563842637Z caller=module_service.go:49 msg="module waiting for initialization" module=memberlist-kv waiting_for=server
level=info ts=2021-07-27T14:28:54.563889267Z caller=module_service.go:59 msg=initialising module=memberlist-kv
level=debug ts=2021-07-27T14:28:54.563853378Z caller=module_service.go:49 msg="module waiting for initialization" module=ring waiting_for=server
level=debug ts=2021-07-27T14:28:54.5639354Z caller=module_service.go:49 msg="module waiting for initialization" module=distributor-service waiting_for=ring
level=debug ts=2021-07-27T14:28:54.563938095Z caller=module_service.go:49 msg="module waiting for initialization" module=ring waiting_for=memberlist-kv
level=info ts=2021-07-27T14:28:54.563955293Z caller=module_service.go:59 msg=initialising module=ring
level=debug ts=2021-07-27T14:28:54.564471505Z caller=module_service.go:81 msg=stopping module=server
level=error ts=2021-07-27T14:28:54.564459598Z caller=cortex.go:426 msg="module failed" module=ring err="invalid service state: Failed, expected: Running, failure: unable to initialise ring state: Get \"http://localhost:8500/v1/kv/collectors/ring?stale=\": dial tcp 127.0.0.1:8500: connect: connection refused"
level=error ts=2021-07-27T14:28:54.564499413Z caller=cortex.go:426 msg="module failed" module=distributor-service err="failed to start distributor-service, because it depends on module ring, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expected: Running, failure: unable to initialise ring state: Get \"http://localhost:8500/v1/kv/collectors/ring?stale=\": dial tcp 127.0.0.1:8500: connect: connection refused"
level=debug ts=2021-07-27T14:28:54.564526357Z caller=module_service.go:104 msg="module waiting for" module=memberlist-kv waiting_for=ring
level=debug ts=2021-07-27T14:28:54.564552049Z caller=module_service.go:81 msg=stopping module=memberlist-kv
level=info ts=2021-07-27T14:28:54.56456975Z caller=module_service.go:91 msg="module stopped" module=memberlist-kv
level=info ts=2021-07-27T14:28:54.565735671Z caller=server_service.go:50 msg="server stopped"
level=info ts=2021-07-27T14:28:54.565762806Z caller=module_service.go:91 msg="module stopped" module=server
level=info ts=2021-07-27T14:28:54.565773441Z caller=cortex.go:415 msg="Cortex stopped"
level=error ts=2021-07-27T14:28:54.565806452Z caller=log.go:106 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/__w/cortex/cortex/pkg/cortex/cortex.go:461\nmain.main\n\t/__w/cortex/cortex/cmd/cortex/main.go:190\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
```
