### ISSUE TITLE
Cortex fails to start with SignatureDoesNotMatch when minio is used as alertmanager storage

### ISSUE THREAD

**Issue by nohack** [cortexproject/cortex#4414]
The server fails to start with the below error when cortex is run as standalone docker container

> level=error ts=2021-08-10T15:37:08.952533603Z caller=cortex.go:401 msg="module failed" module=alertmanager err="invalid service state: Failed, expected: Running, failure: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 1699FC02BBE5816F, host id: "

**To Reproduce**
1. Start Cortex (ubuntu/cortex:1.7-21.04_beta image)

**Expected behavior**
Cortex starts

**Environment:**
 - Infrastructure: laptop

**Storage Engine**
- Blocks

Below is the alertmanager config

```
alertmanager:
  external_url: http://random.com/alertmanager
  enable_api: true
  storage:
    type: s3
    s3:
      endpoint: 172.17.0.1:9000
      bucketnames: cortex/am
      access_key_id: admin
      secret_access_key: admin
      signature_version: v4
      insecure: true

```
