### ISSUE TITLE
container probes fail when Cortex mutual TLS is enabled

### ISSUE THREAD

**Issue by danfromtitan** [cortexproject/cortex#4427]
**Describe the bug**
I followed the [instructions here ](https://cortexmetrics.io/docs/guides/tls/) to enable mTLS in Cortex. 
I deployed Cortex from the latest [helm chart](https://github.com/cortexproject/cortex-helm-chart).

The outcome is pods are being terminated because the [startup probe](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L444) must present a client TLS when making a [readiness probe](https://cortexmetrics.io/docs/api/#readiness-probe) request.

Fortunatelly the helm chart [provides the ability](https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L444) to overwrite the container probes with a command instead of http-get. 
Unfortunatelly the Cortex image is [missing curl](https://github.com/cortexproject/cortex/blob/master/cmd/cortex/Dockerfile#L2) to implement a probe alternative such as:

`curl -s --cert /srv/certs/cert.pem --key /srv/certs/key.pem --cacert /srv/certs/ca.crt --resolve server.common.name:8080:127.0.0.1 https://server.common.name:8080/ready`

I suspect adding _curl_ to the Cortex base image would help. Is there anything else I could use instead ?

**Comment by danfromtitan** [comment]
Looks like the following probe would pass as long as _curl_ is in the cortex image:

```yaml
   startupProbe:
      httpGet: # this is needed here to override default from chart's values, otherwise deployment fails with "Forbidden: may not specify more than 1 handler type"
      exec:
        command:
          - curl
          - --cert
          - /srv/certs/cert.pem
          - --key
          - /srv/certs/key.pem
          - --cacert
          - /srv/certs/ca.crt
          - --resolve
          - server.common.name:8080:127.0.0.1
          - https://server.common.name:8080/ready
```

Cert files are coming from a volume mounted from a k8s secret, the helm chart offers the option for extra volumes. Same files are referenced from Cortex TLS configuration.

So the only thing left here is to add curl to cortex base image.
