### ISSUE TITLE
alert rules and notification do not seem to fire and resolve correctly

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#4472]
We are trying to get Cortex Alertmanager (AM) and ruler set up for our production monitoring system.  We found that the interaction between ruler and alert manager  both seemed not to behave as expected.  I am using Cortex 1.8.0 currently running on GKE

Cortex alertmanager config:

```
global:
  resolve_timeout: 1h
  slack_api_url: <'url'>
route:
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 10m
  receiver: slack_receiver

  routes:
    - receiver: slack_receiver
      matchers: [ '{severity=~"critical|warning"}' ]
      continue: true
      group_by: ['...']
```

We have the following alert rule in Ruler is as followed:

```
gateway-alerts:
    - name: nms_testing_node_uname_info_combined_group
      rules:
        - alert: 'CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway'
          expr: count by (gateway_id) (node_uname_info{job="node-exporter",gateway_id="ABC"}) > 0
          for: 1m
          labels:
            condition: 'CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway'
            severity: critical
          annotations:
            description: 'CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway'
            title: 'From Cortex - CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway.'
        - alert: 'CORTEX: NMS Test #2 (same group): node_uname_info with preview gateway'
          expr: count by (gateway_id) (node_uname_info{job="node-exporter",gateway_id="XYZ"}) > 0
          for: 1m
          labels:
            condition: 'CORTEX: NMS Test #2 (same group): node_uname_info with preview gateway'
            severity: critical
          annotations:
            description: 'CORTEX: NMS Test #2 (same group): node_uname_info with preview gateway'
            title: 'From Cortex - CORTEX: NMS Test #2 (same group): node_uname_info with preview gateway.'
```
`evaluation_interval` is default i.e 1m
The intention of the test is to have this always sending an alert  and not resolved until the resolve time_out is reached,  since both gateways ABC and XYZ is always up (count returned will always be >0)

We are trying to achieve and were expecting the following:

- Alert will be firing and sent to AM every 1m or so (1 fo ABC and one for XYZ)
- AM will group them and notify every 5m (grooup_internal=5m)
- Alert will not be marked as resolved from ruler since the GWs are always up
- After 1 h has passed, AM will send RESOLVED since resolve_timeout is set to 1 h

Instead here are the results that we see after we submit the rule to ruler:

- Only alert for ABC fired. Alert for XYZ does not happen at all. (nothing on AM logs)
- it took about 2 min for the first alert to notify
- The first alert stay open for 15 min then we received a [resolved] slack message for the first alert after 15 min -> NOT EXPECTED
- alert notification again 1 min after the reolved message accompanied bu a resolved message 5 mins later
- Then the pattern of 1 min alert and 5 min Resolve message repeat 

Any help decipher this behavior and to get to what we are wanted to do is greatly appreciated.

Here are some alert manager logs and time line tracking 
```
# TIMELINE:
# 01: [active]:          2021-09-10T23:17:56.731621365Z
# 02: [active]:          2021-09-10T23:18:06.731938263Z
# 03: [active/notify]:   2021-09-10T23:18:06.875198743Z <<<-----
# 04: [resolved]:        2021-09-10T23:19:56.703827668Z
# 05: [active]:          2021-09-10T23:22:56.719947494Z
# 06: [active]:          2021-09-10T23:23:06.732121683Z
# 07: [resolved]:        2021-09-10T23:23:56.703743152Z
# 08: [resolved]:        2021-09-10T23:25:56.703878436Z
# 09: [active]:          2021-09-10T23:27:56.70408957Z
# 10: [active]           2021-09-10T23:28:06.732319811Z
# 11: [active]           2021-09-10T23:29:56.704176763Z
# 12: [resolved]:        2021-09-10T23:31:56.704018616Z
# 13: [resolved]:        2021-09-10T23:33:06.73248529Z
# 14: [resolved/notify]: 2021-09-10T23:33:06.888599518Z <<<-----
# 15: [active]:          2021-09-10T23:33:56.704176594Z
# 16: [active]:          2021-09-10T23:34:06.704391691Z
# 17: [active/notify]:   2021-09-10T23:34:06.784596034Z <<<-----
# 18: [active]:          2021-09-10T23:35:56.703940898Z
# 19: [resolved]:        2021-09-10T23:36:56.704120888Z


# 1:
level=debug ts=2021-09-10T23:17:56.731621365Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]"
# 2:
level=debug ts=2021-09-10T23:18:06.731938263Z caller=dispatch.go:474 user=0 component=dispatcher component=dispatcher aggrGroup="{}/{severity=~\"^(?:critical|warning)$\"}:{alertname=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", condition=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", gateway_id=\"ABC\", severity=\"critical\"}" msg=flushing alerts="[CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[5f9828b][active]]"
# 3:
level=debug ts=2021-09-10T23:18:06.875198743Z caller=notify.go:732 user=0 component=dispatcher component=dispatcher receiver=slack_receiver integration=slack[0] msg="Notify success" attempts=1
# 4:
level=debug ts=2021-09-10T23:19:56.703827668Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][resolved]"
# 5:
level=debug ts=2021-09-10T23:22:56.719947494Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]"
# 6:
level=debug ts=2021-09-10T23:23:06.732121683Z caller=dispatch.go:474 user=0 component=dispatcher component=dispatcher aggrGroup="{}/{severity=~\"^(?:critical|warning)$\"}:{alertname=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", condition=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", gateway_id=\"ABC", severity=\"critical\"}" msg=flushing alerts="[CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]]"
# 7:
level=debug ts=2021-09-10T23:23:56.703743152Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][resolved]"
# 8:
level=debug ts=2021-09-10T23:25:56.703878436Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][resolved]"
# 9:
level=debug ts=2021-09-10T23:27:56.70408957Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]"
# 10:
level=debug ts=2021-09-10T23:28:06.732319811Z caller=dispatch.go:474 user=0 component=dispatcher component=dispatcher aggrGroup="{}/{severity=~\"^(?:critical|warning)$\"}:{alertname=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", condition=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", gateway_id=\"ABC\", severity=\"critical\"}" msg=flushing alerts="[CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]]"
# 11:
level=debug ts=2021-09-10T23:29:56.704176763Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]"
# 12:
level=debug ts=2021-09-10T23:31:56.704018616Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][resolved]"
# 13:
level=debug ts=2021-09-10T23:33:06.73248529Z caller=dispatch.go:474 user=0 component=dispatcher component=dispatcher aggrGroup="{}/{severity=~\"^(?:critical|warning)$\"}:{alertname=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", condition=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", gateway_id=\"ABC\", severity=\"critical\"}" msg=flushing alerts="[CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][resolved]]"
# 14:
level=debug ts=2021-09-10T23:33:06.888599518Z caller=notify.go:732 user=0 component=dispatcher component=dispatcher receiver=slack_receiver integration=slack[0] msg="Notify success" attempts=1
# 15:
level=debug ts=2021-09-10T23:33:56.704176594Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]"
# 16:
level=debug ts=2021-09-10T23:34:06.704391691Z caller=dispatch.go:474 user=0 component=dispatcher component=dispatcher aggrGroup="{}/{severity=~\"^(?:critical|warning)$\"}:{alertname=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", condition=\"CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway\", gateway_id=\"ABC\", severity=\"critical\"}" msg=flushing alerts="[CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]]"
# 17:
level=debug ts=2021-09-10T23:34:06.784596034Z caller=notify.go:732 user=0 component=dispatcher component=dispatcher receiver=slack_receiver integration=slack[0] msg="Notify success" attempts=1
# 18:
level=debug ts=2021-09-10T23:35:56.703940898Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][active]"
# 19:
level=debug ts=2021-09-10T23:36:56.704120888Z caller=dispatch.go:138 user=0 component=dispatcher component=dispatcher msg="Received alert" alert="CORTEX: NMS Test #1 (same group): node_uname_info with integration gateway[ABC][resolved]"
```
