### ISSUE TITLE
Cortex block storage does not response metrics data older than query_ingesters_within with bucket_index enabled

### ISSUE THREAD

**Issue by truong-hua** [cortexproject/cortex#4479]
**Describe the bug**
According to https://cortexmetrics.io/docs/blocks-storage/production-tips/, we configured query_ingesters_within = 335m and query_store_after = 330m. But the query only response data within query_ingesters_within and there is no older.

**To Reproduce**
1. Start Cortex 1.10.0
2. Perform Operations(Read/Write/Others)

**Expected behavior**
Cortex response data older than query_ingesters_within properly

**Environment:**
 - Docker Swarm

**Storage Engine**
- Blocks

**Additional Context**
I guess that the reason is related to a situation that I upgraded cortex from an old version with bucket_index disabled. But even after a while running with new bucket_index enabled, old data is still not responded properly.
I tried to disable bucket_index and everything work well again. So is it mean that we have to delete all data in storage before changing the bucket_index option?

My cortex config
```yaml
# Disable the requirement that every request to Cortex has a
# X-Scope-OrgID header. `fake` will be substituted in instead.
auth_enabled: false

server:
  http_listen_port: 9009

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  lifecycler:
    join_after: 5m
  
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints: ['etcd:2379']
      replication_factor: 2

querier:
  max_concurrent: 6
  query_store_after: 330m
  query_ingesters_within: 335m
  query_store_for_labels_enabled: true

storage:
  engine: blocks

blocks_storage:
  bucket_store:
    sync_interval: 1h
    bucket_index:
      enabled: true
    ignore_deletion_mark_delay: 1h
  tsdb:
    retention_period: 6h
    ship_interval: 4h

store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: etcd
      etcd:
        endpoints: ['etcd:2379']
    replication_factor: 2

compactor:
  block_ranges: [4h0m0s,24h0m0s]
  compaction_interval: 2h
```
