### ISSUE TITLE
Alermanager sent Resolved even though alert is still firin

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#4491]
**Describe the bug**
We have a strange situation with Ruler and Cortex AM :
we have a rule to sent an alert to AM when the condition of high io wait > 5% for 1m.  AM recevied the alert and sent notification about the alert as planned.  We have resolved_timeout set to 1H. Within 20 min of receiving the alert,  we receive a Resolved notification on the original alert even through the high iowait data is still greater than 5% - i.e not resolved.

Alertmanager config
```
global:
  resolve_timeout: 1h
route:
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
routes:
  group_by: ['gateway_id']

```
Ruler config
```
rules:
        - alert: 'CORTEX: NMS Test #3 (separate group): I/O Wait (avg) > 5%'
          expr: avg by (gateway_id, nodename, environment) (irate(node_cpu_seconds_total{mode="iowait",job="node-exporter"}[5m])) * 100 / on(gateway_id) group_left(nodename) node_uname_info{job="node-exporter"} > 5
          for: 5m
```

**Expected behavior**
The alert keep firing because the gateway iowait did not come down less than 5% in the eval time frame

**Environment:**
 - Infrastructure: GKE - K8s 1.17
 - Deployment tool: K8s deployment 

**Storage Engine**
- [ X] Blocks
- [ ] Chunks

**Additional Context**
