### ISSUE TITLE
Error in cortex-configs (K8s)

### ISSUE THREAD

**Issue by Ejant** [cortexproject/cortex#4536]
Hi all!

I've just migrated cortex from helm chart and I see an error on cortex-configs:

```
~$ kubectl -n cortex logs cortex-configs-67cfd878b8-9dh56
error loading config from /etc/cortex/cortex.yaml: Error parsing config file: yaml: unmarshal errors:
  line 5: field alertmanager_storage not found in type cortex.Config
  line 91: field ruler_storage not found in type cortex.Config
```

However, Cortex is running fine, only this pod has CrashLoopBackOff.

my chart info:

```
~$ helm list -n cortex
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
cortex  cortex          8              2021-10-26 11:30:39.037128669 -0300 -03 deployed        cortex-0.7.0    v1.10.0
```

and my config:

```
config:
 alertmanager:
   external_url: /alertmanager
 alertmanager_storage:
   backend: s3
   s3:
        bucket_name: cortexmetrics
        endpoint: 'minio-hl.minio-operator.svc.cluster.local:9000'
        access_key_id: minio
        secret_access_key: some_access_key
        insecure: false
        http:
          insecure_skip_verify: true

 ruler_storage:
   backend: s3
   s3:
     bucket_name: cortexmetrics
     endpoint: 'minio-hl.minio-operator.svc.cluster.local:9000'
     access_key_id: minio
     secret_access_key: some_access_key
     insecure: false
     http:
       insecure_skip_verify: true

 querier:
  store_gateway_addresses: "dns+cortex-store-gateway-headless:9095"
 storage:
  engine: blocks
 blocks_storage:
    bucket_store:
      sync_dir: "/data"
    backend: s3
    tsdb:
      dir: "/data"
    s3:
      bucket_name: cortexmetrics
      endpoint: 'minio-hl.minio-operator.svc.cluster.local:9000'
      access_key_id: minio
      secret_access_key: minio123
      insecure: false
      http:
        insecure_skip_verify: true
 ingester:
    lifecycler:
      join_after: 1s
      final_sleep: 10s
      num_tokens: 512
      ring:
        replication_factor: 1
        kvstore:
          store: consul
          prefix: 'collectors/'
          consul:
            host: 'consul.service.consul:8500'
            http_client_timeout: '20s'
            consistent_reads: true

 limits:
     ingestion_rate: 50000
     max_label_names_per_series: 45
     ingestion_burst_size: 100000


 frontend:
memcached:
 enabled: true
memcached-index-read:
 enabled: true
memcached-index-write:
 enabled: true
memcached-frontend:
 enabled: true
```

Pods info:

```
NAME                                    READY   STATUS             RESTARTS   AGE
cortex-alertmanager-7cc577d6bb-28gx9    1/1     Running            0          66m
cortex-compactor-0                      1/1     Running            0          66m
cortex-configs-67cfd878b8-9dh56         0/1     CrashLoopBackOff   20         82m
cortex-distributor-7b668f6f5b-hzlft     1/1     Running            0          65m
cortex-distributor-7b668f6f5b-w6xsc     1/1     Running            0          66m
cortex-ingester-68f9dff66f-cw7l4        1/1     Running            0          60m
cortex-ingester-68f9dff66f-p59xw        1/1     Running            0          63m
cortex-ingester-68f9dff66f-z42lf        1/1     Running            0          66m
cortex-memcached-0                      2/2     Running            0          7h54m
cortex-memcached-1                      2/2     Running            0          7h55m
cortex-memcached-frontend-0             2/2     Running            0          7h55m
cortex-memcached-frontend-1             2/2     Running            0          7h55m
cortex-memcached-index-read-0           2/2     Running            0          7h55m
cortex-memcached-index-read-1           2/2     Running            0          7h55m
cortex-memcached-index-write-0          2/2     Running            0          7h55m
cortex-memcached-index-write-1          2/2     Running            0          7h55m
cortex-nginx-7d68f676dc-q6kv8           1/1     Running            0          7h55m
cortex-nginx-7d68f676dc-tgnqr           1/1     Running            0          7h55m
cortex-querier-6d8c48d548-99s6v         1/1     Running            0          66m
cortex-querier-6d8c48d548-rtnf6         1/1     Running            0          65m
cortex-query-frontend-d69fc7cd9-8ss2g   1/1     Running            0          66m
cortex-query-frontend-d69fc7cd9-vzhgr   1/1     Running            0          65m
cortex-ruler-7dff7849bd-x8zf9           1/1     Running            0          66m
cortex-store-gateway-0                  1/1     Running            0          65m
```

Maybe some parameters are missing? alertmanager_storage and ruler_storage are defined.
My cluster is deployed on kubernetes bare metal

Thanks!!
