### ISSUE TITLE
Getting 500 DeadlineExceeded error when pushing from Prometheus to Cortex

### ISSUE THREAD

**Issue by vnorguet** [cortexproject/cortex#4537]
**Describe the bug**

When I connect Prometheus to Cortex, I get 500 error with:  `rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false` message

**To Reproduce**
1. Start Cortex (SHA or version): v1.10.0
2. Perform Operations(Read/Write/Others): Write

**Expected behavior**
Prometheus push data to cortex to `http://cortex:9009/api/v1/push` and get 2xx return code

**Environment:**
 - Infrastructure: Docker Swarm on AWS EC2 instance
 - Deployment tool: Docker stack deploy on top of `docker-compose` file
 
### Docker-compose file
```yaml
version: '3.7'

volumes:
  prometheus_data:
  cortex_data:

networks:
  back-tier:
    driver: overlay
    attachable: true

services:

  prometheus:
    image: prom/prometheus:v2.30.3
    user: root
    volumes:
      - /data/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier

  cortex:
    image: quay.io/cortexproject/cortex:v1.10.0
    command: -config.file=/etc/cortex/config.yml -ring.store=consul -consul.hostname=consul:8500
    ports:
      - "9009:9009"
    volumes:
      - type: volume
        source: cortex_data
        target: /data
      - type: bind
        source: /data/cortex/config.yml
        target: /etc/cortex/config.yml
    networks:
      - back-tier

  consul:
    image: consul:1.9.10
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - back-tier
    ports:
      - "8500:8500"
```

### Prometheus config file (cortex-related part only)
```yaml
remote_write:
  - url: http://cortex:9009/api/v1/push
    tls_config:
      insecure_skip_verify: true
```

### Cortex config file 

Mostly copy-paste from https://github.com/cortexproject/cortex/blob/master/docs/configuration/single-process-config-blocks.yaml

```yaml

# Configuration for running Cortex in single-process mode.
# This should not be used in production.  It is only for getting started
# and development.

# Disable the requirement that every request to Cortex has a
# X-Scope-OrgID header. `fake` will be substituted in instead.
auth_enabled: false

server:
  http_listen_port: 9009

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    # address: 127.0.0.1

    # We want to start immediately and flush on shutdown.
    join_after: 0
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512

    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

storage:
  engine: blocks

blocks_storage:
  tsdb:
    dir: /tmp/cortex/tsdb

  bucket_store:
    sync_dir: /tmp/cortex/tsdb-sync

  # You can choose between local storage and Amazon S3, Google GCS and Azure storage. Each option requires additional configuration
  # as shown below. All options can be configured via flags as well which might be handy for secret inputs.
  backend: filesystem # s3, gcs, azure or filesystem are valid options
  # s3:
  #   bucket_name: cortex
  #   endpoint: s3.dualstack.us-east-1.amazonaws.com
    # Configure your S3 credentials below.
    # secret_access_key: "TODO"
    # access_key_id:     "TODO"
#  gcs:
#    bucket_name: cortex
#    service_account: # if empty or omitted Cortex will use your default service account as per Google's fallback logic
#  azure:
#    account_name:
#    account_key:
#    container_name:
#    endpoint_suffix:
#    max_retries: # Number of retries for recoverable errors (defaults to 20)
  filesystem:
    dir: /data/tsdb

compactor:
  data_dir: /tmp/cortex/compactor
  sharding_ring:
    kvstore:
      store: inmemory

frontend_worker:
  match_max_concurrent: true

ruler:
  enable_api: true
  enable_sharding: false

ruler_storage:
  backend: local
  local:
    directory: /tmp/cortex/rules

```
**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

### Cortex logs

```
monitoring_cortex.1.nfe6iq961ohu@ip-10-0-10-253    | level=warn ts=2021-10-27T09:50:50.8974364Z caller=logging.go:71 traceID=00a24d443c582031 msg="POST /api/v1/push (500) 2.001150859s Response: \"rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false; Content-Encoding: snappy; Content-Length: 14941; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.30.3; X-Prometheus-Remote-Write-Version: 0.1.0; "
monitoring_cortex.1.nfe6iq961ohu@ip-10-0-10-253    | level=warn ts=2021-10-27T09:50:50.89900903Z caller=logging.go:71 traceID=24e4a64e38780a74 msg="POST /api/prom/push (500) 2.002819455s Response: \"rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false; Content-Encoding: snappy; Content-Length: 14900; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.30.3; X-Prometheus-Remote-Write-Version: 0.1.0; "
```

### Prometheus logs

```
monitoring_prometheus.1.5acm12dkf3py@ip-10-0-20-106    | ts=2021-10-27T09:59:59.681Z caller=dedupe.go:112 component=remote level=warn remote_name=aec840 url=http://cortex:9009/api/prom/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: rpc error: code = Canceled desc = grpc: the client connection is closing"
monitoring_prometheus.1.5acm12dkf3py@ip-10-0-20-106    | ts=2021-10-27T10:00:06.000Z caller=dedupe.go:112 component=remote level=warn remote_name=aec840 url=http://cortex:9009/api/prom/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
monitoring_prometheus.1.5acm12dkf3py@ip-10-0-20-106    | ts=2021-10-27T10:00:10.216Z caller=dedupe.go:112 component=remote level=warn remote_name=2e7064 url=http://cortex:9009/api/v1/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```
