### ISSUE TITLE
store gateway frequestly goes OOM

### ISSUE THREAD

**Issue by mvkrishna86** [cortexproject/cortex#4551]
**Describe the bug**
cortex store gateway frequestly goes OOM.

**To Reproduce**
1. Start Cortex-1.10.0 in micro service mode, in k8s
2. Start feeding metrics.

**Expected behavior**
Store Gateway should not go to OOM

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Storage Engine**
- [ *] Blocks

**Additional Context**
![image](https://user-images.githubusercontent.com/15136443/140645231-f52fb73e-4e4e-42ee-babb-0a6da3d96d47.png)
![image](https://user-images.githubusercontent.com/15136443/140645677-bfb6d85b-bd15-4bf9-9068-1afecabbd01a.png)

As you can see in the screenshot, I am running cortex with 3 ingesters (12Gi memory), 2 distributors and 1 store-gateway. If I dont apply limits and requests for memory, the store-gateway is occupying more than 50GB of memory and thus creating a memory crunch in node and node just goes offline. If I apply resource limits, pod just goes OOM.

**Comment by akshat-zopsmart** [comment]
@mvkrishna86 what was the resolution for this issue?

**Comment by mvkrishna86** [comment]
We are just containing the issue.. temporarily, we can delete the pod, pvc. But I could not find any permanent fix.

**Comment by mvkrishna86** [comment]
We increased the store-gateway memory limit to 24G.

**Comment by akshat-zopsmart** [comment]
Even after deleting the PVC, the memory utilisation still continues to grow. We have not set any memory limit on the store-gateway and even set the request to 64GB. Memory grows upto around 57GB and then the container restarts with error 
`fatal error: runtime: cannot allocate memory`
Even tried to enable sharding but no avail

**Comment by mvkrishna86** [comment]
here is my config:

```
    config:
      auth_enabled: true
      api:
        prometheus_http_prefix: /prometheus
        response_compression_enabled: true
      alertmanager:
        enable_api: true
        external_url: /api/prom/alertmanager
        data_dir: /data/
        storage:
          type : local
          local:
            path: /configs/
      alertmanager_storage:
        backend: filesystem
      blocks_storage:
        backend: s3
        bucket_store:
          index_cache:
            backend: memcached
            memcached:
              addresses: dns+cortex-memcached:11211
          metadata_cache:
            backend: memcached
            memcached:
              addresses: dns+cortex-memcached:11211
            bucket_index_content_ttl: 1m
            tenant_blocks_list_ttl: 1m
            metafile_doesnt_exist_ttl: 1m
          index_header_lazy_loading_enabled: true
          index_header_lazy_loading_idle_timeout: 1h
          sync_dir: /data/tsdb
          sync_interval: 5m
        s3:
          bucket_name: XXXXXXXXXXXXXXXXXXXXXX
          endpoint: s3.dualstack.ap-south-1.amazonaws.com
          region: ap-south-1
          sse:
            type: SSE-S3
        tsdb:
          block_ranges_period:
            - 1h
          dir: /data/tsdb
          retention_period: 2h
          #max_exemplars: 10000
      compactor:
        compaction_interval: 4h
        cleanup_interval: 5m
        #data_dir: /tmp/cortex-compactor
        sharding_enabled: true
        sharding_ring:
          kvstore:
            store: memberlist
        block_deletion_marks_migration_enabled: false
        deletion_delay: 0
      distributor:
        pool:
          health_check_ingesters: true
        ring:
          kvstore:
            store: memberlist
        shard_by_all_labels: true
      frontend:
        log_queries_longer_than: 10s
      frontend_worker:
        frontend_address: dns+cortex-query-frontend-headless:9095
        grpc_client_config:
          max_send_msg_size: 52428800
        match_max_concurrent: true
      ingester:
        lifecycler:
          final_sleep: 0s
          join_after: 10s
          observe_period: 30s
          num_tokens: 512
          ring:
            kvstore:
              store: memberlist
              # zone_awareness_enabled: true
            replication_factor: 1
        max_transfer_retries: 0
        max_chunk_age: 2h
      ingester_client:
        grpc_client_config:
          grpc_compression: gzip
          max_recv_msg_size: 52428800
          max_send_msg_size: 52428800
      limits:
        enforce_metric_name: true
        max_global_series_per_metric: 0
        max_global_series_per_user: 0
        max_query_length: 744h
        max_query_lookback: 0s
        max_series_per_metric: 0
        max_series_per_user: 0
        reject_old_samples: true
        reject_old_samples_max_age: 30m
        ingestion_rate: 50000
        #ingestion_rate_strategy: global
        #compactor_blocks_retention_period: 744h
      memberlist:
        bind_port: 7946
        join_members:
          - cortex-memberlist
      querier:
        active_query_tracker_dir: /data/cortex/querier
        #query_ingesters_within: 35m
        query_store_after: 0s
      query_range:
        align_queries_with_step: true
        cache_results: true
        results_cache:
          cache:
            memcached:
              expiration: 1h
            memcached_client:
              addresses: dns+cortex-memcached:11211
              timeout: 5s
        split_queries_by_interval: 24h
      ruler:
        alertmanager_url: http://cortex-alertmanager.monitoring.svc.cluster.local/api/prom/alertmanager
        enable_alertmanager_discovery: false
        enable_alertmanager_v2: false
        enable_api: true
        enable_sharding: true
        rule_path: /etc/cortex/rules
        ring:
          kvstore:
            store: memberlist
      ruler_storage:
        backend: local
        local:
          directory: /data/rules
        s3:
          bucket_name: XXXXXXXXXXXXXXXXXXXX
          endpoint: s3.dualstack.ap-south-1.amazonaws.com
          region: ap-south-1
          sse:
            type: SSE-S3
      server:
        grpc_listen_port: 9095
        grpc_server_max_concurrent_streams: 1000
        grpc_server_max_recv_msg_size: 104857600
        grpc_server_max_send_msg_size: 104857600
        http_listen_port: 80
      storage:
        engine: blocks
        index_queries_cache_config:
          memcached:
            expiration: 1h
          memcached_client:
            addresses: cortex-memcached:11211
            timeout: 5s
      store_gateway:
        sharding_enabled: true
        sharding_ring:
          kvstore:
            store: memberlist
          replication_factor: 1
          zone_awareness_enabled: true
```

```
    store_gateway:
      replicas: 2
      statefulSet:
        enabled: true
      resources:
        limits:
          cpu: 4000m
          memory: 24Gi
        requests:
          cpu: 2000m
          memory: 8Gi
      persistentVolume:
        storageClass: "ebs-sc"
        size: 50Gi
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      serviceMonitor:
        enabled: true
        additionalLabels:
          app: cortex-store_gateway
          release: kube-prometheus-stack
```
