### ISSUE TITLE
unexpected EOF while scanning BigTable tables by blocksconverter / scanner

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex#4592]
I'm running blocksconverter/scanner in k8s trying to migrate from chunks to blocks and every now and then it runs into the following error:

```
level=error ts=2021-12-17T16:28:42.163716674Z caller=main.go:104 msg="scanner failed" err="failed to process table dev_index_2705: failed to scan table dev_index_2705 and generate plan files: rpc error: code = Internal desc = unexpected EOF"
```

Upon restarting the container it completes working on the table and picks up another ones until the error occurs again. Any hints what could be wrong here? I don't think it is expected to have a restart driven migration :D

The environment:
- gke 1.20
- gcs & bigtable
- blocksconverter v1.11.0

The definitions:

```
apiVersion: v1
kind: Pod
metadata:
  name: cortex-scanner
spec:
  serviceAccountName: xxx
  containers:
    - name: cortex-scanner
      image: cortexproject/blocksconvert:v1.11.0
      command: ["/bin/sh", "-c"]
      args:
        - >-
          /blocksconvert
          -target=scanner
          -schema-config-file=/data/schema.yaml
          -scanner.output-dir=/scanner-output-dir
          -blocks-storage.backend=gcs
          -blocks-storage.gcs.bucket-name=xxx
          -bigtable.instance=xxx
          -bigtable.project=xxx
          -log.level=debug
      volumeMounts:
      - name: schema-volume
        mountPath: /data
      - name: scanner-output-dir
        mountPath: /scanner-output-dir
  volumes:
    - name: schema-volume
      configMap:
        name: cortex-scanner-schema
    - name: scanner-output-dir
      persistentVolumeClaim:
        claimName: cortex-scanner-output-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-scanner-schema
data:
  schema.yaml: |
    configs:
      - from: "2020-10-01"
        schema: v9
        chunks:
            period: 1w
            prefix: dev_chunks_
        index:
            period: 1w
            prefix: dev_index_
        object_store: gcs
        store: gcp-columnkey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-scanner-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
```
