### ISSUE TITLE
Target-specific validation of configuration

### ISSUE THREAD

**Issue by mweibel** [cortexproject/cortex#4607]
**Is your feature request related to a problem? Please describe.**
cortex-helm-chart configures all cortex configuration in one file (secret or ConfigMap). Depending on helm chart values it manually adds memcached backend type and address for the blocks storage caches. 
I wanted to adjust (based on [recommended starting configuration](https://cortexproject.github.io/cortex-helm-chart/guides/configure_memcached.html)) the memcached client configuration and ended up with this config:

```yaml
# [...]
blocks_storage:
  backend: gcs
  bucket_store:
    bucket_index:
      enabled: true
    chunks_cache:
      backend: memcached
      memcached:
        max_async_buffer_size: 10000000
        max_async_concurrency: 100
        max_get_multi_batch_size: 1000
        max_get_multi_concurrency: 750
        max_idle_connections: 750
        max_item_size: 33554432
        timeout: 300ms
    index_cache:
      backend: memcached
      memcached:
        max_async_buffer_size: 10000000
        max_async_concurrency: 100
        max_get_multi_batch_size: 1000
        max_get_multi_concurrency: 750
        max_idle_connections: 750
        max_item_size: 16777216
        timeout: 300ms
    metadata_cache:
      backend: memcached
      memcached:
        max_async_buffer_size: 10000000
        max_async_concurrency: 100
        max_get_multi_batch_size: 1000
        max_get_multi_concurrency: 750
        max_idle_connections: 750
        max_item_size: 16777216
        timeout: 300ms
# [...]
```

When running e.g. alertmanager with this configuration it will fail because `blocks_storage.bucket_store.chunks_cache.backend: memcached` is defined but not `blocks_storage.bucket_store.chunks_cache.memcached.addresses`. This fails even though the alertmanager does not use any caching. 

```bash
$ git checkout v1.11.0 # in cortex cloned project
$ go run cmd/cortex/main.go -target=alertmanager -config.file=cfg.yaml
error validating config: invalid TSDB config: index-cache configuration: no index cache backend addresses
exit status 1
```
This confused me because I knew alertmanager didn't use any caching and wondered why it would fail like that.

When removing the key `blocks_storage.bucket_store.chunks_cache.backend` it works properly. 

**Note:** `chunks_cache` is just an example, same happens for `index_cache` and `metadata_cache`.

**Describe the solution you'd like**
Alertmanager does not use caching, therefore I believe the config validation should not fail if `backend` is defined but `memcached.addresses` not. 

I'm aware this is because the whole config validation is done before the target is selected and maybe the change needed for this is too much for the benefit it brings :)

**Additional context**
[Issue in cortex-helm-chart discussing this](https://github.com/cortexproject/cortex-helm-chart/issues/299)
