### ISSUE TITLE
Redeploy Cortex / Reuse existing blob storage isn't working

### ISSUE THREAD

**Issue by justinrush** [cortexproject/cortex#4653]
**Describe the bug**
We are doing some testing for deploying Cortex to production. We ran some load testing for 12 hours. One of those tests was to delete the Cortex instance we had (we deployed via Helm, we manually removed the PV/PVCs) but leave the Azure blob storage account intact. We then redeployed (with the exact same values overrides) and expected that we'd be able to query the data that exists in the Azure storage account. However, what we see is that no data is available, new or old.

The store gateway seems to have found the blobs:
```
level=info ts=2022-02-24T01:10:31.042621469Z caller=main.go:193 msg="Starting Cortex" version="(version=1.11.0, branch=HEAD, revision=43c646b)"
level=info ts=2022-02-24T01:10:31.043008283Z caller=server.go:260 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-02-24T01:10:31.170611545Z caller=memcached.go:49 msg="created memcached cache"
level=info ts=2022-02-24T01:10:31.186696008Z caller=memcached.go:49 msg="created memcached cache"
level=info ts=2022-02-24T01:10:31.215206229Z caller=memcached.go:55 msg="created memcached index cache"
level=info ts=2022-02-24T01:10:31.21562994Z caller=module_service.go:64 msg=initialising module=server
level=info ts=2022-02-24T01:10:31.215702106Z caller=module_service.go:64 msg=initialising module=runtime-config
level=info ts=2022-02-24T01:10:31.215717635Z caller=module_service.go:64 msg=initialising module=memberlist-kv
level=info ts=2022-02-24T01:10:31.215816629Z caller=module_service.go:64 msg=initialising module=store-gateway
level=info ts=2022-02-24T01:10:31.215840439Z caller=bucket_stores.go:142 msg="synchronizing TSDB blocks for all users"
level=info ts=2022-02-24T01:10:31.307282579Z caller=bucket_stores.go:418 org_id=fake msg="creating user bucket store"
level=info ts=2022-02-24T01:10:34.933324279Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.534361902s id=01FWMAQBP98DW5TF9RAHY2BPR8
level=info ts=2022-02-24T01:10:35.032565358Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.633695239s id=01FWMAQ2266KYJNS9TXCQZJKS1
level=info ts=2022-02-24T01:10:35.03805401Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.638990396s id=01FWMJ8GMKPXNA3WBXRB3F5THS
level=info ts=2022-02-24T01:10:35.057097025Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.65792594s id=01FWMAQ21FT254RMWTT5CKTRXB
level=info ts=2022-02-24T01:10:35.057828333Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.658539802s id=01FWMGM9WFA33NJ5RKR9AWS3WM
level=info ts=2022-02-24T01:10:35.06185274Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.662683396s id=01FWMAQ1VEZ8FH1S6XGAJ5SYK0
level=info ts=2022-02-24T01:10:35.130580103Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.731132468s id=01FWKZ9D4BQ93AZE9YK5MKXTB2
level=info ts=2022-02-24T01:10:35.141329159Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.741930232s id=01FWKRDNWA6CNK2FTK8N3VME7F
level=info ts=2022-02-24T01:10:35.154224043Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=3.754878306s id=01FWKQNW5A24XFX7JYKP223FK6
level=info ts=2022-02-24T01:10:35.154376493Z caller=bucket_stores.go:151 msg="successfully synchronized TSDB blocks for all users"
level=info ts=2022-02-24T01:10:35.154420659Z caller=cortex.go:436 msg="Cortex started"
level=info ts=2022-02-24T01:25:26.763623235Z caller=gateway.go:326 msg="synchronizing TSDB blocks for all users" reason=periodic
level=info ts=2022-02-24T01:25:27.652935246Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=784.989086ms id=01FWMM9SF3EM2ZA39P3NPDV8DA
level=info ts=2022-02-24T01:25:27.653461222Z caller=bucket.go:551 org_id=fake msg="loaded new block" elapsed=785.514886ms id=01FWMMFEBREQG7W7143XRNHS72
level=info ts=2022-02-24T01:25:27.653533662Z caller=gateway.go:332 msg="successfully synchronized TSDB blocks for all users" reason=periodic
```

We deployed using the newest chart (1.3.0) which uses Cortex 1.11.0.

I didn't see any errors on the queriers or the query frontends.

If it helps, this is the values overrides we provided to deploy the chart:

```yaml
ingress:
  enabled: true
  ingressClass:
    enabled: true
    name: "management"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: myhost.com
      paths:
        - /cortex/?(.*)

tags:
  blocks-storage-memcached: true

config:

  blocks_storage:
    bucket_store:
      chunks_cache:
        backend: memcached
        memcached:
          addresses: 'dns+{{ include "cortex.fullname" $ }}-memcached-blocks:11211'

      metadata_cache:
        backend: memcached
        memcached:
          addresses: 'dns+{{ include "cortex.fullname" $ }}-memcached-blocks-metadata:11211'
      
      bucket_index:
        enabled: true

  ingester:
    lifecycler:
      ring:
        # since we are running on kubernetes and this isn't mission critical, 
        replication_factor: 1
    walconfig:
      wal_enabled: true
      recover_from_wal: true
      wal_dir: "/data/wal"

  # See https://github.com/cortexproject/cortex/blob/master/docs/configuration/config-file-reference.md#storage_config
  storage:
    engine: blocks
    azure:
      container_name: cortex
      account_name: myacct
      account_key: so-secret==
  blocks_storage:
    # this doesn't seem like it should be needed, but it absolutly is
    backend: azure
    azure:
      container_name: cortex
      account_name: myacct
      account_key: so-secret==
    tsdb:
      dir: "/data/tsdb"
    bucket_store:
      sync_dir: "/data/tsdb-sync"

  limits:
    accept_ha_samples: true
    ha_cluster_label: __cluster__
    ha_replica_label: __replica__
    ingestion_rate: 25000
    ingestion_burst_size: 100000

  distributor:
    ha_tracker:
      enable_ha_tracker: true
      ha_tracker_update_timeout: 30s
      ha_tracker_failover_timeout: 1m
      kvstore:
        store: etcd
        # https://cortexmetrics.io/docs/configuration/configuration-file/#etcd_config
        etcd:
          endpoints:
          - cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local:2379
          - cortex-etcd-1.cortex-etcd-headless.cortex.svc.cluster.local:2379
          - cortex-etcd-2.cortex-etcd-headless.cortex.svc.cluster.local:2379

    ring:
      kvstore:
        store: etcd
        # https://cortexmetrics.io/docs/configuration/configuration-file/#etcd_config
        etcd:
          endpoints:
          - cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local:2379
          - cortex-etcd-1.cortex-etcd-headless.cortex.svc.cluster.local:2379
          - cortex-etcd-2.cortex-etcd-headless.cortex.svc.cluster.local:2379

  alertmanager_storage:
    backend: azure
    azure:
      container_name: cortex
      account_name: myacct
      account_key: so-secret==

ingester:
  autoscaling:
    enabled: true
    targetMemoryUtilizationPercentage: 70
    minReplicas: 1
    maxReplicas: 10
  statefulSet:
    enabled: true
  persistentVolume:
    size: 20Gi
  resources:
    requests:
      memory: 2G
      cpu: 0.01
    limits:
      memory: 2400M
      cpu: 2  

distributor:
  autoscaling:
    enabled: true
    targetMemoryUtilizationPercentage: 80
    minReplicas: 1
    maxReplicas: 5
  resources:
    requests:
      memory: 256M
      cpu: 0.2
    limits:
      memory: 280M
      cpu: 1  

querier:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
  resources:
    requests:
      memory: 100M
      cpu: 0.01
    limits:
      memory: 500M
      cpu: 0.5  

query_frontend:
  replicas: 2

table_manager:
  replicas: 1

nginx:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5

store_gateway:
  replicas: 1
  persistentVolume:
    size: 30Gi
  resources:
    requests:
      memory: 100M
      cpu: 0.01
    limits:
      memory: 1G
      cpu: 0.5  

compactor:
  replicas: 1
  persistentVolume:
    size: 8Gi

ruler:
  enabled: false

alertmanager:
  enabled: false

# memcached instances to deploy and use
# This is used by query-frontend for results caching
memcached-frontend:
  enabled: true
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
# used by store-gateway as shared block index cache when store-gateway scale out is enabled
memcached-blocks-index:
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
memcached-blocks:
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
# used by store gateway and queriers to share metadata of fetched blocks
# reduces api calls to backend storage
memcached-blocks-metadata:
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
```
