### ISSUE TITLE
Compactor is unable to properly compact blocks

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex#4677]
**Describe the bug**
I'm running two config-identical Cortex clusters, let's say: prod & nonprod. 
Nonprod looks fine. 
In prod it seems that compactor is unable to properly compact blocks and this leads to prod having ~11 000 blocks, while nonprod ~600 (the volume of data alone is not 20x bigger on prod, so this is unexpected).
Having 11k blocks causes problems with store gateway pods which tend to take a lot of time to load blocks and, until all blocks loaded, the cluster does not work great.
Why am I assuming that compacting does not work for prod? It seems that upon successful compaction there should be some entries such as `compacted blocks` and `marking compacted block for deletion` etc. There are none, only endless entries like the ones above.  Also I'm running various dashboards, ie. https://github.com/monitoring-mixins/website/blob/master/assets/cortex/dashboards/cortex-compactor-resources.json which shows literally no compacted blocks for prod (and some for nonprod). Sharing my logs below.

I am aware that there are at least several issues that could be causing compactor not to work https://github.com/cortexproject/cortex/pull/4453 or https://github.com/cortexproject/cortex/issues/3569, but **I'd very much welcome any hints that could allow me to unblock compacting** as the current volume of blocks makes the cluster prone to not working properly (which is not great for production usage, obviously).

**Expected behavior**
Compacting works, the amount of blocks in prod in not ~20x the amount of blocks in nonprod (more like ~3-4 times at best).

**Environment:**
K8s in GKE v1.21, deployed by the official cortex Helm chart v1.4.0

**Storage Engine**
Blocks

**Additional Context**
Two sets of logs are here:
- [Initial debug level logs (nontruncated)](https://gist.github.com/shybbko/5b30d596af85a99061933f7bffafe1c0#file-initial-debug-level-logs-nontruncated)
- [Extra logs - disabled debug and didn't include the usual noise for more clarity](https://gist.github.com/shybbko/5b30d596af85a99061933f7bffafe1c0#file-extra-logs-disabled-debug-and-didn-t-include-the-usual-noise-for-more-clarity)

**Comment by shybbko** [comment]
Also tried using `thanos tools` (https://github.com/thanos-io/thanos/blob/main/docs/components/tools.md) in hopes that maybe I'll be able to use the `repair` option, but seems that it's unable to see the blocks (even though I believe the config to be a proper one, as no errors are presented) 

```
level=debug ts=2022-03-18T17:33:42.835491406Z caller=main.go:66 msg="maxprocs: Leaving GOMAXPROCS=[16]: CPU quota undefined"
level=info ts=2022-03-18T17:33:42.835776032Z caller=factory.go:49 msg="loading bucket configuration"
level=debug ts=2022-03-18T17:33:42.838233901Z caller=fetcher.go:319 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2022-03-18T17:33:42.996412892Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=158.208834ms duration_ms=158 cached=0 returned=0 partial=0
level=info ts=2022-03-18T17:33:42.996497217Z caller=tools_bucket.go:458 msg="ls done" objects=0
level=info ts=2022-03-18T17:33:43.014347816Z caller=main.go:161 msg=exiting
level=debug ts=2022-03-18T17:33:43.01442981Z caller=main.go:66 msg="maxprocs: No GOMAXPROCS change to reset%!(EXTRA []interface {}=[])"
```

Here's the config I used: 
```
apiVersion: v1
kind: Pod
metadata:
  name: thanos-tools
spec:
  serviceAccountName: xxx-service-account
  containers:
    - name: thanos-tools
      image: quay.io/thanos/thanos:v0.25.1
      command: ["/bin/sh", "-c"]
      args:
        - >-
          thanos tools bucket ls
          --log.level=debug
          --objstore.config-file=/config/bucket.yml
      volumeMounts:
      - name: config-file-volume
        mountPath: /config
  volumes:
    - name: config-file-volume
      configMap:
        name: bucket-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bucket-config
data:
  bucket.yml: |
    type: GCS
    config: 
      bucket: "xxx-blocks-storage"
```
