### ISSUE TITLE
Query cortex only shows metrics pushed to individual nodes

### ISSUE THREAD

**Issue by PatrikMuniak** [cortexproject/cortex#4678]
Hi, 
I have cortex set up on 3 VMs using consul and a common s3 bucket where  metrics from all 3 nodes are being sent, when I send metrics to node 1 I'm not able to query those metrics from node 2 and don't understand why. From my understanding isn't the store-gateway supposed to iterate over the whole bucket and discover the blocks pushed by all the nodes? 

Here is the config excluding defaults, it's the same for all the 3 nodes: 
```
alertmanager:
  data_dir: /local/nmr/cortex/var/backend-alertmanager
  enable_api: true
  external_url: http://localhost:9009/alertmanager
  sharding_ring:
    kvstore:
      prefix: cortex-alertmanagers/
alertmanager_storage:
  filesystem:
    dir: /local/nmr/cortex/var/backend-alertmanager
  local:
    path: /local/nmr/cortex/var/backend-alertmanager
  s3:
    access_key_id: <key_id>
    bucket_name: eu-cortex-alertmanager
    endpoint: <endpoint>
    http:
      insecure_skip_verify: true
    secret_access_key: <access_key>
blocks_storage:
  bucket_store:
    sync_dir: /local/nmr/cortex/var/tsdb-sync
  s3:
    access_key_id: <key_id>
    bucket_name: eu-cortex-metrics
    endpoint: <endpoint>
    http:
      insecure_skip_verify: true
    secret_access_key: <access_key>
  tsdb:
    dir: /local/nmr/cortex/var/tsdb
compactor:
  data_dir: /local/nmr/cortex/var/compactor
  sharding_ring:
    kvstore:
      prefix: cortex-collectors/
distributor:
  ha_tracker:
    kvstore:
      prefix: cortex-ha-tracker/
  remote_timeout: 10s
  ring:
    instance_interface_names:
    - ens192
    kvstore:
      prefix: cortex-collectors/
frontend_worker:
  match_max_concurrent: true
ingester:
  lifecycler:
    address: 127.0.0.1
    final_sleep: 0s
    interface_names:
    - ens192
    min_ready_duration: 0s
    num_tokens: 512
    ring:
      kvstore:
        prefix: cortex-collectors/
      replication_factor: 1
  walconfig:
    wal_enabled: true
ingester_client:
  grpc_client_config:
    grpc_compression: gzip
    max_send_msg_size: 104857600
querier:
  active_query_tracker_dir: /local/nmr/cortex/var/active-queries
ruler:
  alertmanager_url: http://localhost:9009/alertmanager
  enable_api: true
  rule_path: /local/nmr/cortex/var/tmp-rule-files-prom
ruler_storage:
  filesystem:
    dir: /local/nmr/cortex/var/rules
  s3:
    access_key_id: <key_id>
    bucket_name: eu-cortex-ruler
    endpoint: <endpoint>
    http:
      insecure_skip_verify: true
    secret_access_key: <access_key>
server:
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 9009
  log_level: warn
storage:
  engine: blocks
store_gateway:
  sharding_enabled: true
  sharding_ring:
    instance_interface_names:
    - ens192
    kvstore:
      prefix: cortex-collectors/
target: all,alertmanager
```
Am I missing something?
