### ISSUE TITLE
AM: crash on handleOverSizedMessages 

### ISSUE THREAD

**Issue by shuker85** [cortexproject/cortex#4684]
**Describe the bug**

Alertmanager pods are getting restarted

Full logs https://gist.github.com/shuker85/b2c6eb98174ab56bb247bc757b0370c4

**To Reproduce**
1. Start Cortex 1.8.0
2. Perform Operations(Read/Write/Others)

**Expected behavior**
No restarts

**Environment:**
 - Infrastructure: Kubernetes v1.22
 - Deployment tool: kustomize

**Storage Engine**
- [ ] Blocks
- [x] Chunks

**Additional Context**

Pod config:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-01-25T13:46:34Z"
  generateName: alert-manager-
  labels:
    controller-revision-hash: alert-manager-89856fd9d
    name: alert-manager
    statefulset.kubernetes.io/pod-name: alert-manager-0
  name: alert-manager-0
  namespace: cortex
spec:
  containers:
  - args:
    - -alertmanager-storage.gcs.service-account=/var/secrets/google/credentials.json
    - -alertmanager.cluster.gossip-interval=500ms
    - -alertmanager.cluster.listen-address=0.0.0.0:9094
    - -alertmanager.cluster.peer-timeout=5s
    - -alertmanager.cluster.peers=alert-manager-0.alert-manager-headless:9094
    - -alertmanager.cluster.peers=alert-manager-1.alert-manager-headless:9094
    - -alertmanager.cluster.peers=alert-manager-2.alert-manager-headless:9094
    - -alertmanager.cluster.push-pull-interval=5s
    - -alertmanager.sharding-enabled=true
    - -alertmanager.sharding-ring.consul.hostname=consul:8500
    - -alertmanager.storage.gcs.bucketname=xxxyyyzzz
    - -alertmanager.storage.type=gcs
    - -alertmanager.web.external-url=/api/prom/alertmanager
    - -experimental.alertmanager.enable-api=true
    - -log.level=warn
    - -server.http-listen-port=80
    - -target=alertmanager
    - -tenant-federation.enabled=true
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/credentials.json
    image: quay.io/cortexproject/cortex:v1.8.0
    imagePullPolicy: IfNotPresent
    name: alert-manager
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      failureThreshold: 1
      httpGet:
        path: /ready
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 2
      timeoutSeconds: 3
    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 100m
        memory: 3Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/secrets/google
      name: service-account-secret
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jl2rf
      readOnly: true
  dnsConfig:
    options:
    - name: ndots
      value: "1"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: alert-manager-0
  nodeName: eur-standard-5ah5-c535d04c-p4c4
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: alert-manager-headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: service-account-secret
    secret:
      defaultMode: 420
      optional: false
      secretName: service-account-secret
  - name: default-token-jl2rf
    secret:
      defaultMode: 420
      secretName: default-token-jl2rf
```
