### ISSUE TITLE
Cortex in distributed mode miss data between 23:00 and 24:00 UTC with a recovering on the next day

### ISSUE THREAD

**Issue by Onlinehead** [cortexproject/cortex#4749]
**Describe the bug**
Every day metrics data is unavailable for a period from 23:00 to 24:00 UTC. That is a moving gap, so on the next day previous data became available, but the latest period from 23 to 24 UTC is not. 
<img width="694" alt="Screenshot 2022-06-10 at 12 24 52" src="https://user-images.githubusercontent.com/1026551/173046176-30f9c172-88d7-47e5-b142-ae35c86fbafb.png">
I manually check the index in S3 and it contains block for the period of gap, but because of whatever reason it is not in use until the next time period.

**To Reproduce**
1. Start Cortex in distributed micro-services mode. 
2. Perform Operations(Read/Write/Others)

**Expected behavior**
Should be no gap in a data.

**Environment:**
 - Infrastructure: Kubernetes, AWS, EBS volumes, S3 storage.
 - Deployment tool: helm
 - Replicas: 3 ingesters, 3 storage-gateway, 1 compactor, 2 queries, 2 queries-frontends, 2 distributors.
 - Memerlist for all components.

**Storage Engine**
- [x] Blocks

**Additional Context**
No error logs in components during that time.
Overrides from default values.yaml in a configuration (excluding enabled memcached cache):
```
compactor:
    consistency_delay: 2h10m
query_range:
    split_queries_by_interval: 24h
distributor:
    shard_by_all_labels: true
bucket_store:
      max_concurrent: 100
      consistency_delay: 10s
chunks_cache:
  metadata_cache:
    chunks_list_ttl: 1h
        metafile_content_ttl: 1h
        metafile_attributes_ttl: 1h
        block_index_attributes_ttl: 1h
storage:
    engine: blocks
    index_queries_cache_config:
      memcached:
        expiration: 1h
```
