### ISSUE TITLE
Distributors use more memory with Replication Factor 1, compared with Replication Factor 3

### ISSUE THREAD

**Issue by SuperMatt** [cortexproject/cortex#4833]
**Describe the bug**
We have a cortex cluster which does not need the default Replication Factor of 3, so we modified the replication factor variable and reduced it down to 1. Since this point, the memory usage of the distributors has increased 3x, and the resource usage on the ingesters is not equally balanced. E.g., one ingester per region is using more CPU than the others, and has its disk filling at a higher rate, as if more data is being sent to one ingester, compared to all the rest.

**To Reproduce**
1. Start Cortex 1.13.0
2. Send a lot of data to Cortex
3. Reduce the the replication factor from 3 to 1

**Expected behavior**
The expected outcome would be for the memory usage to remain the same or drop

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
This is an image of our distributor memory usage dashboard, and you can see the moment that the scaling factor was decreased from 3 to 1
![image](https://user-images.githubusercontent.com/3635576/185612951-a1c8286d-a713-45bc-9974-8e64abce606f.png)

Below is our distributor config

```
alertmanager:
  enable_api: true
  external_url: /api/prom/alertmanager
alertmanager_storage:
  s3:
    bucket_name: company-cortex-alertmanager
    endpoint: s3.dualstack.region-1.amazonaws.com
    region: region-1
api:
  response_compression_enabled: true
blocks_storage:
  bucket_store:
    bucket_index:
      enabled: true
    sync_dir: /data/tsdb-sync
  s3:
    bucket_name: company-cortex
    endpoint: s3.dualstack.region-1.amazonaws.com
    region: region-1
  tsdb:
    dir: /data/tsdb
distributor:
  extend_writes: false
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      consul:
        host: consul-server.prometheus.region1.eks:8500
frontend:
  log_queries_longer_than: 10s
ingester:
  lifecycler:
    availability_zone: region1
    join_after: 10s
    num_tokens: 512
    observe_period: 10s
    ring:
      excluded_zones: region2,region3,region4,region5,region6,region7,region8,region9,region10,region11
      kvstore:
        store: memberlist
      replication_factor: 1
ingester_client:
  grpc_client_config:
    grpc_compression: snappy
    max_recv_msg_size: 10485760
    max_send_msg_size: 10485760
limits:
  accept_ha_samples: true
  ha_cluster_label: eks_cluster_name
  ha_replica_label: replica
  ingestion_rate: 50000
  ingestion_tenant_shard_size: 3
  max_label_names_per_series: 100
  max_label_value_length: 10240
  reject_old_samples_max_age: 1w
memberlist:
  abort_if_cluster_join_fails: false
  gossip_interval: 1s
  join_members:
  - cortex-memberlist.region1
  - cortex-memberlist.region2
  - cortex-memberlist.region3
  - cortex-memberlist.region4
  - cortex-memberlist.region5
  - cortex-memberlist.region6
  - cortex-memberlist.region7
  - cortex-memberlist.region8
  - cortex-memberlist.region9
  - cortex-memberlist.region10
  - cortex-memberlist.region11
querier:
  active_query_tracker_dir: /data/active-query-tracker
  store_gateway_addresses: dns+cortex-store-gateway-headless:9095
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      memcached:
        expiration: 1h0m0s
      memcached_client:
        timeout: 1s
  split_queries_by_interval: 24h0m0s
ruler:
  enable_api: true
ruler_storage:
  backend: local
  local:
    directory: /data/rules
runtime_config:
  file: /etc/cortex-runtime-config/runtime_config.yaml
server:
  grpc_server_max_concurrent_streams: 10000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 8080
storage:
  engine: blocks
  index_queries_cache_config:
    memcached:
      expiration: 1h0m0s
    memcached_client:
      timeout: 1s
target: distributor
tenant_federation:
  enabled: true
```
