### ISSUE TITLE
AlertManager UI gives 404

### ISSUE THREAD

**Issue by paul-bormans** [cortexproject/cortex#4911]
The AlertManager UI as specified in https://cortexmetrics.io/docs/api/#alertmanager-ui returns 404.

```
/ $ curl -XGET -I -H 'X-Scope-OrgID: system' http://cortex-alertmanager.cortex.svc.cluster.local:8080/alertmanager
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Date: Thu, 13 Oct 2022 13:28:06 GMT
Content-Length: 19
```

I can fetch the tenant specific config:

```
/ $ curl -XGET -H 'X-Scope-OrgID: system' http://cortex-alertmanager.cortex.svc.cluster.local:8080/multitenant_alertmanager/configs
system:
  template_files: {}
  alertmanager_config: |-
    global:
      resolve_timeout: 5m
      http_config: {}
      smtp_hello: localhost
      smtp_require_tls: true
<...>
```

**To Reproduce**

1. Install Cortex on a kind cluster (chart 1.6.0 cortex v1.11.1), see values.yaml below. this is basically following the example of using sidecars to pickup rules and AM configs (https://cortexproject.github.io/cortex-helm-chart/guides/configure_rules_via_sidecar.html).
2. apply alertmanager.yaml
3. find the sidecar applying the config for the tenant

```
kubectl logs cortex-alertmanager-966f7dd5b-sphts -n cortex -c cortex-sc-alertmanager | head
{"time": "2022-10-11T15:01:22.441554+00:00", "level": "INFO", "msg": "Starting collector"}
{"time": "2022-10-11T15:01:22.441965+00:00", "level": "INFO", "msg": "Loading incluster config ..."}
{"time": "2022-10-11T15:01:22.443417+00:00", "level": "INFO", "msg": "Config for cluster api at 'https://10.96.0.1:443' loaded..."}
{"time": "2022-10-11T15:01:22.443630+00:00", "level": "INFO", "msg": "Unique filenames will not be enforced."}
{"time": "2022-10-11T15:01:22.443788+00:00", "level": "INFO", "msg": "5xx response content will not be enabled."}
{"time": "2022-10-11T15:01:27.485680+00:00", "level": "INFO", "msg": "Found a folder override annotation, placing the alertmanager-example-config in: /data/system"}
```

4. But UI not accessible:

```
/ $ curl -XGET -I -H 'X-Scope-OrgID: system' http://cortex-alertmanager.cortex.svc.cluster.local:8080/alertmanager
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Date: Thu, 13 Oct 2022 13:38:33 GMT
Content-Length: 19

/ $ curl -XGET  -H 'X-Scope-OrgID: system' http://cortex-alertmanager.cortex.svc.cluster.local:8080/alertmanager
404 page not found
```

**Additional Context**
values.yaml

```
config:
  auth_enabled: true
  api:
    alertmanager_http_prefix: "/alertmanager"
  server:
    log_level: debug
  storage:
    engine: blocks  # chunks (deprecated) or blocks
  blocks_storage:
    backend: s3
    s3:
      bucket_name: cortex-blocks-bucket
      endpoint: minio.minio.svc.cluster.local:9000
      secret_access_key: my-secret-key
      access_key_id: my-access-key
      insecure: true

  ruler:
    enable_api: true
    rule_path: /rules
  ruler_storage:
    backend: local
    local:
      directory: /data/rules    
  alertmanager:
    enable_api: true
    data_dir: /data
  alertmanager_storage:
    backend: local
    local:
      path: /data    

alertmanager:
  replicas: 1
  sidecar:
    enabled: true
    label: cortex/alertmanager-config
    labelValue: ""
    searchNamespace: source-nginx
    folder: /data
    folderAnnotation: "tenant"

ruler:
  replicas: 1
  sidecar:
    enabled: true
    label: cortex/rules
    labelValue: ""
    searchNamespace: source-nginx
    folder: /data/rules
    folderAnnotation: "tenant"
```

alertmanager.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    tenant: system
  labels:
    cortex/alertmanager-config: "true"
  name: alertmanager-example-config
  namespace: source-nginx
data:
  system.yaml: |-
    global:
      resolve_timeout: 5m
      http_config: {}
      smtp_hello: localhost
      smtp_require_tls: true
    route:
      receiver: "null"
      group_by:
      - alertname
      routes:
      - receiver: "null"
        match:
          alertname: Watchdog
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    receivers:
    - name: "null"
```
