### ISSUE TITLE
Adding runtime configuration usage doc

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4928]
If I want to configurate `runtime_config`,  I can't find any example at  [configuration-file](https://cortexmetrics.io/docs/configuration/configuration-file/) doc, how about adding some simple runtime_config example like:

update cortex.yaml:

```
runtime_config:
  file: /cortex/config/runtime.yaml
```
update  /cortex/config/runtime.yaml:
```
overrides:
  tenant1:
    ingestion_rate: 50000
  tenant2:
    ingestion_rate: 75000
```
