### ISSUE TITLE
ingester memberlist brain split 

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4931]
**Describe the bug**

when stop the seed member and recover later, the ring will brain split.

**To Reproduce**
1. Start Cortex (v1.13.1)
2. Perform Operations(docker image)

I use docker-compose to make test, there are three cortex instances named cortex-1, cortex-2 and cortex3.   the memeberlist source is only cortex-1:

```
ingester:
  lifecycler:
    # We want to start immediately.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3

memberlist:
  join_members: [cortex-1]
```

when started,  I can see all of them from every instance ingester ring page:

![image](https://user-images.githubusercontent.com/1459834/197166093-69896d18-c01f-4c80-8187-b985b2e527cf.png)

but when I stop cortex-1, after about 10 seconds, start cortex-1 again,  ring brain split existed:

![image](https://user-images.githubusercontent.com/1459834/197166781-7a37160e-e376-4656-8589-b4bead0b0830.png)

![image](https://user-images.githubusercontent.com/1459834/197166911-c2c8bb97-1651-457a-95d1-ce487339361f.png)

**Expected behavior**
when cortex-1 started, it will auto join to the ring, no bran split.

how about remain the source member only set it to unheathy, when it started, the ring will recover auto
