### ISSUE TITLE
post rule groups support

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4932]
**Is your feature request related to a problem? Please describe.**

At now cortex only support add rule group one by one, but promtheus rules support groups. 

for example:

rules.yaml
```
groups:
- name: cortex_api_1
  rules:
  - expr: xxx
      by (le, cluster, job))
    record: xxx
- name: cortex_api_2
  rules:
  - expr: xxx
    record: xxx
```

but cortex only support:

```
name: <string>
interval: <duration;optional>
rules:
  - record: <string>
    expr: <string>
  - alert: <string>
    expr: <string>
    for: <duration>
    annotations:
      <annotation_name>: <string>
    labels:
      <label_name>: <string>
```

how about changing to promethus compatible way or add new api for rule groups post.
