### ISSUE TITLE
Ruler sharding does't work with filesystem backed ruler storage

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4941]
**Describe the bug**
I run three cortex with mode=all at port(8001~8003) , and ruler related configuration is:

```
ruler:
  enable_sharding: true
  rule_path: /data/rules
ruler_storage:
  backend: filesystem
```

When I use cortex-tool to load rules（about 17 groups）, all the rules have stored at the api called cortex node(8001), other two cortex have no any rule. 

**To Reproduce**
1. Start Cortex with docker-compose.

**Expected behavior**
1. rule groups sharding works for filesystem.
