### ISSUE TITLE
make memberlist kvstore to default

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4971]
**Is your feature request related to a problem? Please describe.**

currently the ring kvstore default value is consul, how about changing it to `memberlist`.

**Comment by alvinlin123** [comment]
I think this idea is worth the discussing. What pros and cons do you think changing the default would have?

For me the cons is it would be a breaking change? Pros is better out-of-box experience ( no need to deploy extra service out-of-box).

**Comment by songjiayang** [comment]
Frankly speaking, this is indeed a break changes, but when we want to use consul, we must configure consul_config. if  memberlist is default, we can use common `memberlist_config`.

memberlist isn't default: 

```
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

memberlist:
  join_members: [cortex-1, cortex-2, cortex-3]

store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist

ruler:
  enable_api: true
  enable_sharding: true
  poll_interval: 2s
  ring:
    kvstore:
      store: memberlist
```

memberlist is default:

```
memberlist:
  join_members: [cortex-1, cortex-2, cortex-3]

store_gateway:
  sharding_enabled: true

ruler:
  enable_api: true
  enable_sharding: true
  poll_interval: 2s
```
