### ISSUE TITLE
[Alertmanager] Increasing number of AM replicas above the replication factor breaks AM

### ISSUE THREAD

**Issue by ShunjiTakano** [cortexproject/cortex#5090]
**Describe the bug**
When using alertmanager with sharding enabled, if we increase the number of AM instances above the replication factor, the UI breaks and sometimes return 'the Alertmanager is not configured' error. (See video)
When curling directly into the alertmanager pods using /alertmanager/api/v1/alerts, we also see that some pods return 'the Alertmanager is not configured' while others return correct responses and that tenants alerts.

https://user-images.githubusercontent.com/89514357/211770150-7e0b15c8-cb1c-4fa4-99a5-eb26f4943699.mp4

But if we decrease the number of instances to below the replication factor, it will return to normal and work okay.

For example

#works okay
replication_factor = 3
number of replicas <= 3

#starts breaking again
replication_factor = 3
number of replicas >= 4

**To Reproduce**
1. Start Cortex with just alertmanager in kubernetes using statefulset and below config
2. cortex.yml
```
alertmanager:
  enable_api: true
  external_url: /alertmanager
  sharding_enabled: true 
  sharding_ring:
    kvstore:
      store: consul 
      prefix: alertmanagers/
      consul:
        host: ${CONSUL_HOST}
        http_client_timeout: 20s
    replication_factor: 3
  alertmanager_client:
    grpc_compression: gzip
alertmanager_storage:
  backend: gcs
  gcs:
    bucket_name: ${BUCKET_NAME}
    service_account: ${SERVICE_ACCOUNT}
```
3. set replicas to 3. confirm alertmanager is working
4. set replicas to 4+. Alertmanager UI will break and some pods will return 'the Alertmanager is not configured' even if that tenant has been configured
**Expected behavior**
We should be able to set the replicas number to greater than  the replica_factor, without alertmanager breaking.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: kustomize
 - kvstore: consul
 - alertmanager_storage: gcs

**Additional Context**
We see these logs when alertmanager starts breaking
`component=MultiTenantAlertmanager msg="deleted local directory for user" dir=data/test-user user=test-user`

**Comment by jeromeinsf** [comment]
What would be the expected behaviour? 
With replication_factor = 3, and number of replicas >= 4, I suspect one instance of instance manager not to be active for one tenant.

**Comment by qinxx108** [comment]
Are you using single tenant for those 4 alert manager instances ?

**Comment by ShunjiTakano** [comment]
@jeromeinsf The expected behaviour would be that the UI works for all tenants and that API requests return consistent responses.
We are putting a load balancer in front of the alertmanager pods, which then routes the requests in a round-robin fashion.
Is this not the intended way to connect to alertmanager?

**Comment by ShunjiTakano** [comment]
@qinxx108 We are using multi-tenant alertmanager. We have also configured multiple tenants.
In the video posted, it was just a single tenant refreshing the page. We have a loadbalancer in front of the alertmanager pods, so each refresh the request was being routed to a different alertmanager instance.

**Comment by jeromeinsf** [comment]
My understanding is that with replication factor of 3, only 3 alert managers have information for a given tenant, so if you round robin against 4 of them, 25% of the time it will hit a pod without the tenant information.

**Comment by qinxx108** [comment]
Are you using the latest version of cortex? the alert manager should distribute the request to the correct alert manager which own the tenant. See https://cortexmetrics.io/docs/proposals/scalable-alertmanager/

**Comment by ShunjiTakano** [comment]
Yes, we're using v1.14.1 using the image from quay.io/cortexproject/cortex

**Comment by qinxx108** [comment]
Do you have the same problem when you call the APIs? or just happens for when using the UI

**Comment by ShunjiTakano** [comment]
It happens just for the UI. The api calls work as expected.

**Comment by ShunjiTakano** [comment]
It can also be replicated localy with docker by following this guide https://cortexmetrics.io/docs/getting-started/
using below as the config and creating 4+ local instances.
```
auth_enabled: true

server:
  http_listen_port: 9009
  log_level: debug

alertmanager:
  enable_api: true
  external_url: /alertmanager
  persist_interval: 1m
  sharding_enabled: true 
  sharding_ring:
    kvstore:
      store: consul 
      consul:
        host: consul:8500
        http_client_timeout: 20s
      prefix: am/
  alertmanager_client:
    grpc_compression: gzip
alertmanager_storage:
  backend: gcs
  gcs:
    bucket_name: <bucketname>
    service_account: 'xxxx'
```

**Comment by ShunjiTakano** [comment]
Also for testing, I tried using mimir's version of alertmanager (I believe mimir is a fork of cortex). 
Using a similar configuration I was able to get it working. The UI and API calls work correctly. No matter which alertmanager instance I call, I get the expected  information. No 'the Alertmanager is not configured' error.
This makes me think there is a bug on the cortex side.
```
multitenancy_enabled: true

server:
  http_listen_port: 9009
  log_level: debug

alertmanager:
  enable_api: true
  external_url: /alertmanager
  persist_interval: 1m
  sharding_ring:
    kvstore:
      store: consul 
      consul:
        host: consul:8500
        http_client_timeout: 20s
alertmanager_storage:
  backend: gcs
  gcs:
    bucket_name: <bucketname>
    service_account: ''
```
