### ISSUE TITLE
Cortex Auth Gateway

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#5106]
**Is your feature request related to a problem? Please describe.**
Cortex server has a simple authentication mechanism (X-Scope-OrgId) but users can’t use the multi tenancy features out of the box without complicated proxy configuration. It’s hard to support all the different authentication mechanisms used by different companies but plan to have a simple but opinionated auth-gateway that provides value out of the box.

**Describe the solution you'd like**
We want to have a new experimental cortex component or tool (inside https://github.com/cortexproject/cortex/tree/master/tools) called auth-gateway that validates tenants requests and proxies valid requests to distributors and query-frontend.

https://cortexmetrics.io/docs/roadmap/#auth-gateway This is also part of the Cortex Roadmap.

**Comment by songjiayang** [comment]
According to the documentation, does it mean that the username is equal to the database id（X-Scope-OrgId）? 

Do we need to add additional fields separately to indicate the databases that the user can access.

**Comment by friedrichg** [comment]
@songjiayang yes, the name of the tenant would be X-Scope-OrgId. And I wouldn't mind if passwords became a list of strings to enable password rotation.
Regarding scope for every password, I prefer we don't do that in the initial version. 

Main target is being able to replace nginx in the cortex helm chart for most uses plus providing proper prometheus metrics, timeouts and load balancing.

Eventually, we want to be able to plug in other external auth mechanisms. For example, an external URL to offload authentication like most kubernetes ingress do.

**Comment by yeya24** [comment]
@friedrichg Another thought on this, shall we have a separate repo for this project under cortex org or keeps it here?
I feel Auth is not part of the scope of Cortex itself. But as a community project or outside the main Cortex repo, it sounds better to me.

**Comment by songjiayang** [comment]
Hi, I really like another repo for cortex gateway, because sometime we need proxy mutiple services with different routes.

In our use cases, the demo configruation like:

```
secret: "xxxx"  
basic:  
  username:      
    password: "password"       
    tenant: "orgid"                          
routes:              
  - path: "/api/v1/push"       
    target: "distributor"
  - path: "/prometheus"
    prefix: true
    target: "query-frontend"
  - path: "/api/v1/alerts"
    target: "ruler"
  - path: "/api/v1/rules"
    prefix: true
    target: "ruler"
  - path: "/alertmanager"
    prefix: true
    target: "alertmanager"    
targets:                
  distributor: "http://127.0.0.1:8004"            
  query-frontend: "http://127.0.0.1:8004"
  alertmanager: "http://127.0.0.1:8004"
  ruler: "http://127.0.0.1:8004"
  notify: "http://127.0.0.1:8100"
```

**Comment by sagar10arya** [comment]
@friedrichg  Hello sir, I am a final-year computer science student interested in learning about this project and contributing to the project as an LFX mentee. I want to get started with this project and request you to please provide some resources so that I can learn more about the project. I have basic command on golang language and would be very happy to learn and develop more through this project.

**Comment by friedrichg** [comment]
@sagar10arya apply using this [link](https://mentorship.lfx.linuxfoundation.org/project/820f9269-ddef-44e9-bf77-95a8d2444c1e)

**Comment by sagar10arya** [comment]
@friedrichg Sir how can I get started to learn about the project (any resources)?

**Comment by mahesh-hegde** [comment]
Hi @friedrichg I am applying to this project through LFX program. Just had a question.

The authentication is supposed to be done using HTTP 407 `Proxy Authorization Required` status code right?

What other features will it require to implement specific to cortex?

Also, what should my cover letter to LFX contain? Should it contain a proposal?

**Comment by dogukanteber** [comment]
Hello @songjiayang. I am the LFX Mentee for this task. Thank you for providing the demo configuration.

Upon reading the configuration with @friedrichg we could not understand what `prefix` and `secret` mean. Could you elaborate that for us?

Also, in the roadmap, the configuration example is given as this:

```yaml
tenants:
- name: infra-team
  password: basic-auth-password
- name: api-team
  password: basic-auth-password2
```
Could you tell me how is your configuration different than this?

Thanks in advance :vulcan_salute:
