### ISSUE TITLE
Remote read requests fail with "snappy: corrupt input" error

### ISSUE THREAD

**Issue by juliusv** [cortexproject/cortex#5253]
I tried using remote read from Prometheus against Cortex with the latest RC and noticed that these requests fail with this error message on the Cortex side:

    msg="failed to parse proto" err="snappy: corrupt input"

I used `git bisect` to trace this down to commit 0bcbceda57d86153d00a033651e3b0b5d8f023ad.

The Prometheus version is 2.43 (everything on Linux/amd) and its config is simply:

```yml
global:
  scrape_interval: 5s

# Write data to Cortex.
remote_write:
  - url: "http://localhost:9009/api/prom/push"
# Read data from Cortex.
remote_read:
  - url: "http://localhost:9009/api/prom/api/v1/read"

# Let Prometheus scrape itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
```
