### ISSUE TITLE
visit-mark.json was left on gcs when block was deleted by compactor

### ISSUE THREAD

**Issue by yk-zheng-zz** [cortexproject/cortex#5498]
**Describe the bug**
visit-mark.json was left on gcs when block was deleted by compactor

this issue happened on part of blocks but not all blocks
and it didn't happen when the total size of chunks in block is small

before block deletion
```sh
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/:
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/deletion-mark.json
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/index
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/meta.json
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/visit-mark.json
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/chunks/:
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/chunks/000001
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/chunks/000002
 
...
 
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/chunks/000053
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/chunks/000054
gs://cortex-data/cas/markers/01H6QGDG93Q46709ENE69R1PXK-deletion-mark.json
```
after block deletion
```sh
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/:
gs://cortex-data/cas/01H6QGDG93Q46709ENE69R1PXK/visit-mark.json
```

warning logs on compactor after block deletion
`level=warn ts=2023-08-02T06:44:56.97791064Z caller=updater.go:108 component=cleaner org_id=cas msg="skipped partial block when updating bucket index" block=01H6QGDG93Q46709ENE69R1PXK`

**To Reproduce**
1. Start Cortex (SHA or version) v1.15.3
2. Perform Operations(Read/Write/Others) N/A

**Expected behavior**
visit-mark.json can be removed by compactor automatically

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: kubectl

**Additional Context**
configuration of compactor
```yaml
limits:
  compactor_blocks_retention_period: 14d
  compactor_tenant_shard_size: 2

compactor:
  block_ranges: [2h,12h,24h]
  consistency_delay: 1h
  data_dir: /data/cortex-compactor
  compaction_interval: 1h
  compaction_concurrency: 2
  deletion_delay: 2h
  sharding_enabled: true
  sharding_strategy: "shuffle-sharding"
  sharding_ring:
    kvstore:
      consul: *consul

blocks_storage:
  backend: gcs
  gcs:
    bucket_name: xxx
    service_account: xxx
```
