### ISSUE TITLE
S3 endpoint is defaulting to incorrect value in us-gov-east-1

### ISSUE THREAD

**Issue by doris-zhou** [cortexproject/cortex#5520]
**Describe the bug**
I'm running Cortex v1.15.3 on an AWS EKS cluster in the us-gov-east-1 region. I have my blocks storage configured as follows:

```
blocks_storage:
  backend: s3
  s3:
    bucket_name: <bucket name>
    endpoint: s3-fips.us-gov-east-1.amazonaws.com
```

The store gateway and other components that reach out to S3 are failing with errors similar to the following:

```
level=error ts=2023-08-18T21:02:47.217243999Z caller=bucket_client.go:124 msg="bucket operation fail after retries" err="Get \"https://<bucket name>.s3.dualstack.us-east-1.amazonaws.com/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=\": dial tcp <redacted>: i/o timeout" operation="Iter "
```

I have confirmed that the blocks_storage.s3.endpoint value is set correctly to `s3-fips.us-gov-east-1.amazonaws.com` by using `kubectl exec` to get into the pod and checking the `etc/cortex/cortex.yaml` file, but for some reason the pods are actually trying to hit the `s3.dualstack.us-east-1.amazonaws.com` endpoint instead. Where is this incorrect endpoint coming from?

This seems similar to [this mimir issue](https://github.com/grafana/mimir/discussions/2613), but the hop limit is already set to 2 for my cluster.

I have been successfully running Cortex with the same configuration in non-gov regions, so it seems like a problem specific to the AWS GovCloud environment.

I've also tried setting the `region` to `us-gov-east-1`, so the configuration is as follows:

```
blocks_storage:
  backend: s3
  s3:
    bucket_name: <bucket name>
    region: us-gov-east-1
    endpoint: s3-fips.us-gov-east-1.amazonaws.com
```

It then tries to hit `s3.dualstack.us-gov-east-1.amazonaws.com` instead, which does work, but it is still reaching out to the incorrect endpoint -- it should be using the FIPS endpoint I specified instead.

**To Reproduce**
1. Start Cortex (v1.15.3)
2. Deploy into an AWS EKS cluster in the us-gov-east-1 region with the configuration specified above

**Expected behavior**
I expect Cortex to be trying to hit the S3 endpoint set in the configuration (`s3-fips.us-gov-east-1.amazonaws.com`), not `s3.dualstack.us-east-1.amazonaws.com`.

**Environment:**
 - Infrastructure: Kubernetes, AWS EKS
 - Deployment tool: ArgoCD

**Additional Context**
Cortex is granted access to the S3 bucket through [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).
