### ISSUE TITLE
Member list headless service cannot be resolved

### ISSUE THREAD

**Issue by duj4** [cortexproject/cortex#5652]
**Describe the bug**
I am trying to add ingester into the gossip ring via memberlist but the ingester log shows it failed to resolve the memberlist service.

**To Reproduce**
1. Start Cortex  1.15.3
2. Create a memberlist headless service and ingester statefulset with config file.

**Expected behavior**
I hope all ingesters could join in memberlist gossip ring.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: config file

**Additional Context**
config file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-config
  namespace: monitoring
data:
  config.yml: |-
    auth_enabled: false

    api:
      prometheus_http_prefix: '/prometheus'
      response_compression_enabled: true

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 10485760
      grpc_server_max_send_msg_size: 10485760
      grpc_server_max_concurrent_streams: 10000

    storage:
      engine: blocks
    
    blocks_storage:
      backend: filesystem

      filesystem:
        dir: /data/storage
      
      tsdb:
        dir: /data/tsdb
      
      bucket_store:
        sync_dir: /data/tsdb-sync
        bucket_index:
          enabled: true

    ingester:
      lifecycler:
        join_after: 10s
        observe_period: 10s
        final_sleep: 30s
        num_tokens: 512
        ring:
          replication_factor: 3
          kvstore:
            store: "memberlist"

    distributor:
      shard_by_all_labels: true
      pool:
        health_check_ingesters: true
      ring:
        kvstore:
          store: "memberlist"

    memberlist:
      bind_port: 7946
      join_members:
        - 'gossip-ring.monitoring.svc.cluster.local'
```

memberlist headless service yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: gossip-ring
  namespace: monitoring
  labels:
      app.kubernetes.io/name: cortex
      app.kubernetes.io/component: memberlist
      app.kubernetes.io/part-of: memberlist
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7946
      protocol: TCP
      name: gossip
      targetPort: gossip
  selector:
      app.kubernetes.io/name: cortex
      app.kubernetes.io/part-of: memberlist
```
ingester statefulset yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: ingester-headless
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/component: ingester
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9095
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/component: ingester
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingester
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/component: ingester
    app.kubernetes.io/part-of: memberlist
spec:
  replicas: 3
  serviceName: ingester-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: cortex
      app.kubernetes.io/component: ingester
      app.kubernetes.io/part-of: memberlist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cortex
        app.kubernetes.io/component: ingester
        app.kubernetes.io/part-of: memberlist
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      serviceAccount: "<serviceAccount name>"
      containers:
        - name: cortex-ingester
          image: cortexproject/cortex:v1.15.3
          imagePullPolicy: IfNotPresent
          args:
            - "-target=ingester"
            - "-config.file=/etc/cortex/config.yml"
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: gossip
              containerPort: 7946
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
```

ingester-0:
```
level=info ts=2023-11-14T02:07:38.573570016Z caller=main.go:194 msg="Starting Cortex" version="(version=1.15.3, branch=HEAD, revision=21e8366)"
level=info ts=2023-11-14T02:07:38.573734452Z caller=server.go:323 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-11-14T02:07:38.574939947Z caller=ingester.go:659 msg="TSDB idle compaction timeout set" timeout=1h8m10.785008982s
level=info ts=2023-11-14T02:07:38.575134471Z caller=memberlist_client.go:399 msg="Using memberlist cluster node name" name=ingester-0-5091dc09
level=info ts=2023-11-14T02:07:38.576247495Z caller=module_service.go:64 msg=initialising module=server
level=info ts=2023-11-14T02:07:38.576390515Z caller=module_service.go:64 msg=initialising module=memberlist-kv
level=info ts=2023-11-14T02:07:38.576401141Z caller=module_service.go:64 msg=initialising module=ingester-service
level=info ts=2023-11-14T02:07:38.576414476Z caller=lifecycler.go:572 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-11-14T02:07:38.576586179Z caller=ingester.go:2068 msg="opening existing TSDBs"
level=info ts=2023-11-14T02:07:38.576619528Z caller=ingester.go:2161 msg="successfully opened existing TSDBs"
level=info ts=2023-11-14T02:07:38.57665754Z caller=cortex.go:422 msg="Cortex started"
ts=2023-11-14T02:07:38.58204516Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-11-14T02:07:38.582079664Z caller=memberlist_client.go:451 msg="failed to join memberlist cluster on startup" err="1 error occurred:\n\t* Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
level=info ts=2023-11-14T02:07:38.582204675Z caller=lifecycler.go:601 msg="instance not found in ring, adding with no tokens" ring=ingester
ts=2023-11-14T02:07:38.584605614Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
ts=2023-11-14T02:07:39.908527165Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
ts=2023-11-14T02:07:42.74189994Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
ts=2023-11-14T02:07:47.448915204Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=info ts=2023-11-14T02:07:48.595557822Z caller=lifecycler.go:448 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2023-11-14T02:07:49.607086712Z caller=lifecycler.go:457 msg="observing tokens before going ACTIVE" ring=ingester
level=warn ts=2023-11-14T02:07:57.844879443Z caller=lifecycler.go:251 msg="found an existing instance(s) with a problem in the ring, this instance cannot become ready until this problem is resolved. The /ring http endpoint on the distributor (or single binary) provides visibility into the ring." ring=ingester err="instance 172.16.135.176:9095 in state JOINING"
level=info ts=2023-11-14T02:07:59.617802013Z caller=lifecycler.go:476 msg="token verification successful" ring=ingester
level=info ts=2023-11-14T02:07:59.617855144Z caller=lifecycler.go:811 msg="changing instance state from" old_state=JOINING new_state=ACTIVE ring=ingester
ts=2023-11-14T02:08:01.351986434Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
ts=2023-11-14T02:08:17.403265441Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve gossip-ring.monitoring.svc.cluster.local: lookup gossip-ring.monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=info ts=2023-11-14T02:08:54.728244792Z caller=memberlist_client.go:565 msg="joined memberlist cluster" reached_nodes=1
```
When I logged into ingester-0 and tried nslookup:
```
/ # nslookup gossip-ring.monitoring.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10:53

Name:   gossip-ring.monitoring.svc.cluster.local
Address: 172.16.135.176
Name:   gossip-ring.monitoring.svc.cluster.local
Address: 172.16.85.203
Name:   gossip-ring.monitoring.svc.cluster.local
Address: 172.16.58.218
```

**Comment by friedrichg** [comment]
do you have only one ingester and no distributors part of the memberlist cluster? that single ingester might fail to join itself.
Alternatively you should be able to set the following so your ingester doesn't fail if it can join the memberlist cluster:
```
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - gossip-ring.monitoring.svc.cluster.local:7946
```
That is how I run all my ingesters
