### ISSUE TITLE
expanding series: consistency check failed because some blocks were not queried

### ISSUE THREAD

**Issue by anuragkdi** [cortexproject/cortex#5791]
Hi Folks,

We are seeing below errors in cortex while querying metrics > 12 hours in grafana.

QUERIER

`expanding series: consistency check failed because some blocks were not queried: 01HQQ110QJNE4392CFZWM69K6Z`

`method=blocksStoreQuerier.selectSorted level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gateway instance left after checking exclude for block 01HQQ110QJNE4392CFZWM69K6Z"`

STORE GATEWAY

```
024-02-28T12:10:12+05:30 level=warn ts=2024-02-28T06:40:12.060087106Z caller=sharding_strategy.go:140 msg="failed to check block owner and block has been excluded because was not previously loaded" block=01HC9TMZAGJ28RXW73QKD43VNK err="inconsistent ring tokens information"
2024-02-28T12:10:12+05:30 level=warn ts=2024-02-28T06:40:12.060120669Z caller=sharding_strategy.go:140 msg="failed to check block owner and block has been excluded because was not previously loaded" block=01HD3SHHDV98NTCAXAPWPCW3RD err="inconsistent ring tokens information"
2024-02-28T12:10:12+05:30 level=warn ts=2024-02-28T06:40:12.060136819Z caller=sharding_strategy.go:140 msg="failed to check block owner and block has been excluded because was not previously loaded" block=01GPQ3J10WK2X2QAQJJAT6N4Y2 err="inconsistent ring tokens information"
2024-02-28T12:10:12+05:30 level=info ts=2024-02-28T06:40:12.060608181Z caller=gateway.go:332 msg="successfully synchronized TSDB blocks for all users" reason=periodic
```

META.JSON for block (seems the source is "compactor")
[01HQQ110QJNE4392CFZWM69K6Z.json](https://github.com/cortexproject/cortex/files/14430045/01HQQ110QJNE4392CFZWM69K6Z.json)

CORTEX YAML

```
alertmanager:
  enable_api: false
  external_url: /api/prom/alertmanager
  storage: {}
api:
  prometheus_http_prefix: /prometheus
  response_compression_enabled: true
auth_enabled: true
blocks_storage:
  azure:
    account_key: 
    account_name: 
    container_name: 
  backend: azure
  bucket_store:
    bucket_index:
      enabled: true
    sync_dir: /data/tsdb-sync
  tsdb:
    dir: /data/tsdb
    retention_period: 15h0m0s
distributor:
  pool:
    health_check_ingesters: true
  shard_by_all_labels: true
frontend:
  log_queries_longer_than: 10s
ingester:
  lifecycler:
    final_sleep: 30s
    join_after: 0s
    num_tokens: 512
    observe_period: 0s
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 10485760
    max_send_msg_size: 10485760
limits:
  enforce_metric_name: false
  ingestion_rate: 100000
  max_global_series_per_metric: 2000000
  max_label_names_per_series: 150
  max_label_value_length: 4096
  max_query_lookback: 0s
  max_series_per_metric: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  bind_port: 7946
  join_members:
  - cortex-memberlist
querier:
  active_query_tracker_dir: /data/cortex/querier
  store_gateway_addresses: cortex-store-gateway-headless:9095
  query_ingesters_within: 13h
  query_store_after: 12h
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      memcached:
        expiration: 1h
      memcached_client:
        timeout: 1s
  split_queries_by_interval: 24h
ruler:
  enable_alertmanager_discovery: false
  enable_api: false
  storage: {}
runtime_config:
  file: /etc/cortex-runtime-config/runtime_config.yaml
server:
  grpc_listen_port: 9095
  grpc_server_max_concurrent_streams: 10000
  grpc_server_max_recv_msg_size: 10485760
  grpc_server_max_send_msg_size: 10485760
  http_listen_port: 8080
storage:
  engine: blocks
  index_queries_cache_config:
    memcached:
      expiration: 1h
    memcached_client:
      timeout: 1s
store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
compactor:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
tenant_federation:
  enabled: true
```

CORTEX RESOURCES:

cortex app version: `1.11.0`
chart version: `1.3.0`
Distributor (count): `15`
Ingester (count): `25`
Querier (count):` 2`
Query Frontend (count): `2`
Compactor (count):` 2`
Store Gateway (count): `2` and RF:` 3`

We are currently facing this in our production cluster (Day 2) and would appreciate if someone could assist on this?
