### ISSUE TITLE
Alertmanager not able to send alerts to Pagerduty with routing_key

### ISSUE THREAD

**Issue by ShunjiTakano** [cortexproject/cortex#5998]
**Describe the bug**
In alertmanager, if you set a receiver to send to pagerduty using the _routing_key_ you get an error like:
```
"unexpected status code 400: Event object is invalid: 'event_type' is missing or blank,Service key can't be blank". 
```
Note if you use _service_key_ it will work as intended. But there are some pagerduty_configs that are only compatible with _routing_key_ such as 'severity'

**To Reproduce**
1. Start Cortex (Tested with both v1.16.0 and v1.17.1)
2. Create alertmanager receiver/routes like such:
```
receivers:
 - name: 'default-receiver'
  pagerduty_configs:
   - routing_key: '<events API v2 integration key>'
    send_resolved: true
    severity: 'warning'
```
3. Send an alert to your alertmanager. (I call the api alertmanager/api/v2/alerts, but you can send an alert through any method)
```
[
  {
    "labels": {
      "alertname": "Test Pagerduty Alert
    },
    "annotations": {
      "link": "https://example.com",
      "summary": "This is a testing alert!"
    },
    "generatorURL": "http://my.testing.script.local" 
  }
]
``` 

**Expected behavior**
Receive an alert from my pagerduty. But no alert comes through to my pagerduty. 

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [kustomize]

**Additional Context**
I have tried this using prometheus alertmanager v0.26.0 with the same configurations and was able to receive an alert from pagerduty correctly.
