### ISSUE TITLE
Query Rejection for Metadata Queries Bug

### ISSUE THREAD

**Issue by erlan-z** [cortexproject/cortex#6143]
**Describe the bug**
When [Query Rejection](https://github.com/cortexproject/cortex/pull/6005) configured with only properties that is not applicable for the API, then it rejects all the metadata queries. For example, dashboard_uid and panel_id headers are not provided for Metadata queries, and if query rejection configured to only those two fields, then it will reject all the Metadata queries for that tenant. 

**To Reproduce**
Configure Query rejection with below config
```
    query_rejection:
      enabled: true
      query_attributes:
        - dashboard_uid: "dash123"
          panel_id: "panel123"
```
1. Start Cortex (SHA or version)
2. Perform Operations(Query metadata API)

**Expected behavior**
It should only reject queries that is matching the query_attributes. It shouldn't be rejecting metadata queries because they don't match (no dashboard_uid or panel_id header for them)

**Environment:**
 - Any

**Additional Context**
