### ISSUE TITLE
Help Request: Alertmanager configuration not loaded when S3 backend is enabled

### ISSUE THREAD

**Issue by geeky-akshay** [cortexproject/cortex#6486]
**Describe the bug**
I need a way to correctly configure alertmanager. I'm using official cortex helm chart to install cortex in my AWS EKS cluster. I've configured S3 backend storage for alertmanager, blocks and ruler. Here is my config
```
    config:
      auth_enabled: true
      alertmanager:
        enable_api: true
        enabled_tenants: "tenantfoo"
      alertmanager_storage:
        backend: s3
        s3:
          endpoint: '${S3_BUCKET_HOST}'
          region: '${S3_BUCKET_REGION}'
          bucket_name: '${S3_BUCKET_NAME}'
          access_key_id: '${S3_ACCESS_KEY_ID}'
          secret_access_key: '${S3_ACCESS_KEY_SECRET}'
          insecure: true
      blocks_storage:
        backend: s3
        s3:
          endpoint: '${S3_BUCKET_HOST}'
          region: '${S3_BUCKET_REGION}'
          bucket_name: '${S3_BUCKET_NAME}'
          access_key_id: '${S3_ACCESS_KEY_ID}'
          secret_access_key: '${S3_ACCESS_KEY_SECRET}'
          insecure: true
        bucket_store:
          sync_dir: "/data"
        tsdb:
          dir: "/data"
      compactor:
        enabled_tenants: "tenantfoo"
      ruler:
        enabled_tenants: "tenantfoo"
      ruler_storage:
        backend: s3
        s3:
          endpoint: '${S3_BUCKET_HOST}'
          region: '${S3_BUCKET_REGION}'
          bucket_name: '${S3_BUCKET_NAME}'
          access_key_id: '${S3_ACCESS_KEY_ID}'
          secret_access_key: '${S3_ACCESS_KEY_SECRET}'
          insecure: true
      store_gateway:
        enabled_tenants: "tenantfoo"
      querier:
        store_gateway_addresses: "dns+cortex-store-gateway-headless.cortex.svc.cluster.local:9095"
```
I've enabled sidecar to discover and load the alertmanager configuration
```
alertmanager:
  sidecar:
    enabled: true
    searchNamespace: "cortex"
```
Here is my alertmanager configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    k8s-sidecar-target-directory: /data/tenantfoo
  labels:
    cortex_alertmanager: "1"
  name: tenantfoo-alertmanager-config
  namespace: cortex
data:
  tenantfoo.yaml: |
  ...
```
When I try to query the `/api/prom/alertmanager` I expect to see the Alertmanager UI, instead I get "The alertmanager is not configured"
```
sh-5.1$ curl -XGET -H "X-Scope-OrgID: tenantfoo" http://cortex-alertmanager:8080/api/prom/alertmanager
the Alertmanager is not configured
```
The alertmanager log says, `deleted local directory for user tenantfoo`
```
ts=2025-01-07T08:03:11.440508102Z caller=multitenant.go:690 level=info component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"
ts=2025-01-07T08:03:11.450816098Z caller=multitenant.go:802 level=debug component=MultiTenantAlertmanager msg="adding configurations" num_configs=0
ts=2025-01-07T08:03:11.451004079Z caller=multitenant.go:1272 level=info component=MultiTenantAlertmanager msg="deleted local directory for user" dir=data/tenantfoo user=tenantfoo
ts=2025-01-07T08:03:58.512064572Z caller=multitenant.go:1074 level=debug component=MultiTenantAlertmanager msg="the Alertmanager has no configuration and no fallback specified" user=tenantfoo
ts=2025-01-07T08:03:58.512131746Z caller=logging.go:114 level=debug traceID=02f7835b0527012e msg="GET /api/prom/alertmanager (404) 100.096µs"
```
can anyone tell me why i'm getting the log 'deleted local directory for user' and what is the correct way to load the alertmanager config if sidecar is not the right way?
Thanks!
